using System.Net;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

namespace ClankerWorld.Simulation.Cognition;

/// <summary>
/// Providers are interchangeable decision sources. They never own simulation
/// authority: the cognition runtime admits their structured result and the
/// world kernel still validates and executes the selected intention.
/// </summary>
public enum DecisionProviderKind
{
    Deterministic,
    Jev,
    LargeLanguageModel,
}

/// <summary>
/// A legal intention generated by authoritative simulation code. The provider
/// may choose among these candidates, but may not invent a new action ID.
/// Candidates should be ordered with the safest local fallback first.
/// </summary>
public sealed record CognitionCandidate(
    string Id,
    string Description,
    int DeterministicPriority = 0,
    string? DestinationId = null,
    string? DestinationName = null)
{
    public void Validate()
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(Id);
        ArgumentException.ThrowIfNullOrWhiteSpace(Description);
        if (DeterministicPriority < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(DeterministicPriority));
        }
    }
}

/// <summary>A bounded excerpt of an existing, actor-owned memory or belief.</summary>
public sealed record CognitionMemoryExcerpt(
    string Id,
    string OwnerId,
    string SubjectId,
    string Summary,
    long SourceTick,
    string Kind = "experience",
    string? Visibility = null,
    string? Provenance = null,
    int? ConfidenceBasisPoints = null,
    string? SourceAgentId = null,
    long? SourceEventId = null,
    bool IsCorrected = false,
    int ImportanceBasisPoints = 0,
    int ImportanceConfidenceBasisPoints = 0);

/// <summary>
/// A source record Jev may rate while it is already choosing a routine action.
/// IDs stay local to the host; the provider sees only a per-request index.
/// </summary>
public sealed record CognitionMemoryCompactionCandidate(
    string Id,
    string OwnerId,
    string Kind,
    string SubjectId,
    string Summary,
    long SourceTick,
    string? Visibility = null,
    string? Provenance = null,
    int? ConfidenceBasisPoints = null,
    string? SourceAgentId = null,
    long? SourceEventId = null,
    bool IsCorrected = false);

/// <summary>A Jev salience assessment of one source record, not a world fact.</summary>
public sealed record CognitionMemoryCompactionScore(
    string Id,
    string OwnerId,
    string Kind,
    long SourceTick,
    int ImportanceBasisPoints,
    int ConfidenceBasisPoints);

/// <summary>A compact fact from the observing agent's own map or field records.</summary>
public sealed record CognitionKnowledgeFact(
    int X,
    int Y,
    string Terrain,
    IReadOnlyList<string> ResourceKinds,
    string DiscovererId,
    long LearnedTick,
    string Acquisition);

/// <summary>
/// One frozen estate lot offered to a will by a per-request key such as <c>item:1</c>.
/// A vessel's contents, such as "3 fresh_water", go with it and are not offered separately.
/// </summary>
public sealed record CognitionWillItem(string Key, string Kind, int Quantity,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? Contents = null);

/// <summary>
/// A living person, or the dead agent's Town, a will may name. The key is a
/// server-minted ID such as <c>will:heir:{id}</c>; the provider may not invent one.
/// </summary>
public sealed record CognitionWillHeir(string Key, string Name, string? Relation = null);

/// <summary>
/// The bounded post-death will context: what the dead agent owned and who may
/// inherit. The server still checks every choice against real ownership.
/// </summary>
public sealed record CognitionWillContext(
    IReadOnlyList<CognitionWillItem> Items,
    IReadOnlyList<CognitionWillHeir> Heirs)
{
    public const int MaximumItems = 24;
    public const int MaximumHeirChoices = 17;
    public const int MaximumNamedHeirs = 3;
    public const int MaximumHeirKeyLength = 160;
    public const string HouseholdCandidateId = "will:household";
    public const string HeirsCandidateId = "will:heirs";
    public const string EqualSplit = "equal";
    public const string ItemSplit = "items";

    public void Validate()
    {
        if (Items is null || Items.Count is 0 or > MaximumItems || Heirs is null || Heirs.Count > MaximumHeirChoices)
            throw new ArgumentException("The will context exceeds its bounds.", nameof(Items));
        var keys = new HashSet<string>(StringComparer.Ordinal);
        foreach (var item in Items)
        {
            if (item is null || !IsBoundedText(item.Key, 16) || !IsBoundedText(item.Kind, 48) ||
                item.Quantity <= 0 || item.Contents is not null && !IsBoundedText(item.Contents, 128) || !keys.Add(item.Key))
                throw new ArgumentException("A will item is malformed.", nameof(Items));
        }
        foreach (var heir in Heirs)
        {
            if (heir is null || !IsBoundedText(heir.Key, MaximumHeirKeyLength) || !IsBoundedText(heir.Name, 128) ||
                heir.Relation is not null && !IsBoundedText(heir.Relation, 32) || !keys.Add(heir.Key))
                throw new ArgumentException("A will heir is malformed.", nameof(Heirs));
        }
    }

    private static bool IsBoundedText(string? value, int maximumLength) =>
        !string.IsNullOrWhiteSpace(value) && value.Length <= maximumLength && !value.Any(char.IsControl);
}

/// <summary>
/// A provider's untrusted will reply. With no heirs the estate keeps the
/// household default; final words are optional either way.
/// </summary>
public sealed record CognitionWillChoice(
    IReadOnlyList<string> HeirKeys,
    string? Split = null,
    IReadOnlyDictionary<string, string>? ItemHeirs = null,
    string? FinalWords = null)
{
    /// <summary>
    /// Short enough that "Name's final words were: '…'" fits one bounded memory.
    /// </summary>
    public const int MaximumFinalWordsLength = 80;

    /// <summary>
    /// Plain one-line final words: control and invisible formatting characters
    /// become spaces, runs of spaces collapse, and text containing markup
    /// characters or longer than the limit is refused (null).
    /// </summary>
    public static string? NormalizeFinalWords(string? value)
    {
        if (value is null) return null;
        var builder = new StringBuilder(Math.Min(value.Length, 512));
        var pendingSpace = false;
        foreach (var character in value)
        {
            if (char.IsWhiteSpace(character) || char.IsControl(character) ||
                char.GetUnicodeCategory(character) is System.Globalization.UnicodeCategory.Format or
                    System.Globalization.UnicodeCategory.LineSeparator or System.Globalization.UnicodeCategory.ParagraphSeparator or
                    System.Globalization.UnicodeCategory.Surrogate or System.Globalization.UnicodeCategory.PrivateUse or
                    System.Globalization.UnicodeCategory.OtherNotAssigned)
            {
                pendingSpace = builder.Length > 0;
                continue;
            }
            if (character is '<' or '>' or '[' or ']' or '{' or '}' or '`') return null;
            if (pendingSpace) builder.Append(' ');
            pendingSpace = false;
            builder.Append(character);
            if (builder.Length > MaximumFinalWordsLength) return null;
        }
        return builder.Length == 0 ? null : builder.ToString();
    }

    public void Validate()
    {
        if (HeirKeys is null || HeirKeys.Count > CognitionWillContext.MaximumNamedHeirs ||
            HeirKeys.Any(key => string.IsNullOrWhiteSpace(key) || key.Length > CognitionWillContext.MaximumHeirKeyLength) ||
            HeirKeys.Distinct(StringComparer.Ordinal).Count() != HeirKeys.Count)
            throw new ArgumentOutOfRangeException(nameof(HeirKeys));
        if (HeirKeys.Count == 0 ? Split is not null || ItemHeirs is not null
            : Split is not (CognitionWillContext.EqualSplit or CognitionWillContext.ItemSplit) ||
              Split == CognitionWillContext.EqualSplit && ItemHeirs is not null)
            throw new ArgumentOutOfRangeException(nameof(Split));
        if (ItemHeirs is { } items && (items.Count > CognitionWillContext.MaximumItems ||
            items.Any(item => string.IsNullOrWhiteSpace(item.Key) || item.Key.Length > 16 ||
                !HeirKeys.Contains(item.Value, StringComparer.Ordinal))))
            throw new ArgumentOutOfRangeException(nameof(ItemHeirs));
        if (FinalWords is not null && NormalizeFinalWords(FinalWords) != FinalWords)
            throw new ArgumentOutOfRangeException(nameof(FinalWords));
    }
}

/// <summary>
/// Actor-owned context only; absent survival data remains unknown, not invented.
/// <paramref name="HousingNote"/> explains the actor's housing and current House capacity when known.
/// <paramref name="ContinuityNote"/> explains the low-population continuity rule to a partner it applies to.
/// <paramref name="DepartureNote"/> summarizes goods to collect or return and paused household work after a departure.
/// <paramref name="TownMembershipNote"/> states recorded Town membership, its rights and any admission the actor knows of.
/// <paramref name="AllowedChildSurnames"/> lists the chosen biological parents' surnames during a child's naming request;
/// an empty list means no parental surname is available, while null means the childhood restriction does not apply.
/// </summary>
public sealed record CognitionSelfContext(
    string OwnerId, string Name, string LifeStage, string Personality, string Aspiration,
    string? HouseholdId, int? WarmthBasisPoints, int? IllnessBasisPoints, string? RecentThought,
    string? HouseholdName = null, string? TownName = null, string? HousingNote = null,
    string? EquipmentNote = null, string? ContinuityNote = null, string? DepartureNote = null, string? CivicNote = null,
    string? MedicalCareNote = null, string? TownMembershipNote = null,
    string? ToolMakingRequestNote = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] IReadOnlyList<string>? AllowedChildSurnames = null);

/// <summary>
/// An exact owner message addressed to this actor. The authoritative identity
/// fields stay with the observation for admission; providers receive only the
/// instruction ID, outside-observer provenance, wording and recognized task.
/// </summary>
public sealed record CognitionObserverGuidance(
    string InstructionId,
    string IssuerId,
    string TargetInhabitantId,
    string Kind,
    string Text,
    long SubmittedTick,
    long RunEpoch,
    long SubmissionSequence,
    string? UnderstoodTask,
    bool ReplyAllowed);

/// <summary>A short optional response addressed to one requested observer message.</summary>
public sealed record CognitionObserverReply(string InstructionId, string Text);

/// <summary>
/// The exact observed guidance snapshot carried through cognition admission.
/// This is transient dispatch evidence; the runtime writes any accepted result
/// back to the matching authoritative instruction record.
/// </summary>
public sealed record CognitionObserverGuidanceResult(
    string WorldId,
    string InhabitantId,
    string RequestId,
    long RunEpoch,
    long DecisionGeneration,
    string ObservationDigest,
    IReadOnlyList<CognitionObserverGuidance> Messages,
    IReadOnlyList<CognitionObserverReply> Replies);

/// <summary>
/// Compact, provider-neutral state supplied to a decision provider. It is an
/// observation, not a mutable world object or an omniscient world dump.
/// </summary>
public sealed record InhabitantObservation(
    string InhabitantId,
    long WorldTick,
    long RunEpoch,
    long DecisionGeneration,
    string ObservationDigest,
    int HungerBasisPoints,
    IReadOnlyList<CognitionCandidate> Candidates,
    bool NeedsName = false,
    bool RequiresPersonalProvider = false,
    IReadOnlyList<CognitionMemoryExcerpt>? RetrievedMemories = null,
    IReadOnlyList<CognitionMemoryCompactionCandidate>? MemoryCompactionCandidates = null,
    IReadOnlyList<CognitionKnowledgeFact>? KnownMapFacts = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] CognitionSelfContext? Self = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] bool NeedsPersonality = false,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)] bool NeedsAspiration = false,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] CognitionWillContext? Will = null)
{
    public const int MaximumObserverGuidanceCount = 8;
    public const int MaximumObserverGuidanceTextLength = 512;

    /// <summary>The opaque current world identity used to bind observer input and its reply.</summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? WorldId { get; init; }

    /// <summary>Pending suggestions and recognized orders addressed to this actor only.</summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<CognitionObserverGuidance>? ObserverGuidance { get; init; }

    // Scheduler control metadata is materialized only for duplicate-name
    // retries and live conversation choices. It is not stored in a save or
    // sent to a provider.
    [JsonIgnore]
    public bool IsNameRetry { get; init; }

    [JsonIgnore]
    public string? ConversationChoiceContext { get; init; }

    /// <summary>Host-only identity binding this decision to the current persistent order.</summary>
    [JsonIgnore]
    public string? OperativeOrderInstructionId { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? IdentityMoment { get; init; }

    public void Validate()
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(InhabitantId);
        ArgumentException.ThrowIfNullOrWhiteSpace(ObservationDigest);
        if (WorldTick < 0 || RunEpoch < 0 || DecisionGeneration < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(WorldTick));
        }

        if (ConversationChoiceContext is { Length: > 512 })
            throw new ArgumentException("Conversation choice context exceeds its bound.", nameof(ConversationChoiceContext));

        if (WorldId is not null && (string.IsNullOrWhiteSpace(WorldId) || WorldId.Length > 128 || WorldId.Any(char.IsControl)))
            throw new ArgumentException("World identity must be bounded and contain no control characters.", nameof(WorldId));
        if (OperativeOrderInstructionId is { } orderId &&
            (string.IsNullOrWhiteSpace(orderId) || orderId.Length > 128 || orderId.Any(char.IsControl)))
            throw new ArgumentException("Operative order identity must be bounded and contain no control characters.", nameof(OperativeOrderInstructionId));

        var guidance = ObserverGuidance ?? [];
        if (guidance.Count > MaximumObserverGuidanceCount || guidance.Count > 0 && WorldId is null)
            throw new ArgumentException("Observer guidance must be bounded and bound to a world.", nameof(ObserverGuidance));
        var instructionIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var message in guidance)
        {
            ArgumentNullException.ThrowIfNull(message);
            if (string.IsNullOrWhiteSpace(message.InstructionId) || message.InstructionId.Length > 128 ||
                string.IsNullOrWhiteSpace(message.IssuerId) || message.IssuerId.Length > 128 ||
                message.TargetInhabitantId != InhabitantId ||
                message.Kind is not ("suggestive" or "must_do") ||
                string.IsNullOrWhiteSpace(message.Text) || message.Text.Length > MaximumObserverGuidanceTextLength ||
                message.Text.Any(char.IsControl) ||
                message.SubmittedTick < 0 || message.SubmittedTick > WorldTick ||
                message.RunEpoch < 0 || message.RunEpoch > RunEpoch || message.SubmissionSequence <= 0 ||
                !instructionIds.Add(message.InstructionId) ||
                message.Kind == "must_do" && message.UnderstoodTask is not
                    ("eat one carried food item" or "travel within gathering range of an available food source" or
                        "gather several food servings from a nearby food source" or
                        "gather the requested material from a natural source" or
                        "collect your own stored or dropped material" or
                        "collect your own stored or dropped food" or
                        "collect your own stored or dropped equipment" or
                        "store your own carried material in your House" or
                        "repair your own worn clothing or carrying aid" or
                        "repair your own worn tool" or
                        "till a field for your household" or
                        "plant the requested crop in your household field" or
                        "tend your household crop" or
                        "harvest your household crop" or
                        "travel to the exact tile named in this order" or
                        "accept primary care of the named child through their guardian search") ||
                message.Kind == "suggestive" && message.UnderstoodTask is not null)
                throw new ArgumentException("Observer guidance must be bounded, target-owned and uniquely identified.", nameof(ObserverGuidance));
        }

        if (IdentityMoment is { } moment && (string.IsNullOrWhiteSpace(moment) ||
            moment.Length > 128 || moment.Any(char.IsControl) || !RequiresPersonalProvider ||
            !NeedsPersonality || !NeedsAspiration || NeedsName || Candidates.Count != 1 ||
            Candidates[0].Id != "identity_optional"))
            throw new ArgumentException("The life-moment identity request is invalid.", nameof(IdentityMoment));

        if (HungerBasisPoints is < 0 or > 10_000)
        {
            throw new ArgumentOutOfRangeException(nameof(HungerBasisPoints));
        }

        if (Self is { } self && (self.OwnerId != InhabitantId ||
            string.IsNullOrWhiteSpace(self.Name) || self.Name.Length > 128 ||
            string.IsNullOrWhiteSpace(self.LifeStage) || self.LifeStage.Length > 32 ||
            self.Personality is null || self.Personality.Length > 256 ||
            self.Aspiration is null || self.Aspiration.Length > 256 ||
            self.HouseholdId?.Length > 128 || self.RecentThought?.Length > 160 ||
            self.HouseholdName?.Length > 128 || self.TownName?.Length > 128 || self.HousingNote?.Length > 256 ||
            self.EquipmentNote?.Length > 256 || self.ContinuityNote?.Length > 256 || self.DepartureNote?.Length > 256 ||
            self.CivicNote?.Length > 1024 || self.MedicalCareNote?.Length > 256 || self.TownMembershipNote?.Length > 256 ||
            self.ToolMakingRequestNote?.Length > 256 ||
            self.WarmthBasisPoints is < 0 or > 10_000 || self.IllnessBasisPoints is < 0 or > 10_000))
            throw new ArgumentException("Self context must be bounded and owned by the actor.", nameof(Self));

        if (Self?.AllowedChildSurnames is { } surnames &&
            (surnames.Count > 2 || surnames.Any(surname => string.IsNullOrWhiteSpace(surname) ||
                surname.Length > 128 || surname.Any(char.IsControl)) ||
             surnames.Distinct(StringComparer.OrdinalIgnoreCase).Count() != surnames.Count))
            throw new ArgumentException("Child naming context must contain at most two bounded parental surnames.", nameof(Self));

        if (Candidates is null || Candidates.Count == 0)
        {
            throw new ArgumentException("A cognition observation must contain at least one legal candidate.", nameof(Candidates));
        }

        Will?.Validate();

        var ids = new HashSet<string>(StringComparer.Ordinal);
        foreach (var candidate in Candidates)
        {
            ArgumentNullException.ThrowIfNull(candidate);
            candidate.Validate();
            if (!ids.Add(candidate.Id))
            {
                throw new ArgumentException("Cognition candidate IDs must be unique.", nameof(Candidates));
            }
        }

        if (RetrievedMemories is { Count: > 4 })
            throw new ArgumentException("Memory context exceeds the four-record budget.", nameof(RetrievedMemories));
        foreach (var memory in RetrievedMemories ?? [])
        {
            ArgumentNullException.ThrowIfNull(memory);
            if (!string.Equals(memory.OwnerId, InhabitantId, StringComparison.Ordinal) ||
                string.IsNullOrWhiteSpace(memory.Id) || string.IsNullOrWhiteSpace(memory.SubjectId) ||
                memory.Id.Length > 128 || memory.SubjectId.Length > 128 ||
                string.IsNullOrWhiteSpace(memory.Summary) || memory.Summary.Length > 160 ||
                memory.SourceTick < 0 || memory.SourceTick > WorldTick ||
                !IsMemoryKind(memory.Kind) || !IsOptionalBounded(memory.Visibility, 32) ||
                memory.Provenance is not (null or "firsthand" or "hearsay" or "inference") ||
                memory.ConfidenceBasisPoints is < 0 or > 10_000 ||
                !IsOptionalBounded(memory.SourceAgentId, 128) || memory.SourceEventId is <= 0 ||
                memory.ImportanceBasisPoints is < 0 or > 10_000 ||
                memory.ImportanceConfidenceBasisPoints is < 0 or > 10_000)
                throw new ArgumentException("Memory context must be bounded and owned by the actor.", nameof(RetrievedMemories));
        }

        if (MemoryCompactionCandidates is { Count: > 12 })
            throw new ArgumentException("Memory compaction context exceeds the twelve-record budget.", nameof(MemoryCompactionCandidates));
        var compactionIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var candidate in MemoryCompactionCandidates ?? [])
        {
            ArgumentNullException.ThrowIfNull(candidate);
            if (!string.Equals(candidate.OwnerId, InhabitantId, StringComparison.Ordinal) ||
                string.IsNullOrWhiteSpace(candidate.Id) || candidate.Id.Length > 128 ||
                !compactionIds.Add($"{candidate.Kind}:{candidate.Id}") ||
                !IsMemoryKind(candidate.Kind) || string.IsNullOrWhiteSpace(candidate.SubjectId) ||
                candidate.SubjectId.Length > 128 || string.IsNullOrWhiteSpace(candidate.Summary) ||
                candidate.Summary.Length > 160 || candidate.SourceTick < 0 || candidate.SourceTick > WorldTick ||
                !IsOptionalBounded(candidate.Visibility, 32) ||
                candidate.Provenance is not (null or "firsthand" or "hearsay" or "inference") ||
                candidate.ConfidenceBasisPoints is < 0 or > 10_000 ||
                !IsOptionalBounded(candidate.SourceAgentId, 128) || candidate.SourceEventId is <= 0)
                throw new ArgumentException("Memory compaction context must be bounded and owned by the actor.", nameof(MemoryCompactionCandidates));
        }

        if (KnownMapFacts is { Count: > 16 })
            throw new ArgumentException("Map-knowledge context exceeds the sixteen-fact budget.", nameof(KnownMapFacts));
        foreach (var fact in KnownMapFacts ?? [])
        {
            ArgumentNullException.ThrowIfNull(fact);
            if (fact.X < 0 || fact.Y < 0 || string.IsNullOrWhiteSpace(fact.Terrain) || fact.Terrain.Length > 32 ||
                fact.ResourceKinds is null || fact.ResourceKinds.Count > 4 ||
                fact.ResourceKinds.Any(kind => string.IsNullOrWhiteSpace(kind) || kind.Length > 48) ||
                string.IsNullOrWhiteSpace(fact.DiscovererId) || fact.DiscovererId.Length > 128 ||
                fact.LearnedTick < 0 || fact.LearnedTick > WorldTick ||
                fact.Acquisition is not ("firsthand" or "shared" or "read"))
                throw new ArgumentException("Map-knowledge context must be bounded and privately owned by the actor.", nameof(KnownMapFacts));
        }
    }

    private static bool IsMemoryKind(string kind) => kind is "experience" or "belief";

    private static bool IsOptionalBounded(string? value, int maximumLength) =>
        value is null || value.Length <= maximumLength && !value.Any(char.IsControl);
}

/// <summary>
/// A provider request has a server-minted request ID and captures every epoch
/// needed to reject a response that belongs to an older world boundary.
/// </summary>
public sealed record CognitionDecisionRequest(
    string RequestId,
    long ProviderEpoch,
    InhabitantObservation Observation)
{
    public void Validate()
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(RequestId);
        if (ProviderEpoch < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(ProviderEpoch));
        }

        ArgumentNullException.ThrowIfNull(Observation);
        Observation.Validate();
    }
}

/// <summary>
/// A typed provider response. Probabilities are telemetry and admission
/// evidence; the selected ID is still checked against the request's legal
/// candidate set before it can become an intention.
/// </summary>
public sealed record CognitionLandTile(int X, int Y);

public sealed record CognitionDecisionResponse(
    string RequestId,
    string InhabitantId,
    DecisionProviderKind Provider,
    long ProviderEpoch,
    long RunEpoch,
    long DecisionGeneration,
    string ObservationDigest,
    string SelectedCandidateId,
    double Confidence,
    IReadOnlyDictionary<string, double> Probabilities,
    CognitionUsage? Usage = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? PrivateThought = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? ChosenName = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] IReadOnlyList<CognitionMemoryCompactionScore>? MemoryCompactionScores = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? ChosenPersonality = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? ChosenAspiration = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? CivicProposal = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] IReadOnlyList<string>? CivicBallot = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] IReadOnlyList<CognitionObserverReply>? ObserverReplies = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] CognitionWillChoice? Will = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] IReadOnlyList<CognitionLandTile>? CivicLandTiles = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] CognitionLandHearingChoice? CivicLandHearing = null)
{
    public const int MaximumCivicLandTiles = 64;
    public const int MaximumPrivateThoughtLength = 160;
    public const int MaximumObserverReplyLength = 160;
    public const int MaximumChosenNameLength = 48;
    public const int MaximumIdentityTextLength = 256;

    public static string? NormalizeIdentityText(string? value)
    {
        var text = value?.Trim();
        return text is { Length: > 0 and <= MaximumIdentityTextLength } &&
            !text.Any(char.IsControl) ? text : null;
    }

    public static string? NormalizePrivateThought(string? value)
    {
        var text = value?.Trim();
        return text is { Length: > 0 and <= MaximumPrivateThoughtLength } &&
            !text.Any(char.IsControl) ? text : null;
    }

    public static string? NormalizeObserverReply(string? value)
    {
        var text = value?.Trim();
        return text is { Length: > 0 and <= MaximumObserverReplyLength } &&
            !text.Any(char.IsControl) ? text : null;
    }

    public static string? NormalizeChosenName(string? value)
    {
        var text = value?.Trim();
        return text is { Length: > 0 and <= MaximumChosenNameLength } &&
            !text.Any(char.IsControl) ? text : null;
    }

    public void Validate()
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(RequestId);
        ArgumentException.ThrowIfNullOrWhiteSpace(InhabitantId);
        ArgumentException.ThrowIfNullOrWhiteSpace(ObservationDigest);
        ArgumentException.ThrowIfNullOrWhiteSpace(SelectedCandidateId);
        if (ProviderEpoch < 0 || RunEpoch < 0 || DecisionGeneration < 0 ||
            double.IsNaN(Confidence) || double.IsInfinity(Confidence) || Confidence is < 0 or > 1)
        {
            throw new ArgumentOutOfRangeException(nameof(Confidence));
        }

        if (Probabilities is null)
        {
            throw new ArgumentNullException(nameof(Probabilities));
        }

        foreach (var probability in Probabilities)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(probability.Key);
            if (double.IsNaN(probability.Value) || double.IsInfinity(probability.Value) || probability.Value is < 0 or > 1)
            {
                throw new ArgumentOutOfRangeException(nameof(Probabilities));
            }
        }

        if (PrivateThought is not null && NormalizePrivateThought(PrivateThought) != PrivateThought)
        {
            throw new ArgumentOutOfRangeException(nameof(PrivateThought));
        }

        if (ChosenName is not null && NormalizeChosenName(ChosenName) != ChosenName)
            throw new ArgumentOutOfRangeException(nameof(ChosenName));
        if (ChosenPersonality is not null && NormalizeIdentityText(ChosenPersonality) != ChosenPersonality ||
            ChosenAspiration is not null && NormalizeIdentityText(ChosenAspiration) != ChosenAspiration)
            throw new ArgumentOutOfRangeException(nameof(ChosenPersonality));

        if (CivicProposal is not null && NormalizeIdentityText(CivicProposal) != CivicProposal ||
            CivicBallot is { Count: > 3 } || CivicBallot?.Any(id => string.IsNullOrWhiteSpace(id) || id.Any(char.IsControl)) == true)
            throw new ArgumentOutOfRangeException(nameof(CivicProposal));
        if (ObserverReplies is { Count: > InhabitantObservation.MaximumObserverGuidanceCount })
            throw new ArgumentOutOfRangeException(nameof(ObserverReplies));
        if (CivicLandTiles is { Count: 0 or > MaximumCivicLandTiles } || CivicLandTiles?.Any(tile => tile is null) == true)
            throw new ArgumentOutOfRangeException(nameof(CivicLandTiles));
        CivicLandHearing?.Validate();
        var observerReplyIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var reply in ObserverReplies ?? [])
        {
            ArgumentNullException.ThrowIfNull(reply);
            if (string.IsNullOrWhiteSpace(reply.InstructionId) || reply.InstructionId.Length > 128 ||
                NormalizeObserverReply(reply.Text) != reply.Text || !observerReplyIds.Add(reply.InstructionId))
                throw new ArgumentOutOfRangeException(nameof(ObserverReplies));
        }

        if (MemoryCompactionScores is { Count: > 12 })
            throw new ArgumentOutOfRangeException(nameof(MemoryCompactionScores));
        var compactionIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var score in MemoryCompactionScores ?? [])
        {
            ArgumentNullException.ThrowIfNull(score);
            if (string.IsNullOrWhiteSpace(score.Id) || score.Id.Length > 128 ||
                string.IsNullOrWhiteSpace(score.OwnerId) || score.OwnerId.Length > 128 ||
                score.Kind is not ("experience" or "belief") || score.SourceTick < 0 ||
                score.ImportanceBasisPoints is < 0 or > 10_000 ||
                score.ConfidenceBasisPoints is < 0 or > 10_000 ||
                !compactionIds.Add($"{score.Kind}:{score.Id}"))
                throw new ArgumentOutOfRangeException(nameof(MemoryCompactionScores));
        }

        Will?.Validate();
        Usage?.Validate();
    }
}

/// <summary>
/// Provider usage is telemetry only. It is retained with a request record so
/// an owner can see that a hosted decision happened without storing secrets or
/// raw provider reasoning in world state.
/// </summary>
public sealed record CognitionUsage(
    string? ModelId,
    int InputTokens,
    int OutputTokens,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] long? LatencyMilliseconds = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? ProviderId = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? Role = null)
{
    public void Validate()
    {
        if (InputTokens < 0 || OutputTokens < 0 || LatencyMilliseconds < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(InputTokens));
        }

        if (ModelId is not null && string.IsNullOrWhiteSpace(ModelId))
        {
            throw new ArgumentException("A provider model ID cannot be blank when supplied.", nameof(ModelId));
        }
    }
}

/// <summary>
/// Provider implementations are intentionally small. A hosted provider can
/// be plugged in later without changing the simulation or persistence model.
/// </summary>
public interface IDecisionProvider
{
    DecisionProviderKind Kind { get; }

    long ProviderEpoch { get; }

    DecisionProviderKind KindFor(InhabitantObservation observation) => Kind;

    ValueTask<CognitionDecisionResponse> DecideAsync(
        CognitionDecisionRequest request,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// The always-available local provider. The authoritative candidate generator
/// orders candidates by deterministic priority, so this provider is a stable
/// fallback rather than a fake attempt at open-ended cognition.
/// </summary>
public sealed class DeterministicDecisionProvider : IDecisionProvider
{
    public DecisionProviderKind Kind => DecisionProviderKind.Deterministic;

    public long ProviderEpoch => 0;

    public ValueTask<CognitionDecisionResponse> DecideAsync(
        CognitionDecisionRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        request.Validate();
        cancellationToken.ThrowIfCancellationRequested();

        var selected = request.Observation.Candidates
            .OrderBy(candidate => candidate.DeterministicPriority)
            .ThenBy(candidate => candidate.Id, StringComparer.Ordinal)
            .First();
        var probabilities = request.Observation.Candidates
            .ToDictionary(
                candidate => candidate.Id,
                candidate => string.Equals(candidate.Id, selected.Id, StringComparison.Ordinal) ? 1d : 0d,
                StringComparer.Ordinal);

        return ValueTask.FromResult(new CognitionDecisionResponse(
            request.RequestId,
            request.Observation.InhabitantId,
            Kind,
            ProviderEpoch,
            request.Observation.RunEpoch,
            request.Observation.DecisionGeneration,
            request.Observation.ObservationDigest,
            selected.Id,
            1d,
            new ReadOnlyDictionary<string, double>(probabilities)));
    }
}

/// <summary>
/// Optional TypeSafe System One adapter. The API key is obtained at call time
/// and is never part of a request, save document, telemetry event, or options
/// record. If it is absent, the cognition runtime treats this as an ordinary
/// provider failure and uses its deterministic fallback.
/// </summary>
public sealed class JevDecisionProvider : IDecisionProvider
{
    private const string ChoiceQuestionId = "selected_candidate";
    private static readonly string[] MemoryImportanceCriteria =
    [
        "Minor, redundant, or unlikely to help the agent again.",
        "Possibly useful context for the agent's future choices.",
        "Important long-term context that should remain easy to retrieve.",
    ];
    private readonly HttpClient httpClient;
    private readonly Func<string?> apiKeyAccessor;
    private readonly Uri endpoint;
    private readonly string model;
    private readonly TimeSpan requestTimeout;
    private readonly ModelNeedFormat needFormat;

    public JevDecisionProvider(
        HttpClient httpClient,
        Func<string?> apiKeyAccessor,
        Uri? endpoint = null,
        string model = "jev-1.13.0",
        TimeSpan? requestTimeout = null,
        long providerEpoch = 1,
        ModelNeedFormat needFormat = ModelNeedWords.DefaultFormat)
    {
        this.httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        this.apiKeyAccessor = apiKeyAccessor ?? throw new ArgumentNullException(nameof(apiKeyAccessor));
        this.endpoint = endpoint ?? new Uri("https://api.typesafe.ai/v1/systemone", UriKind.Absolute);
        if (!this.endpoint.IsAbsoluteUri || this.endpoint.Scheme != Uri.UriSchemeHttps)
        {
            throw new ArgumentException("The Jev endpoint must be an absolute HTTPS URI.", nameof(endpoint));
        }

        this.model = NormalizeRequiredText(model, nameof(model));
        this.requestTimeout = requestTimeout ?? TimeSpan.FromSeconds(30);
        if (this.requestTimeout <= TimeSpan.Zero || this.requestTimeout > TimeSpan.FromMinutes(5))
        {
            throw new ArgumentOutOfRangeException(nameof(requestTimeout));
        }

        ArgumentOutOfRangeException.ThrowIfNegative(providerEpoch);
        ProviderEpoch = providerEpoch;
        this.needFormat = Enum.IsDefined(needFormat) ? needFormat : throw new ArgumentOutOfRangeException(nameof(needFormat));
    }

    public DecisionProviderKind Kind => DecisionProviderKind.Jev;

    public long ProviderEpoch { get; }

    public async ValueTask<CognitionDecisionResponse> DecideAsync(
        CognitionDecisionRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        request.Validate();
        cancellationToken.ThrowIfCancellationRequested();

        var apiKey = apiKeyAccessor()?.Trim();
        if (string.IsNullOrWhiteSpace(apiKey))
        {
            throw new CognitionProviderUnavailableException("missing_key", "Jev is enabled but no TypeSafe API key is configured.");
        }

        var questions = new Dictionary<string, JevQuestion>(StringComparer.Ordinal)
        {
            [ChoiceQuestionId] = new JevQuestion(
                "choice",
                "Choose exactly one legal candidate for the agent's next small action. " +
                (needFormat == ModelNeedFormat.Words
                    ? "fullness, warmth and illness each give the agent's current level in words, then the whole scale from worst to best."
                    : "hunger_basis_points says how well fed they are: 10000 is full and 0 is starving. " +
                        "warmth_basis_points is 0 dangerously cold to 10000 warm; illness_basis_points is 0 well to 10000 severely ill.") +
                " A null need is unknown.",
                request.Observation.Candidates.ToDictionary(
                    candidate => candidate.Id,
                    candidate => candidate.Description,
                    StringComparer.Ordinal)),
        };
        for (var index = 0; index < (request.Observation.MemoryCompactionCandidates?.Count ?? 0); index++)
        {
            questions[MemoryQuestionId(index)] = new JevQuestion(
                "score",
                "Rate how useful this source record is for the agent's future decisions and identity. " +
                "Preserve it if it records a lasting relationship, learned skill, major personal event, " +
                "or unresolved commitment. A belief is an uncertain account, not a verified world fact; " +
                "consider its provenance and confidence without treating it as authoritative.",
                MemoryImportanceCriteria);
        }

        var payload = new JevRequest(
            new
            {
                agent_id = request.Observation.InhabitantId,
                hunger_basis_points = request.Observation.HungerBasisPoints,
                warmth_basis_points = request.Observation.Self?.WarmthBasisPoints,
                illness_basis_points = request.Observation.Self?.IllnessBasisPoints,
                household = request.Observation.Self?.HouseholdName,
                town = request.Observation.Self?.TownName,
                town_membership = request.Observation.Self?.TownMembershipNote,
                housing = request.Observation.Self?.HousingNote,
                continuity = request.Observation.Self?.ContinuityNote,
                departure = request.Observation.Self?.DepartureNote,
                medical_care = request.Observation.Self?.MedicalCareNote,
                tool_making_request = request.Observation.Self?.ToolMakingRequestNote,
                candidates = request.Observation.Candidates.Select(candidate => new
                {
                    id = candidate.Id,
                    description = candidate.Description,
                    destination = candidate.DestinationName,
                }).ToArray(),
                memory_compaction_candidates = (request.Observation.MemoryCompactionCandidates ?? [])
                    .Select((candidate, index) => new
                    {
                        source_index = index,
                        kind = candidate.Kind,
                        subject_id = candidate.SubjectId,
                        summary = candidate.Summary,
                        source_tick = candidate.SourceTick,
                        visibility = candidate.Visibility,
                        provenance = candidate.Provenance,
                        confidence_basis_points = candidate.ConfidenceBasisPoints,
                        source_agent_id = candidate.SourceAgentId,
                        source_event_id = candidate.SourceEventId,
                        is_corrected = candidate.IsCorrected,
                    }).ToArray(),
            },
            model,
            questions);
        if (needFormat == ModelNeedFormat.Words)
            payload = payload with { State = DescribeNeedsInWords(payload.State, request.Observation) };

        var json = JsonSerializer.Serialize(payload, JsonOptions);
        using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        timeout.CancelAfter(requestTimeout);
        using var httpRequest = new HttpRequestMessage(HttpMethod.Post, endpoint)
        {
            Content = new StringContent(json, Encoding.UTF8, "application/json"),
        };
        httpRequest.Headers.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);

        using var response = await httpClient.SendAsync(
            httpRequest,
            HttpCompletionOption.ResponseHeadersRead,
            timeout.Token).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            throw new HttpRequestException(
                $"Jev returned HTTP {(int)response.StatusCode} ({response.StatusCode}).", null, response.StatusCode);
        }

        var responseBody = await ProviderResponseBody.ReadAsync(response.Content, timeout.Token).ConfigureAwait(false);
        return ParseResponse(request, responseBody);
    }

    private static CognitionDecisionResponse ParseResponse(
        CognitionDecisionRequest request,
        string responseBody)
    {
        try
        {
            using var document = JsonDocument.Parse(responseBody);
            var root = document.RootElement;
            var modelId = root.TryGetProperty("model", out var modelProperty)
                ? modelProperty.GetString()
                : null;
            var answer = root.GetProperty("answers").GetProperty(ChoiceQuestionId);
            if (!string.Equals(answer.GetProperty("type").GetString(), "choice", StringComparison.Ordinal))
            {
                throw new InvalidDataException("Jev returned a non-choice answer for the candidate question.");
            }

            var selected = answer.GetProperty("choice").GetString();
            var confidence = answer.GetProperty("confidence").GetDouble();
            var probabilities = answer.TryGetProperty("probabilities", out var probabilitiesProperty)
                ? probabilitiesProperty.EnumerateObject().ToDictionary(
                    property => property.Name,
                    property => property.Value.GetDouble(),
                    StringComparer.Ordinal)
                : request.Observation.Candidates.ToDictionary(candidate => candidate.Id,
                    candidate => candidate.Id == selected ? 1d : 0d, StringComparer.Ordinal);
            var usage = root.TryGetProperty("usage", out var usageProperty)
                ? new CognitionUsage(
                    modelId,
                    usageProperty.GetProperty("input_tokens").GetInt32(),
                    usageProperty.GetProperty("output_tokens").GetInt32())
                : modelId is null ? null : new CognitionUsage(modelId, 0, 0);
            var memoryCompactionScores = ReadMemoryCompactionScores(
                root.GetProperty("answers"), request.Observation);

            return new CognitionDecisionResponse(
                request.RequestId,
                request.Observation.InhabitantId,
                DecisionProviderKind.Jev,
                request.ProviderEpoch,
                request.Observation.RunEpoch,
                request.Observation.DecisionGeneration,
                request.Observation.ObservationDigest,
                NormalizeRequiredText(selected ?? string.Empty, "choice"),
                confidence,
                probabilities,
                usage,
                MemoryCompactionScores: memoryCompactionScores);
        }
        catch (JsonException exception)
        {
            throw new InvalidDataException("Jev returned malformed JSON.", exception);
        }
        catch (KeyNotFoundException exception)
        {
            throw new InvalidDataException("Jev returned an incomplete choice response.", exception);
        }
    }

    private static List<CognitionMemoryCompactionScore>? ReadMemoryCompactionScores(
        JsonElement answers,
        InhabitantObservation observation)
    {
        var candidates = observation.MemoryCompactionCandidates;
        if (candidates is null || candidates.Count == 0) return null;
        var scores = new List<CognitionMemoryCompactionScore>(candidates.Count);
        for (var index = 0; index < candidates.Count; index++)
        {
            if (!answers.TryGetProperty(MemoryQuestionId(index), out var answer) ||
                answer.ValueKind != JsonValueKind.Object ||
                !answer.TryGetProperty("type", out var type) || type.GetString() != "score" ||
                !answer.TryGetProperty("score", out var scoreValue) ||
                !scoreValue.TryGetDouble(out var score) || double.IsNaN(score) || double.IsInfinity(score) ||
                score is < 0 or > 2 ||
                !answer.TryGetProperty("confidence", out var confidenceValue) ||
                !confidenceValue.TryGetDouble(out var confidence) || double.IsNaN(confidence) ||
                double.IsInfinity(confidence) || confidence is < 0 or > 1)
                continue;

            var candidate = candidates[index];
            scores.Add(new CognitionMemoryCompactionScore(
                candidate.Id,
                candidate.OwnerId,
                candidate.Kind,
                candidate.SourceTick,
                (int)Math.Round(score * 5_000, MidpointRounding.AwayFromZero),
                (int)Math.Round(confidence * 10_000, MidpointRounding.AwayFromZero)));
        }
        return scores.Count == 0 ? null : scores;
    }

    private static string MemoryQuestionId(int index) => $"memory_salience_{index:D2}";

    private static JsonObject DescribeNeedsInWords(object state, InhabitantObservation observation)
    {
        var described = JsonSerializer.SerializeToNode(state, JsonOptions)!.AsObject();
        ModelNeedWords.ReplaceNumber(described, "hunger_basis_points", "fullness",
            ModelNeedWords.Fullness(observation.HungerBasisPoints));
        ModelNeedWords.ReplaceNumber(described, "warmth_basis_points", "warmth",
            observation.Self?.WarmthBasisPoints is { } warmth ? ModelNeedWords.Warmth(warmth) : null);
        ModelNeedWords.ReplaceNumber(described, "illness_basis_points", "illness",
            observation.Self?.IllnessBasisPoints is { } illness ? ModelNeedWords.Illness(illness) : null);
        return described;
    }

    private static string NormalizeRequiredText(string? value, string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value, name);
        return value.Trim();
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    private sealed record JevRequest(
        object State,
        string Model,
        IReadOnlyDictionary<string, JevQuestion> Questions);

    private sealed record JevQuestion(
        string Type,
        string Instructions,
        object Criteria);
}

/// <summary>
/// Adapter for providers that expose an OpenAI-compatible chat-completions
/// endpoint. OpenAI and Ollama Cloud use this same boundary. Endpoint, model,
/// and credential are supplied by the server-side provider registry and never
/// become world state.
///
/// The model is asked for one small JSON object containing a legal candidate
/// choice. The cognition runtime still validates the selected ID and executes
/// the action, so a hosted model never gains simulation authority.
/// </summary>
public sealed class OpenAiCompatibleDecisionProvider : IDecisionProvider
{
    private const string CommonNameInitials = "ABCDEFGHJKLMNPRSTVW";
    private readonly HttpClient httpClient;
    private readonly Func<string?> apiKeyAccessor;
    private readonly Uri endpoint;
    private readonly string model;
    private readonly TimeSpan requestTimeout;
    private readonly ModelNeedFormat needFormat;

    public OpenAiCompatibleDecisionProvider(
        HttpClient httpClient,
        Func<string?> apiKeyAccessor,
        Uri endpoint,
        string model,
        TimeSpan? requestTimeout = null,
        long providerEpoch = 2,
        ModelNeedFormat needFormat = ModelNeedWords.DefaultFormat)
    {
        this.httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        this.apiKeyAccessor = apiKeyAccessor ?? throw new ArgumentNullException(nameof(apiKeyAccessor));
        this.endpoint = endpoint ?? throw new ArgumentNullException(nameof(endpoint));
        if (!this.endpoint.IsAbsoluteUri ||
            (this.endpoint.Scheme != Uri.UriSchemeHttps && !IsAllowedLocalHttpEndpoint(this.endpoint)))
        {
            throw new ArgumentException(
                "The OpenAI-compatible endpoint must be HTTPS, or HTTP on loopback for local development.",
                nameof(endpoint));
        }

        this.model = NormalizeRequiredText(model, nameof(model));
        this.requestTimeout = requestTimeout ?? TimeSpan.FromSeconds(45);
        if (this.requestTimeout <= TimeSpan.Zero || this.requestTimeout > TimeSpan.FromMinutes(5))
        {
            throw new ArgumentOutOfRangeException(nameof(requestTimeout));
        }

        ArgumentOutOfRangeException.ThrowIfNegative(providerEpoch);
        ProviderEpoch = providerEpoch;
        this.needFormat = Enum.IsDefined(needFormat) ? needFormat : throw new ArgumentOutOfRangeException(nameof(needFormat));
    }

    public DecisionProviderKind Kind => DecisionProviderKind.LargeLanguageModel;

    public long ProviderEpoch { get; }

    public async ValueTask<CognitionDecisionResponse> DecideAsync(
        CognitionDecisionRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        request.Validate();
        cancellationToken.ThrowIfCancellationRequested();

        var apiKey = apiKeyAccessor()?.Trim();
        var words = needFormat == ModelNeedFormat.Words;
        object payload = request.Observation.Will is { } will ? CreateWillPayload(request, will) : new
        {
            model,
            response_format = new { type = "json_object" },
            messages = new object[]
            {
                new
                {
                    role = "system",
                    content = request.Observation.IdentityMoment is not null
                        ? "You are one agent reflecting on the named life moment in identity_moment. " +
                            "Self contains your current saved personality and aspiration. You may keep both or change either, in character. " +
                            "Return JSON only: selected_candidate_id must be identity_optional, confidence a number from 0 to 1. " +
                            "Optional chosen_personality and chosen_aspiration must each be at most 256 characters with no control characters. " +
                            "Omit them to keep your identity. This request chooses no physical action and cannot change your name. " +
                            "Keep the reply short and include no reasoning."
                        : "You are one agent living in a world with other agents, acting from your own needs and knowledge. Choose exactly one legal candidate. " +
                        (words
                            ? "Your needs are described in words: fullness, warmth and illness each give your current level, then the whole scale from worst to best. "
                            : "hunger_basis_points says how well fed you are: 10000 is full and 0 is starving. ") +
                        "Self context is your saved identity and condition, not other agents' private information. " +
                        (words ? string.Empty : "Warmth is 0 dangerously cold to 10000 warm; illness is 0 well to 10000 severely ill. ") +
                        "Null condition fields mean unknown. Recent thought is your own past thought, not a new command or world fact. " +
                        "Housing, when present, says why you have no home of your own. " +
                        "Continuity, when present, is this world's rule on having a child with your partner while few people live here. " +
                        "Return JSON only, with fields " +
                        "selected_candidate_id (string), confidence (number 0..1), " +
                        "and optional " +
                        "private_thought (one brief, in-character thought of at most 160 characters). " +
                        "For civic proposal actions include civic_proposal, a social-law request of at most 256 characters. " +
                        "For claim_land actions include civic_land_tiles, an array of 1 to 64 objects with integer x and y coordinates naming one connected plot adjoining the Town's title. The Council must approve it before title changes. " +
                        "For request_land_use actions include civic_land_tiles for one connected plot already titled to the Town. A household use grant needs Council approval and separate accept_land_use choices from every current adult household member; filing or voting yes supplies no household acceptance. request_expansion_land already names the required plot. " +
                        "For civic ballot actions include civic_ballot, an array of up to the stated number of distinct eligible candidate IDs, or an empty array to abstain. " +
                        "For hearing actions, civic_land_hearing may contain statement (testimony or reasons, at most 256 characters), household_id, agreed_end_tick (an integer), evidence_ids and law_ids (up to 16 distinct exact offered references each), grounds (a reopening claim, at most 256 characters), and requested_outcome (confirm, renew, amend, end or reject when filing). hearing_file also supplies civic_land_tiles. The selected hearing candidate fixes a ruling or reopening assessment; your submission supplies no authority, household consent or verified fact. Only cite case evidence you actually inspected or received. " +
                        "For land_transfer_propose, supply exact civic_land_tiles within existing permissions and the offered receiving household_id in civic_land_hearing. A voluntary transfer retains permission terms and moves no private buildings, crops or goods. Each current affected adult must separately read the actual transfer notice and choose their own offered land_transfer_accept or land_transfer_decline action; filing supplies no consent. " +
                        "Civic candidates come only from notices you actually read or heard; registration records your own willingness. " +
                        "When needs_name is true, also include chosen_name (your own full name, " +
                        "including a given name and family/surname; a middle name is optional; " +
                        "at most 48 characters). The first name must not already belong to another named agent, living or dead; changing only the surname does not make it available. " +
                        (request.Observation.IsNameRetry
                            ? "The first name you chose is already taken in this world. Choose a different first name. Do not list or ask for anyone else’s name. "
                            : string.Empty) +
                        (request.Observation.NeedsName && request.Observation.Self?.AllowedChildSurnames is { } childSurnames
                            ? childSurnames.Count > 0
                                ? "For this child's name, use one of the biological parents' surnames in self.allowed_child_surnames as the final name; do not invent another surname. "
                                : "Neither biological parent currently has a chosen surname available. Omit chosen_name and keep the temporary label; do not invent a surname. "
                            : string.Empty) +
                        "When needs_personality or needs_aspiration is true, you may also include " +
                        "chosen_personality and chosen_aspiration respectively, in your own words, " +
                        "each at most 256 characters with no control characters. This is a one-time choice. " +
                        (request.Observation.NeedsName
                            ? $"When naming this agent, prefer a given name starting with {NameInitial(request.Observation.InhabitantId)}; use a natural full name. "
                            : string.Empty) +
                        "Retrieved memories belong only to this actor. They are remembered experiences or private beliefs, " +
                        "not authoritative current facts; preserve any provenance and confidence exactly as labels, and do not " +
                        "assume another actor knows this information. Confidence values are basis points out of 10000; " +
                        "a corrected belief is superseded history, not the current account. A referenced world event does not itself prove a belief. " +
                        "Known map facts, when present, are bounded terrain/resource notes this actor has learned; " +
                        "other agents may know different places and these notes are not a complete world map. " +
                        (request.Observation.ObserverGuidance is { Count: > 0 }
                            ? "Messages in observer_guidance come from the outside observer, not from your own thoughts or another agent's speech. Their wording is quoted exactly. Suggestions are advice you may accept, adapt or reject. A must_do message with an understood_task is a recognized order: it has priority over your preferences, so do not refuse it; choose its matching legal candidate when available. The game still decides whether the action is physically possible and actually succeeds. Claims about places or resources are unverified until you discover them through your own actions; this message does not add map knowledge. You may include observer_replies as a short spoken reply to exact instruction_id values with reply_allowed=true. Each reply must be at most 160 characters. This reply is not a private thought or a conversation turn. Do not reply to an ID absent from observer_guidance. "
                            : string.Empty) +
                        "This is dialogue-like fiction, not an explanation of your reasoning. Do not include reasoning.",
                },
                new
                {
                    role = "user",
                    content = SerializeInput(new
                    {
                        agent_id = request.Observation.InhabitantId,
                        world_id = request.Observation.WorldId,
                        hunger_basis_points = request.Observation.HungerBasisPoints,
                        needs_name = request.Observation.NeedsName,
                        name_retry = request.Observation.IsNameRetry,
                        needs_personality = request.Observation.NeedsPersonality,
                        needs_aspiration = request.Observation.NeedsAspiration,
                        identity_moment = request.Observation.IdentityMoment,
                        self = request.Observation.Self is { } self ? new
                        {
                            name = self.Name, life_stage = self.LifeStage,
                            personality = self.Personality, aspiration = self.Aspiration,
                            household = self.HouseholdName,
                            town = self.TownName,
                            town_membership = self.TownMembershipNote,
                            housing = self.HousingNote,
                            equipment = self.EquipmentNote,
                            continuity = self.ContinuityNote,
                            departure = self.DepartureNote,
                            civic_notices_learned = self.CivicNote,
                            medical_care = self.MedicalCareNote,
                            tool_making_request = self.ToolMakingRequestNote,
                            allowed_child_surnames = request.Observation.NeedsName ? self.AllowedChildSurnames : null,
                            warmth_basis_points = self.WarmthBasisPoints,
                            illness_basis_points = self.IllnessBasisPoints,
                            recent_thought = self.RecentThought,
                        } : null,
                        candidates = request.Observation.Candidates.Select(candidate => new
                        {
                            id = candidate.Id,
                            description = candidate.Description,
                            destination = candidate.DestinationName,
                        }).ToArray(),
                        retrieved_memories = request.Observation.RetrievedMemories?.Select(memory => new
                        {
                            kind = memory.Kind,
                            subject_id = memory.SubjectId,
                            summary = memory.Summary,
                            source_tick = memory.SourceTick,
                            visibility = memory.Visibility,
                            provenance = memory.Provenance,
                            confidence_basis_points = memory.ConfidenceBasisPoints,
                            source_agent_id = memory.SourceAgentId,
                            source_event_id = memory.SourceEventId,
                            is_corrected = memory.IsCorrected,
                        }).ToArray(),
                        known_map_facts = request.Observation.KnownMapFacts?.Select(fact => new
                        {
                            x = fact.X,
                            y = fact.Y,
                            terrain = fact.Terrain,
                            resources = fact.ResourceKinds,
                            discoverer_id = fact.DiscovererId,
                            learned_tick = fact.LearnedTick,
                            acquisition = fact.Acquisition,
                        }).ToArray(),
                        observer_guidance = request.Observation.ObserverGuidance?.Select(message => new
                        {
                            instruction_id = message.InstructionId,
                            source = "outside_observer",
                            kind = message.Kind,
                            text = message.Text,
                            understood_task = message.UnderstoodTask,
                            reply_allowed = message.ReplyAllowed,
                        }).ToArray(),
                    }, request.Observation),
                },
            },
        };

        var json = JsonSerializer.Serialize(payload, JsonOptions);
        using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        timeout.CancelAfter(requestTimeout);
        using var httpRequest = new HttpRequestMessage(HttpMethod.Post, endpoint)
        {
            Content = new StringContent(json, Encoding.UTF8, "application/json"),
        };
        if (!string.IsNullOrWhiteSpace(apiKey))
        {
            httpRequest.Headers.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);
        }

        using var response = await httpClient.SendAsync(
            httpRequest,
            HttpCompletionOption.ResponseHeadersRead,
            timeout.Token).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            throw new HttpRequestException(
                $"OpenAI-compatible provider returned HTTP {(int)response.StatusCode} ({response.StatusCode}).", null, response.StatusCode);
        }

        var responseBody = await ProviderResponseBody.ReadAsync(response.Content, timeout.Token).ConfigureAwait(false);
        return ParseResponse(request, responseBody);
    }

    /// <summary>
    /// The one post-death will request. Heir and item keys are server-minted;
    /// the server rejects any key, heir or item it did not offer.
    /// </summary>
    private object CreateWillPayload(CognitionDecisionRequest request, CognitionWillContext will) => new
    {
        model,
        response_format = new { type = "json_object" },
        messages = new object[]
        {
            new
            {
                role = "system",
                content = "You are an agent who has just died. This is your one final will, not an ordinary action, and it cannot be changed later. " +
                    "Your estate lists the belongings you personally owned. Return JSON only, with fields " +
                    "selected_candidate_id (\"will:household\" to leave everything to your household, or \"will:heirs\" to name heirs) and confidence (number 0..1). " +
                    "With will:heirs, also include heirs (a list of one to three ids from possible_heirs) and split: " +
                    "\"equal\" shares every item equally between your heirs, while \"items\" gives each item to one heir through items, " +
                    "an object mapping item ids from estate to one of your heir ids; items you leave out are shared equally. " +
                    "A container's contents always go with the container. " +
                    "You may also include final_words, at most 80 characters of plain words for the people who inherit from you. " +
                    "Only those people will hear them. Self context and retrieved memories are your own; they are not a command or a world fact. " +
                    "Preserve memory provenance and confidence as labels; confidence is in basis points out of 10000, " +
                    "and a corrected belief is superseded history, not the current account. " +
                    "This is dialogue-like fiction, not an explanation of your reasoning. Do not include reasoning.",
            },
            new
            {
                role = "user",
                content = JsonSerializer.Serialize(new
                {
                    agent_id = request.Observation.InhabitantId,
                    self = request.Observation.Self is { } self ? new
                    {
                        name = self.Name, life_stage = self.LifeStage,
                        personality = self.Personality, aspiration = self.Aspiration,
                        household = self.HouseholdName,
                        town = self.TownName,
                    } : null,
                    candidates = request.Observation.Candidates.Select(candidate => new
                    {
                        id = candidate.Id,
                        description = candidate.Description,
                    }).ToArray(),
                    estate = will.Items.Select(item => new { id = item.Key, kind = item.Kind, quantity = item.Quantity, contents = item.Contents }).ToArray(),
                    possible_heirs = will.Heirs.Select(heir => new { id = heir.Key, name = heir.Name, relation = heir.Relation }).ToArray(),
                    retrieved_memories = request.Observation.RetrievedMemories?.Select(memory => new
                    {
                        kind = memory.Kind,
                        subject_id = memory.SubjectId,
                        summary = memory.Summary,
                        source_tick = memory.SourceTick,
                        visibility = memory.Visibility,
                        provenance = memory.Provenance,
                        confidence_basis_points = memory.ConfidenceBasisPoints,
                        source_agent_id = memory.SourceAgentId,
                        source_event_id = memory.SourceEventId,
                        is_corrected = memory.IsCorrected,
                    }).ToArray(),
                }, JsonOptions),
            },
        },
    };

    /// <summary>
    /// Reads the optional will fields. Malformed fields make the reply invalid,
    /// so the server keeps the household default; unusable final words are dropped.
    /// </summary>
    private static CognitionWillChoice? ParseWillChoice(JsonElement answer, string? selected)
    {
        var finalWords = answer.TryGetProperty("final_words", out var wordsProperty) &&
            wordsProperty.ValueKind == JsonValueKind.String
                ? CognitionWillChoice.NormalizeFinalWords(wordsProperty.GetString()) : null;
        if (selected != CognitionWillContext.HeirsCandidateId)
            return new CognitionWillChoice([], FinalWords: finalWords);
        if (!answer.TryGetProperty("heirs", out var heirsProperty) || heirsProperty.ValueKind != JsonValueKind.Array ||
            heirsProperty.GetArrayLength() > CognitionWillContext.MaximumHeirChoices)
            throw new InvalidDataException("The will reply did not list its heirs.");
        var heirs = heirsProperty.EnumerateArray().Select(item => item.ValueKind == JsonValueKind.String
            ? item.GetString()!.Trim() : throw new InvalidDataException("A will heir is not an ID.")).ToArray();
        var split = answer.TryGetProperty("split", out var splitProperty) && splitProperty.ValueKind == JsonValueKind.String
            ? splitProperty.GetString()!.Trim() : CognitionWillContext.EqualSplit;
        Dictionary<string, string>? items = null;
        if (split == CognitionWillContext.ItemSplit && answer.TryGetProperty("items", out var itemsProperty))
        {
            if (itemsProperty.ValueKind != JsonValueKind.Object)
                throw new InvalidDataException("The will items are not an object.");
            items = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var property in itemsProperty.EnumerateObject())
            {
                if (property.Value.ValueKind != JsonValueKind.String || items.Count >= CognitionWillContext.MaximumItems ||
                    !items.TryAdd(property.Name.Trim(), property.Value.GetString()!.Trim()))
                    throw new InvalidDataException("The will items are malformed.");
            }
        }
        return new CognitionWillChoice(heirs, split, items, finalWords);
    }

    private static CognitionDecisionResponse ParseResponse(
        CognitionDecisionRequest request,
        string responseBody)
    {
        try
        {
            using var document = JsonDocument.Parse(responseBody);
            var root = document.RootElement;
            var modelId = root.TryGetProperty("model", out var modelProperty)
                ? modelProperty.GetString()
                : null;
            var content = root.GetProperty("choices")[0]
                .GetProperty("message")
                .GetProperty("content")
                .GetString();
            using var answer = JsonDocument.Parse(NormalizeJsonContent(content));
            var answerRoot = answer.RootElement;
            var selected = answerRoot.GetProperty("selected_candidate_id").GetString();
            var confidence = answerRoot.GetProperty("confidence").GetDouble();
            var probabilities = answerRoot.TryGetProperty("probabilities", out var probabilitiesProperty)
                ? probabilitiesProperty.EnumerateObject().ToDictionary(
                    property => property.Name,
                    property => property.Value.GetDouble(),
                    StringComparer.Ordinal)
                : request.Observation.Candidates.ToDictionary(
                    candidate => candidate.Id,
                    candidate => string.Equals(candidate.Id, selected, StringComparison.Ordinal) ? 1d : 0d,
                    StringComparer.Ordinal);
            var privateThought = answerRoot.TryGetProperty("private_thought", out var thoughtProperty) &&
                thoughtProperty.ValueKind == JsonValueKind.String
                    ? CognitionDecisionResponse.NormalizePrivateThought(thoughtProperty.GetString())
                    : null;
            var chosenName = answerRoot.TryGetProperty("chosen_name", out var nameProperty) &&
                nameProperty.ValueKind == JsonValueKind.String
                    ? CognitionDecisionResponse.NormalizeChosenName(nameProperty.GetString())
                    : null;
            if (request.Observation.IdentityMoment is not null)
            {
                foreach (var field in new[] { "chosen_personality", "chosen_aspiration" })
                    if (answerRoot.TryGetProperty(field, out var value) && value.ValueKind != JsonValueKind.Null &&
                        (value.ValueKind != JsonValueKind.String ||
                            CognitionDecisionResponse.NormalizeIdentityText(value.GetString()) is null))
                        throw new InvalidDataException("The optional life-moment identity reply is invalid.");
            }
            var chosenPersonality = answerRoot.TryGetProperty("chosen_personality", out var personalityProperty) &&
                personalityProperty.ValueKind == JsonValueKind.String
                    ? CognitionDecisionResponse.NormalizeIdentityText(personalityProperty.GetString()) : null;
            var chosenAspiration = answerRoot.TryGetProperty("chosen_aspiration", out var aspirationProperty) &&
                aspirationProperty.ValueKind == JsonValueKind.String
                    ? CognitionDecisionResponse.NormalizeIdentityText(aspirationProperty.GetString()) : null;
            IReadOnlyList<CognitionObserverReply>? observerReplies = null;
            if (answerRoot.TryGetProperty("observer_replies", out var observerRepliesProperty))
            {
                if (observerRepliesProperty.ValueKind != JsonValueKind.Array ||
                    observerRepliesProperty.GetArrayLength() > InhabitantObservation.MaximumObserverGuidanceCount)
                    throw new InvalidDataException("The OpenAI-compatible provider returned invalid observer replies.");
                observerReplies = observerRepliesProperty.EnumerateArray().Select(reply =>
                {
                    if (reply.ValueKind != JsonValueKind.Object ||
                        !reply.TryGetProperty("instruction_id", out var instructionIdProperty) ||
                        instructionIdProperty.ValueKind != JsonValueKind.String ||
                        !reply.TryGetProperty("text", out var textProperty) ||
                        textProperty.ValueKind != JsonValueKind.String)
                        throw new InvalidDataException("The OpenAI-compatible provider returned an incomplete observer reply.");
                    var instructionId = instructionIdProperty.GetString();
                    var text = CognitionDecisionResponse.NormalizeObserverReply(textProperty.GetString());
                    if (string.IsNullOrWhiteSpace(instructionId) || text is null)
                        throw new InvalidDataException("The OpenAI-compatible provider returned an invalid observer reply.");
                    return new CognitionObserverReply(instructionId, text);
                }).ToArray();
            }

            var will = request.Observation.Will is null ? null : ParseWillChoice(answerRoot, selected?.Trim());
            var civicProposal = answerRoot.TryGetProperty("civic_proposal", out var civicText) && civicText.ValueKind == JsonValueKind.String
                ? CognitionDecisionResponse.NormalizeIdentityText(civicText.GetString()) : null;
            var civicBallot = ParseCivicBallot(answerRoot);
            var usage = TryParseUsage(root, modelId);
            return new CognitionDecisionResponse(
                request.RequestId,
                request.Observation.InhabitantId,
                DecisionProviderKind.LargeLanguageModel,
                request.ProviderEpoch,
                request.Observation.RunEpoch,
                request.Observation.DecisionGeneration,
                request.Observation.ObservationDigest,
                NormalizeRequiredText(selected ?? string.Empty, "selected_candidate_id"),
                confidence,
                probabilities,
                usage,
                privateThought,
                chosenName,
                ChosenPersonality: chosenPersonality, ChosenAspiration: chosenAspiration, CivicProposal: civicProposal, CivicBallot: civicBallot,
                ObserverReplies: observerReplies, Will: will, CivicLandTiles: ParseCivicLandTiles(answerRoot),
                CivicLandHearing: CognitionLandHearingChoice.Parse(answerRoot));
        }
        catch (JsonException exception)
        {
            throw new InvalidDataException("The OpenAI-compatible provider returned malformed JSON.", exception);
        }
        catch (KeyNotFoundException exception)
        {
            throw new InvalidDataException("The OpenAI-compatible provider returned an incomplete choice response.", exception);
        }
        catch (IndexOutOfRangeException exception)
        {
            throw new InvalidDataException("The OpenAI-compatible provider returned no choices.", exception);
        }
    }

    private static CognitionLandTile[]? ParseCivicLandTiles(JsonElement root)
    {
        // An empty plot, like an empty ballot, is no request; the chosen action decides what is used.
        if (!root.TryGetProperty("civic_land_tiles", out var tiles) || tiles.ValueKind == JsonValueKind.Null ||
            tiles.ValueKind == JsonValueKind.Array && tiles.GetArrayLength() == 0) return null;
        if (tiles.ValueKind != JsonValueKind.Array || tiles.GetArrayLength() is < 1 or > CognitionDecisionResponse.MaximumCivicLandTiles)
            throw new InvalidDataException("The provider returned an invalid land plot.");
        return tiles.EnumerateArray().Select(tile =>
        {
            if (tile.ValueKind != JsonValueKind.Object || !tile.TryGetProperty("x", out var x) ||
                !tile.TryGetProperty("y", out var y) || x.ValueKind != JsonValueKind.Number || y.ValueKind != JsonValueKind.Number ||
                !x.TryGetInt32(out var column) || !y.TryGetInt32(out var row))
                throw new InvalidDataException("The provider returned an invalid land coordinate.");
            return new CognitionLandTile(column, row);
        }).ToArray();
    }

    private static string[]? ParseCivicBallot(JsonElement root)
    {
        if (!root.TryGetProperty("civic_ballot", out var ballot) || ballot.ValueKind == JsonValueKind.Null) return null;
        if (ballot.ValueKind != JsonValueKind.Array || ballot.GetArrayLength() > 3 ||
            ballot.EnumerateArray().Any(choice => choice.ValueKind != JsonValueKind.String))
            throw new InvalidDataException("The provider returned an invalid civic ballot.");
        return ballot.EnumerateArray().Select(choice => choice.GetString()!).ToArray();
    }

    private string SerializeInput(object input, InhabitantObservation observation)
    {
        if (needFormat != ModelNeedFormat.Words) return JsonSerializer.Serialize(input, JsonOptions);
        var described = JsonSerializer.SerializeToNode(input, JsonOptions)!.AsObject();
        ModelNeedWords.ReplaceNumber(described, "hunger_basis_points", "fullness",
            ModelNeedWords.Fullness(observation.HungerBasisPoints));
        if (described["self"] is JsonObject self && observation.Self is { } condition)
        {
            ModelNeedWords.ReplaceNumber(self, "warmth_basis_points", "warmth",
                condition.WarmthBasisPoints is { } warmth ? ModelNeedWords.Warmth(warmth) : null);
            ModelNeedWords.ReplaceNumber(self, "illness_basis_points", "illness",
                condition.IllnessBasisPoints is { } illness ? ModelNeedWords.Illness(illness) : null);
        }
        return described.ToJsonString(JsonOptions);
    }

    private static char NameInitial(string agentId) =>
        CommonNameInitials[SHA256.HashData(Encoding.UTF8.GetBytes(agentId))[0] % CommonNameInitials.Length];

    private static CognitionUsage? TryParseUsage(JsonElement root, string? modelId)
    {
        if (!root.TryGetProperty("usage", out var usage))
        {
            return modelId is null ? null : new CognitionUsage(modelId, 0, 0);
        }

        var inputTokens = TryGetInt(usage, "prompt_tokens") ?? TryGetInt(usage, "input_tokens") ?? 0;
        var outputTokens = TryGetInt(usage, "completion_tokens") ?? TryGetInt(usage, "output_tokens") ?? 0;
        return new CognitionUsage(modelId, inputTokens, outputTokens);
    }

    private static int? TryGetInt(JsonElement element, string propertyName) =>
        element.TryGetProperty(propertyName, out var property) && property.TryGetInt32(out var value)
            ? value
            : null;

    private static string NormalizeJsonContent(string? content)
    {
        var normalized = NormalizeRequiredText(content ?? string.Empty, "message.content").Trim();
        if (normalized.StartsWith("```", StringComparison.Ordinal))
        {
            var firstLineEnd = normalized.IndexOf('\n');
            var lastFence = normalized.LastIndexOf("```", StringComparison.Ordinal);
            if (firstLineEnd > 0 && lastFence > firstLineEnd)
            {
                normalized = normalized[(firstLineEnd + 1)..lastFence].Trim();
            }
        }

        return normalized;
    }

    private static bool IsAllowedLocalHttpEndpoint(Uri value) =>
        value.Scheme == Uri.UriSchemeHttp &&
        (string.Equals(value.Host, "localhost", StringComparison.OrdinalIgnoreCase) ||
         IPAddress.TryParse(value.Host, out var address) && IPAddress.IsLoopback(address));

    private static string NormalizeRequiredText(string? value, string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value, name);
        return value.Trim();
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };
}
