using System.Net;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ClankerWorld.Simulation.Cognition;

/// <summary>
/// Providers are interchangeable decision sources. They never own simulation
/// authority: the cognition runtime admits their structured result and the
/// world kernel still validates and executes the selected intention.
/// </summary>
public enum DecisionProviderKind
{
    Deterministic,
    Jev,
    LargeLanguageModel,
}

/// <summary>
/// A legal intention generated by authoritative simulation code. The provider
/// may choose among these candidates, but may not invent a new action ID.
/// Candidates should be ordered with the safest local fallback first.
/// </summary>
public sealed record CognitionCandidate(
    string Id,
    string Description,
    int DeterministicPriority = 0,
    string? DestinationId = null)
{
    public void Validate()
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(Id);
        ArgumentException.ThrowIfNullOrWhiteSpace(Description);
        if (DeterministicPriority < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(DeterministicPriority));
        }
    }
}

/// <summary>A bounded excerpt of an existing, actor-owned memory or belief.</summary>
public sealed record CognitionMemoryExcerpt(
    string Id,
    string OwnerId,
    string SubjectId,
    string Summary,
    long SourceTick,
    string Kind = "experience",
    string? Visibility = null,
    string? Provenance = null,
    int? ConfidenceBasisPoints = null,
    string? SourceAgentId = null,
    long? SourceEventId = null,
    bool IsCorrected = false,
    int ImportanceBasisPoints = 0,
    int ImportanceConfidenceBasisPoints = 0);

/// <summary>
/// A source record Jev may rate while it is already choosing a routine action.
/// IDs stay local to the host; the provider sees only a per-request index.
/// </summary>
public sealed record CognitionMemoryCompactionCandidate(
    string Id,
    string OwnerId,
    string Kind,
    string SubjectId,
    string Summary,
    long SourceTick,
    string? Visibility = null,
    string? Provenance = null,
    int? ConfidenceBasisPoints = null,
    string? SourceAgentId = null,
    long? SourceEventId = null,
    bool IsCorrected = false);

/// <summary>A Jev salience assessment of one source record, not a world fact.</summary>
public sealed record CognitionMemoryCompactionScore(
    string Id,
    string OwnerId,
    string Kind,
    long SourceTick,
    int ImportanceBasisPoints,
    int ConfidenceBasisPoints);

/// <summary>A compact fact from the observing agent's own map or field records.</summary>
public sealed record CognitionKnowledgeFact(
    int X,
    int Y,
    string Terrain,
    IReadOnlyList<string> ResourceKinds,
    string DiscovererId,
    long LearnedTick,
    string Acquisition);

/// <summary>Actor-owned context only; absent survival data remains unknown, not invented.</summary>
public sealed record CognitionSelfContext(
    string OwnerId, string Name, string LifeStage, string Personality, string Aspiration,
    string? HouseholdId, int? WarmthBasisPoints, int? IllnessBasisPoints, string? RecentThought);

/// <summary>
/// Compact, provider-neutral state supplied to a decision provider. It is an
/// observation, not a mutable world object or an omniscient world dump.
/// </summary>
public sealed record InhabitantObservation(
    string InhabitantId,
    long WorldTick,
    long RunEpoch,
    long DecisionGeneration,
    string ObservationDigest,
    int HungerBasisPoints,
    IReadOnlyList<CognitionCandidate> Candidates,
    bool NeedsName = false,
    bool RequiresPersonalProvider = false,
    IReadOnlyList<CognitionMemoryExcerpt>? RetrievedMemories = null,
    IReadOnlyList<CognitionMemoryCompactionCandidate>? MemoryCompactionCandidates = null,
    IReadOnlyList<CognitionKnowledgeFact>? KnownMapFacts = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] CognitionSelfContext? Self = null)
{
    public void Validate()
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(InhabitantId);
        ArgumentException.ThrowIfNullOrWhiteSpace(ObservationDigest);
        if (WorldTick < 0 || RunEpoch < 0 || DecisionGeneration < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(WorldTick));
        }

        if (HungerBasisPoints is < 0 or > 10_000)
        {
            throw new ArgumentOutOfRangeException(nameof(HungerBasisPoints));
        }

        if (Self is { } self && (self.OwnerId != InhabitantId ||
            string.IsNullOrWhiteSpace(self.Name) || self.Name.Length > 128 ||
            string.IsNullOrWhiteSpace(self.LifeStage) || self.LifeStage.Length > 32 ||
            self.Personality is null || self.Personality.Length > 256 ||
            self.Aspiration is null || self.Aspiration.Length > 256 ||
            self.HouseholdId?.Length > 128 || self.RecentThought?.Length > 160 ||
            self.WarmthBasisPoints is < 0 or > 10_000 || self.IllnessBasisPoints is < 0 or > 10_000))
            throw new ArgumentException("Self context must be bounded and owned by the actor.", nameof(Self));

        if (Candidates is null || Candidates.Count == 0)
        {
            throw new ArgumentException("A cognition observation must contain at least one legal candidate.", nameof(Candidates));
        }

        var ids = new HashSet<string>(StringComparer.Ordinal);
        foreach (var candidate in Candidates)
        {
            ArgumentNullException.ThrowIfNull(candidate);
            candidate.Validate();
            if (!ids.Add(candidate.Id))
            {
                throw new ArgumentException("Cognition candidate IDs must be unique.", nameof(Candidates));
            }
        }

        if (RetrievedMemories is { Count: > 4 })
            throw new ArgumentException("Memory context exceeds the four-record budget.", nameof(RetrievedMemories));
        foreach (var memory in RetrievedMemories ?? [])
        {
            ArgumentNullException.ThrowIfNull(memory);
            if (!string.Equals(memory.OwnerId, InhabitantId, StringComparison.Ordinal) ||
                string.IsNullOrWhiteSpace(memory.Id) || string.IsNullOrWhiteSpace(memory.SubjectId) ||
                memory.Id.Length > 128 || memory.SubjectId.Length > 128 ||
                string.IsNullOrWhiteSpace(memory.Summary) || memory.Summary.Length > 160 ||
                memory.SourceTick < 0 || memory.SourceTick > WorldTick ||
                !IsMemoryKind(memory.Kind) || !IsOptionalBounded(memory.Visibility, 32) ||
                memory.Provenance is not (null or "firsthand" or "hearsay" or "inference") ||
                memory.ConfidenceBasisPoints is < 0 or > 10_000 ||
                !IsOptionalBounded(memory.SourceAgentId, 128) || memory.SourceEventId is <= 0 ||
                memory.ImportanceBasisPoints is < 0 or > 10_000 ||
                memory.ImportanceConfidenceBasisPoints is < 0 or > 10_000)
                throw new ArgumentException("Memory context must be bounded and owned by the actor.", nameof(RetrievedMemories));
        }

        if (MemoryCompactionCandidates is { Count: > 12 })
            throw new ArgumentException("Memory compaction context exceeds the twelve-record budget.", nameof(MemoryCompactionCandidates));
        var compactionIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var candidate in MemoryCompactionCandidates ?? [])
        {
            ArgumentNullException.ThrowIfNull(candidate);
            if (!string.Equals(candidate.OwnerId, InhabitantId, StringComparison.Ordinal) ||
                string.IsNullOrWhiteSpace(candidate.Id) || candidate.Id.Length > 128 ||
                !compactionIds.Add($"{candidate.Kind}:{candidate.Id}") ||
                !IsMemoryKind(candidate.Kind) || string.IsNullOrWhiteSpace(candidate.SubjectId) ||
                candidate.SubjectId.Length > 128 || string.IsNullOrWhiteSpace(candidate.Summary) ||
                candidate.Summary.Length > 160 || candidate.SourceTick < 0 || candidate.SourceTick > WorldTick ||
                !IsOptionalBounded(candidate.Visibility, 32) ||
                candidate.Provenance is not (null or "firsthand" or "hearsay" or "inference") ||
                candidate.ConfidenceBasisPoints is < 0 or > 10_000 ||
                !IsOptionalBounded(candidate.SourceAgentId, 128) || candidate.SourceEventId is <= 0)
                throw new ArgumentException("Memory compaction context must be bounded and owned by the actor.", nameof(MemoryCompactionCandidates));
        }

        if (KnownMapFacts is { Count: > 16 })
            throw new ArgumentException("Map-knowledge context exceeds the sixteen-fact budget.", nameof(KnownMapFacts));
        foreach (var fact in KnownMapFacts ?? [])
        {
            ArgumentNullException.ThrowIfNull(fact);
            if (fact.X < 0 || fact.Y < 0 || string.IsNullOrWhiteSpace(fact.Terrain) || fact.Terrain.Length > 32 ||
                fact.ResourceKinds is null || fact.ResourceKinds.Count > 4 ||
                fact.ResourceKinds.Any(kind => string.IsNullOrWhiteSpace(kind) || kind.Length > 48) ||
                string.IsNullOrWhiteSpace(fact.DiscovererId) || fact.DiscovererId.Length > 128 ||
                fact.LearnedTick < 0 || fact.LearnedTick > WorldTick ||
                fact.Acquisition is not ("firsthand" or "shared" or "read"))
                throw new ArgumentException("Map-knowledge context must be bounded and privately owned by the actor.", nameof(KnownMapFacts));
        }
    }

    private static bool IsMemoryKind(string kind) => kind is "experience" or "belief";

    private static bool IsOptionalBounded(string? value, int maximumLength) =>
        value is null || value.Length <= maximumLength && !value.Any(char.IsControl);
}

/// <summary>
/// A provider request has a server-minted request ID and captures every epoch
/// needed to reject a response that belongs to an older world boundary.
/// </summary>
public sealed record CognitionDecisionRequest(
    string RequestId,
    long ProviderEpoch,
    InhabitantObservation Observation)
{
    public void Validate()
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(RequestId);
        if (ProviderEpoch < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(ProviderEpoch));
        }

        ArgumentNullException.ThrowIfNull(Observation);
        Observation.Validate();
    }
}

/// <summary>
/// A typed provider response. Probabilities are telemetry and admission
/// evidence; the selected ID is still checked against the request's legal
/// candidate set before it can become an intention.
/// </summary>
public sealed record CognitionDecisionResponse(
    string RequestId,
    string InhabitantId,
    DecisionProviderKind Provider,
    long ProviderEpoch,
    long RunEpoch,
    long DecisionGeneration,
    string ObservationDigest,
    string SelectedCandidateId,
    double Confidence,
    IReadOnlyDictionary<string, double> Probabilities,
    CognitionUsage? Usage = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? PrivateThought = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? ChosenName = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] IReadOnlyList<CognitionMemoryCompactionScore>? MemoryCompactionScores = null)
{
    public const int MaximumPrivateThoughtLength = 160;
    public const int MaximumChosenNameLength = 48;

    public static string? NormalizePrivateThought(string? value)
    {
        var text = value?.Trim();
        return text is { Length: > 0 and <= MaximumPrivateThoughtLength } &&
            !text.Any(char.IsControl) ? text : null;
    }

    public static string? NormalizeChosenName(string? value)
    {
        var text = value?.Trim();
        return text is { Length: > 0 and <= MaximumChosenNameLength } &&
            !text.Any(char.IsControl) ? text : null;
    }

    public void Validate()
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(RequestId);
        ArgumentException.ThrowIfNullOrWhiteSpace(InhabitantId);
        ArgumentException.ThrowIfNullOrWhiteSpace(ObservationDigest);
        ArgumentException.ThrowIfNullOrWhiteSpace(SelectedCandidateId);
        if (ProviderEpoch < 0 || RunEpoch < 0 || DecisionGeneration < 0 ||
            double.IsNaN(Confidence) || double.IsInfinity(Confidence) || Confidence is < 0 or > 1)
        {
            throw new ArgumentOutOfRangeException(nameof(Confidence));
        }

        if (Probabilities is null)
        {
            throw new ArgumentNullException(nameof(Probabilities));
        }

        foreach (var probability in Probabilities)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(probability.Key);
            if (double.IsNaN(probability.Value) || double.IsInfinity(probability.Value) || probability.Value is < 0 or > 1)
            {
                throw new ArgumentOutOfRangeException(nameof(Probabilities));
            }
        }

        if (PrivateThought is not null && NormalizePrivateThought(PrivateThought) != PrivateThought)
        {
            throw new ArgumentOutOfRangeException(nameof(PrivateThought));
        }

        if (ChosenName is not null && NormalizeChosenName(ChosenName) != ChosenName)
            throw new ArgumentOutOfRangeException(nameof(ChosenName));

        if (MemoryCompactionScores is { Count: > 12 })
            throw new ArgumentOutOfRangeException(nameof(MemoryCompactionScores));
        var compactionIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var score in MemoryCompactionScores ?? [])
        {
            ArgumentNullException.ThrowIfNull(score);
            if (string.IsNullOrWhiteSpace(score.Id) || score.Id.Length > 128 ||
                string.IsNullOrWhiteSpace(score.OwnerId) || score.OwnerId.Length > 128 ||
                score.Kind is not ("experience" or "belief") || score.SourceTick < 0 ||
                score.ImportanceBasisPoints is < 0 or > 10_000 ||
                score.ConfidenceBasisPoints is < 0 or > 10_000 ||
                !compactionIds.Add($"{score.Kind}:{score.Id}"))
                throw new ArgumentOutOfRangeException(nameof(MemoryCompactionScores));
        }

        Usage?.Validate();
    }
}

/// <summary>
/// Provider usage is telemetry only. It is retained with a request record so
/// an owner can see that a hosted decision happened without storing secrets or
/// raw provider reasoning in world state.
/// </summary>
public sealed record CognitionUsage(
    string? ModelId,
    int InputTokens,
    int OutputTokens,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] long? LatencyMilliseconds = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? ProviderId = null,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? Role = null)
{
    public void Validate()
    {
        if (InputTokens < 0 || OutputTokens < 0 || LatencyMilliseconds < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(InputTokens));
        }

        if (ModelId is not null && string.IsNullOrWhiteSpace(ModelId))
        {
            throw new ArgumentException("A provider model ID cannot be blank when supplied.", nameof(ModelId));
        }
    }
}

/// <summary>
/// Provider implementations are intentionally small. A hosted provider can
/// be plugged in later without changing the simulation or persistence model.
/// </summary>
public interface IDecisionProvider
{
    DecisionProviderKind Kind { get; }

    long ProviderEpoch { get; }

    DecisionProviderKind KindFor(InhabitantObservation observation) => Kind;

    ValueTask<CognitionDecisionResponse> DecideAsync(
        CognitionDecisionRequest request,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// The always-available local provider. The authoritative candidate generator
/// orders candidates by deterministic priority, so this provider is a stable
/// fallback rather than a fake attempt at open-ended cognition.
/// </summary>
public sealed class DeterministicDecisionProvider : IDecisionProvider
{
    public DecisionProviderKind Kind => DecisionProviderKind.Deterministic;

    public long ProviderEpoch => 0;

    public ValueTask<CognitionDecisionResponse> DecideAsync(
        CognitionDecisionRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        request.Validate();
        cancellationToken.ThrowIfCancellationRequested();

        var selected = request.Observation.Candidates
            .OrderBy(candidate => candidate.DeterministicPriority)
            .ThenBy(candidate => candidate.Id, StringComparer.Ordinal)
            .First();
        var probabilities = request.Observation.Candidates
            .ToDictionary(
                candidate => candidate.Id,
                candidate => string.Equals(candidate.Id, selected.Id, StringComparison.Ordinal) ? 1d : 0d,
                StringComparer.Ordinal);

        return ValueTask.FromResult(new CognitionDecisionResponse(
            request.RequestId,
            request.Observation.InhabitantId,
            Kind,
            ProviderEpoch,
            request.Observation.RunEpoch,
            request.Observation.DecisionGeneration,
            request.Observation.ObservationDigest,
            selected.Id,
            1d,
            new ReadOnlyDictionary<string, double>(probabilities)));
    }
}

/// <summary>
/// Optional TypeSafe System One adapter. The API key is obtained at call time
/// and is never part of a request, save document, telemetry event, or options
/// record. If it is absent, the cognition runtime treats this as an ordinary
/// provider failure and uses its deterministic fallback.
/// </summary>
public sealed class JevDecisionProvider : IDecisionProvider
{
    private const string ChoiceQuestionId = "selected_candidate";
    private static readonly string[] MemoryImportanceCriteria =
    [
        "Minor, redundant, or unlikely to help the agent again.",
        "Possibly useful context for the agent's future choices.",
        "Important long-term context that should remain easy to retrieve.",
    ];
    private readonly HttpClient httpClient;
    private readonly Func<string?> apiKeyAccessor;
    private readonly Uri endpoint;
    private readonly string model;
    private readonly TimeSpan requestTimeout;

    public JevDecisionProvider(
        HttpClient httpClient,
        Func<string?> apiKeyAccessor,
        Uri? endpoint = null,
        string model = "jev-1.13.0",
        TimeSpan? requestTimeout = null,
        long providerEpoch = 1)
    {
        this.httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        this.apiKeyAccessor = apiKeyAccessor ?? throw new ArgumentNullException(nameof(apiKeyAccessor));
        this.endpoint = endpoint ?? new Uri("https://api.typesafe.ai/v1/systemone", UriKind.Absolute);
        if (!this.endpoint.IsAbsoluteUri || this.endpoint.Scheme != Uri.UriSchemeHttps)
        {
            throw new ArgumentException("The Jev endpoint must be an absolute HTTPS URI.", nameof(endpoint));
        }

        this.model = NormalizeRequiredText(model, nameof(model));
        this.requestTimeout = requestTimeout ?? TimeSpan.FromSeconds(30);
        if (this.requestTimeout <= TimeSpan.Zero || this.requestTimeout > TimeSpan.FromMinutes(5))
        {
            throw new ArgumentOutOfRangeException(nameof(requestTimeout));
        }

        ArgumentOutOfRangeException.ThrowIfNegative(providerEpoch);
        ProviderEpoch = providerEpoch;
    }

    public DecisionProviderKind Kind => DecisionProviderKind.Jev;

    public long ProviderEpoch { get; }

    public async ValueTask<CognitionDecisionResponse> DecideAsync(
        CognitionDecisionRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        request.Validate();
        cancellationToken.ThrowIfCancellationRequested();

        var apiKey = apiKeyAccessor()?.Trim();
        if (string.IsNullOrWhiteSpace(apiKey))
        {
            throw new InvalidOperationException("Jev is enabled but no TypeSafe API key is configured.");
        }

        var questions = new Dictionary<string, JevQuestion>(StringComparer.Ordinal)
        {
            [ChoiceQuestionId] = new JevQuestion(
                "choice",
                "Choose exactly one legal candidate for the agent's next small action. " +
                "hunger_basis_points says how well fed they are: 10000 is full and 0 is starving.",
                request.Observation.Candidates.ToDictionary(
                    candidate => candidate.Id,
                    candidate => candidate.Description,
                    StringComparer.Ordinal)),
        };
        for (var index = 0; index < (request.Observation.MemoryCompactionCandidates?.Count ?? 0); index++)
        {
            questions[MemoryQuestionId(index)] = new JevQuestion(
                "score",
                "Rate how useful this source record is for the agent's future decisions and identity. " +
                "Preserve it if it records a lasting relationship, learned skill, major personal event, " +
                "or unresolved commitment. A belief is an uncertain account, not a verified world fact; " +
                "consider its provenance and confidence without treating it as authoritative.",
                MemoryImportanceCriteria);
        }

        var payload = new JevRequest(
            new
            {
                agent_id = request.Observation.InhabitantId,
                world_tick = request.Observation.WorldTick,
                run_epoch = request.Observation.RunEpoch,
                decision_generation = request.Observation.DecisionGeneration,
                hunger_basis_points = request.Observation.HungerBasisPoints,
                candidates = request.Observation.Candidates.Select(candidate => new
                {
                    id = candidate.Id,
                    description = candidate.Description,
                    destination_id = candidate.DestinationId,
                }).ToArray(),
                memory_compaction_candidates = (request.Observation.MemoryCompactionCandidates ?? [])
                    .Select((candidate, index) => new
                    {
                        source_index = index,
                        kind = candidate.Kind,
                        subject_id = candidate.SubjectId,
                        summary = candidate.Summary,
                        source_tick = candidate.SourceTick,
                        visibility = candidate.Visibility,
                        provenance = candidate.Provenance,
                        confidence_basis_points = candidate.ConfidenceBasisPoints,
                        source_agent_id = candidate.SourceAgentId,
                        source_event_id = candidate.SourceEventId,
                        is_corrected = candidate.IsCorrected,
                    }).ToArray(),
            },
            model,
            questions);

        var json = JsonSerializer.Serialize(payload, JsonOptions);
        using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        timeout.CancelAfter(requestTimeout);
        using var httpRequest = new HttpRequestMessage(HttpMethod.Post, endpoint)
        {
            Content = new StringContent(json, Encoding.UTF8, "application/json"),
        };
        httpRequest.Headers.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);

        using var response = await httpClient.SendAsync(
            httpRequest,
            HttpCompletionOption.ResponseHeadersRead,
            timeout.Token).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            throw new HttpRequestException(
                $"Jev returned HTTP {(int)response.StatusCode} ({response.StatusCode}).");
        }

        var responseBody = await ProviderResponseBody.ReadAsync(response.Content, timeout.Token).ConfigureAwait(false);
        return ParseResponse(request, responseBody);
    }

    private static CognitionDecisionResponse ParseResponse(
        CognitionDecisionRequest request,
        string responseBody)
    {
        try
        {
            using var document = JsonDocument.Parse(responseBody);
            var root = document.RootElement;
            var modelId = root.TryGetProperty("model", out var modelProperty)
                ? modelProperty.GetString()
                : null;
            var answer = root.GetProperty("answers").GetProperty(ChoiceQuestionId);
            if (!string.Equals(answer.GetProperty("type").GetString(), "choice", StringComparison.Ordinal))
            {
                throw new InvalidDataException("Jev returned a non-choice answer for the candidate question.");
            }

            var selected = answer.GetProperty("choice").GetString();
            var confidence = answer.GetProperty("confidence").GetDouble();
            var probabilities = answer.GetProperty("probabilities")
                .EnumerateObject()
                .ToDictionary(
                    property => property.Name,
                    property => property.Value.GetDouble(),
                    StringComparer.Ordinal);
            var usage = root.TryGetProperty("usage", out var usageProperty)
                ? new CognitionUsage(
                    modelId,
                    usageProperty.GetProperty("input_tokens").GetInt32(),
                    usageProperty.GetProperty("output_tokens").GetInt32())
                : modelId is null ? null : new CognitionUsage(modelId, 0, 0);
            var memoryCompactionScores = ReadMemoryCompactionScores(
                root.GetProperty("answers"), request.Observation);

            return new CognitionDecisionResponse(
                request.RequestId,
                request.Observation.InhabitantId,
                DecisionProviderKind.Jev,
                request.ProviderEpoch,
                request.Observation.RunEpoch,
                request.Observation.DecisionGeneration,
                request.Observation.ObservationDigest,
                NormalizeRequiredText(selected ?? string.Empty, "choice"),
                confidence,
                probabilities,
                usage,
                MemoryCompactionScores: memoryCompactionScores);
        }
        catch (JsonException exception)
        {
            throw new InvalidDataException("Jev returned malformed JSON.", exception);
        }
        catch (KeyNotFoundException exception)
        {
            throw new InvalidDataException("Jev returned an incomplete choice response.", exception);
        }
    }

    private static List<CognitionMemoryCompactionScore>? ReadMemoryCompactionScores(
        JsonElement answers,
        InhabitantObservation observation)
    {
        var candidates = observation.MemoryCompactionCandidates;
        if (candidates is null || candidates.Count == 0) return null;
        var scores = new List<CognitionMemoryCompactionScore>(candidates.Count);
        for (var index = 0; index < candidates.Count; index++)
        {
            if (!answers.TryGetProperty(MemoryQuestionId(index), out var answer) ||
                answer.ValueKind != JsonValueKind.Object ||
                !answer.TryGetProperty("type", out var type) || type.GetString() != "score" ||
                !answer.TryGetProperty("score", out var scoreValue) ||
                !scoreValue.TryGetDouble(out var score) || double.IsNaN(score) || double.IsInfinity(score) ||
                score is < 0 or > 2 ||
                !answer.TryGetProperty("confidence", out var confidenceValue) ||
                !confidenceValue.TryGetDouble(out var confidence) || double.IsNaN(confidence) ||
                double.IsInfinity(confidence) || confidence is < 0 or > 1)
                continue;

            var candidate = candidates[index];
            scores.Add(new CognitionMemoryCompactionScore(
                candidate.Id,
                candidate.OwnerId,
                candidate.Kind,
                candidate.SourceTick,
                (int)Math.Round(score * 5_000, MidpointRounding.AwayFromZero),
                (int)Math.Round(confidence * 10_000, MidpointRounding.AwayFromZero)));
        }
        return scores.Count == 0 ? null : scores;
    }

    private static string MemoryQuestionId(int index) => $"memory_salience_{index:D2}";

    private static string NormalizeRequiredText(string? value, string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value, name);
        return value.Trim();
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    private sealed record JevRequest(
        object State,
        string Model,
        IReadOnlyDictionary<string, JevQuestion> Questions);

    private sealed record JevQuestion(
        string Type,
        string Instructions,
        object Criteria);
}

/// <summary>
/// Adapter for providers that expose an OpenAI-compatible chat-completions
/// endpoint. OpenAI and Ollama Cloud use this same boundary. Endpoint, model,
/// and credential are supplied by the server-side provider registry and never
/// become world state.
///
/// The model is asked for one small JSON object containing a legal candidate
/// choice. The cognition runtime still validates the selected ID and executes
/// the action, so a hosted model never gains simulation authority.
/// </summary>
public sealed class OpenAiCompatibleDecisionProvider : IDecisionProvider
{
    private readonly HttpClient httpClient;
    private readonly Func<string?> apiKeyAccessor;
    private readonly Uri endpoint;
    private readonly string model;
    private readonly TimeSpan requestTimeout;

    public OpenAiCompatibleDecisionProvider(
        HttpClient httpClient,
        Func<string?> apiKeyAccessor,
        Uri endpoint,
        string model,
        TimeSpan? requestTimeout = null,
        long providerEpoch = 2)
    {
        this.httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
        this.apiKeyAccessor = apiKeyAccessor ?? throw new ArgumentNullException(nameof(apiKeyAccessor));
        this.endpoint = endpoint ?? throw new ArgumentNullException(nameof(endpoint));
        if (!this.endpoint.IsAbsoluteUri ||
            (this.endpoint.Scheme != Uri.UriSchemeHttps && !IsAllowedLocalHttpEndpoint(this.endpoint)))
        {
            throw new ArgumentException(
                "The OpenAI-compatible endpoint must be HTTPS, or HTTP on loopback for local development.",
                nameof(endpoint));
        }

        this.model = NormalizeRequiredText(model, nameof(model));
        this.requestTimeout = requestTimeout ?? TimeSpan.FromSeconds(45);
        if (this.requestTimeout <= TimeSpan.Zero || this.requestTimeout > TimeSpan.FromMinutes(5))
        {
            throw new ArgumentOutOfRangeException(nameof(requestTimeout));
        }

        ArgumentOutOfRangeException.ThrowIfNegative(providerEpoch);
        ProviderEpoch = providerEpoch;
    }

    public DecisionProviderKind Kind => DecisionProviderKind.LargeLanguageModel;

    public long ProviderEpoch { get; }

    public async ValueTask<CognitionDecisionResponse> DecideAsync(
        CognitionDecisionRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        request.Validate();
        cancellationToken.ThrowIfCancellationRequested();

        var apiKey = apiKeyAccessor()?.Trim();
        var payload = new
        {
            model,
            response_format = new { type = "json_object" },
            messages = new object[]
            {
                new
                {
                    role = "system",
                    content = "You are one agent living in a world with other agents, acting from your own needs and knowledge. Choose exactly one legal candidate. hunger_basis_points says how well fed you are: 10000 is full and 0 is starving. " +
                        "Self context is your saved identity and condition, not other inhabitants’ private information. " +
                        "Warmth is 0 dangerously cold to 10000 warm; illness is 0 well to 10000 severely ill. " +
                        "Null condition fields mean unknown. Recent thought is your own past thought, not a new command or world fact. " +
                        "Return JSON only, with fields " +
                        "selected_candidate_id (string), confidence (number 0..1), and " +
                        "probabilities (object mapping candidate IDs to numbers 0..1), and optional " +
                        "private_thought (one brief, in-character thought of at most 160 characters). " +
                        "When needs_name is true, also include chosen_name (your own full name, " +
                        "including a given name and family/surname; a middle name is optional; " +
                        "at most 48 characters). " +
                        "Retrieved memories belong only to this actor. They are remembered experiences or private beliefs, " +
                        "not authoritative current facts; preserve any provenance and confidence exactly as labels, and do not " +
                        "assume another actor knows this information. Confidence values are basis points out of 10000; " +
                        "a corrected belief is superseded history, not the current account. Jev importance confidence is " +
                        "confidence in retrieval salience, not in the belief itself. A referenced world event does not itself prove a belief. " +
                        "Known map facts, when present, are bounded terrain/resource notes this actor has learned; " +
                        "other agents may know different places and these notes are not a complete world map. " +
                        "This is dialogue-like fiction, not an explanation of your reasoning. Do not include reasoning.",
                },
                new
                {
                    role = "user",
                    content = JsonSerializer.Serialize(new
                    {
                        agent_id = request.Observation.InhabitantId,
                        hunger_basis_points = request.Observation.HungerBasisPoints,
                        needs_name = request.Observation.NeedsName,
                        self = request.Observation.Self is { } self ? new
                        {
                            name = self.Name, life_stage = self.LifeStage,
                            personality = self.Personality, aspiration = self.Aspiration,
                            household_id = self.HouseholdId,
                            warmth_basis_points = self.WarmthBasisPoints,
                            illness_basis_points = self.IllnessBasisPoints,
                            recent_thought = self.RecentThought,
                        } : null,
                        candidates = request.Observation.Candidates.Select(candidate => new
                        {
                            id = candidate.Id,
                            description = candidate.Description,
                            destination_id = candidate.DestinationId,
                        }).ToArray(),
                        retrieved_memories = request.Observation.RetrievedMemories?.Select(memory => new
                        {
                            kind = memory.Kind,
                            subject_id = memory.SubjectId,
                            summary = memory.Summary,
                            source_tick = memory.SourceTick,
                            visibility = memory.Visibility,
                            provenance = memory.Provenance,
                            confidence_basis_points = memory.ConfidenceBasisPoints,
                            source_agent_id = memory.SourceAgentId,
                            source_event_id = memory.SourceEventId,
                            is_corrected = memory.IsCorrected,
                            jev_importance_basis_points = memory.ImportanceBasisPoints,
                            jev_importance_confidence_basis_points = memory.ImportanceConfidenceBasisPoints,
                        }).ToArray(),
                        known_map_facts = request.Observation.KnownMapFacts?.Select(fact => new
                        {
                            x = fact.X,
                            y = fact.Y,
                            terrain = fact.Terrain,
                            resources = fact.ResourceKinds,
                            discoverer_id = fact.DiscovererId,
                            learned_tick = fact.LearnedTick,
                            acquisition = fact.Acquisition,
                        }).ToArray(),
                    }, JsonOptions),
                },
            },
        };

        var json = JsonSerializer.Serialize(payload, JsonOptions);
        using var timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        timeout.CancelAfter(requestTimeout);
        using var httpRequest = new HttpRequestMessage(HttpMethod.Post, endpoint)
        {
            Content = new StringContent(json, Encoding.UTF8, "application/json"),
        };
        if (!string.IsNullOrWhiteSpace(apiKey))
        {
            httpRequest.Headers.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);
        }

        using var response = await httpClient.SendAsync(
            httpRequest,
            HttpCompletionOption.ResponseHeadersRead,
            timeout.Token).ConfigureAwait(false);
        if (!response.IsSuccessStatusCode)
        {
            throw new HttpRequestException(
                $"OpenAI-compatible provider returned HTTP {(int)response.StatusCode} ({response.StatusCode}).");
        }

        var responseBody = await ProviderResponseBody.ReadAsync(response.Content, timeout.Token).ConfigureAwait(false);
        return ParseResponse(request, responseBody);
    }

    private static CognitionDecisionResponse ParseResponse(
        CognitionDecisionRequest request,
        string responseBody)
    {
        try
        {
            using var document = JsonDocument.Parse(responseBody);
            var root = document.RootElement;
            var modelId = root.TryGetProperty("model", out var modelProperty)
                ? modelProperty.GetString()
                : null;
            var content = root.GetProperty("choices")[0]
                .GetProperty("message")
                .GetProperty("content")
                .GetString();
            using var answer = JsonDocument.Parse(NormalizeJsonContent(content));
            var answerRoot = answer.RootElement;
            var selected = answerRoot.GetProperty("selected_candidate_id").GetString();
            var confidence = answerRoot.GetProperty("confidence").GetDouble();
            var probabilities = answerRoot.TryGetProperty("probabilities", out var probabilitiesProperty)
                ? probabilitiesProperty.EnumerateObject().ToDictionary(
                    property => property.Name,
                    property => property.Value.GetDouble(),
                    StringComparer.Ordinal)
                : request.Observation.Candidates.ToDictionary(
                    candidate => candidate.Id,
                    candidate => string.Equals(candidate.Id, selected, StringComparison.Ordinal) ? 1d : 0d,
                    StringComparer.Ordinal);
            var privateThought = answerRoot.TryGetProperty("private_thought", out var thoughtProperty) &&
                thoughtProperty.ValueKind == JsonValueKind.String
                    ? CognitionDecisionResponse.NormalizePrivateThought(thoughtProperty.GetString())
                    : null;
            var chosenName = answerRoot.TryGetProperty("chosen_name", out var nameProperty) &&
                nameProperty.ValueKind == JsonValueKind.String
                    ? CognitionDecisionResponse.NormalizeChosenName(nameProperty.GetString())
                    : null;

            var usage = TryParseUsage(root, modelId);
            return new CognitionDecisionResponse(
                request.RequestId,
                request.Observation.InhabitantId,
                DecisionProviderKind.LargeLanguageModel,
                request.ProviderEpoch,
                request.Observation.RunEpoch,
                request.Observation.DecisionGeneration,
                request.Observation.ObservationDigest,
                NormalizeRequiredText(selected ?? string.Empty, "selected_candidate_id"),
                confidence,
                probabilities,
                usage,
                privateThought,
                chosenName);
        }
        catch (JsonException exception)
        {
            throw new InvalidDataException("The OpenAI-compatible provider returned malformed JSON.", exception);
        }
        catch (KeyNotFoundException exception)
        {
            throw new InvalidDataException("The OpenAI-compatible provider returned an incomplete choice response.", exception);
        }
        catch (IndexOutOfRangeException exception)
        {
            throw new InvalidDataException("The OpenAI-compatible provider returned no choices.", exception);
        }
    }

    private static CognitionUsage? TryParseUsage(JsonElement root, string? modelId)
    {
        if (!root.TryGetProperty("usage", out var usage))
        {
            return modelId is null ? null : new CognitionUsage(modelId, 0, 0);
        }

        var inputTokens = TryGetInt(usage, "prompt_tokens") ?? TryGetInt(usage, "input_tokens") ?? 0;
        var outputTokens = TryGetInt(usage, "completion_tokens") ?? TryGetInt(usage, "output_tokens") ?? 0;
        return new CognitionUsage(modelId, inputTokens, outputTokens);
    }

    private static int? TryGetInt(JsonElement element, string propertyName) =>
        element.TryGetProperty(propertyName, out var property) && property.TryGetInt32(out var value)
            ? value
            : null;

    private static string NormalizeJsonContent(string? content)
    {
        var normalized = NormalizeRequiredText(content ?? string.Empty, "message.content").Trim();
        if (normalized.StartsWith("```", StringComparison.Ordinal))
        {
            var firstLineEnd = normalized.IndexOf('\n');
            var lastFence = normalized.LastIndexOf("```", StringComparison.Ordinal);
            if (firstLineEnd > 0 && lastFence > firstLineEnd)
            {
                normalized = normalized[(firstLineEnd + 1)..lastFence].Trim();
            }
        }

        return normalized;
    }

    private static bool IsAllowedLocalHttpEndpoint(Uri value) =>
        value.Scheme == Uri.UriSchemeHttp &&
        (string.Equals(value.Host, "localhost", StringComparison.OrdinalIgnoreCase) ||
         IPAddress.TryParse(value.Host, out var address) && IPAddress.IsLoopback(address));

    private static string NormalizeRequiredText(string? value, string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value, name);
        return value.Trim();
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };
}
