using ClankerWorld.GodotClient.UI;
using Godot;

namespace ArtPreview.Proposed.Items;

/// <summary>
/// Proposed 16 × 16 item icons, rounds 1 and 2: the complete item catalogue.
/// Each new icon is a text bitmap in the same form as the game's
/// <see cref="ItemIcons"/>: a palette of "kRRGGBB" entries and sixteen rows of
/// sixteen letters, '.' for empty, with nothing on the outer one-pixel ring so
/// the outline added by <see cref="Bitmap.Outlined"/> always fits. Shades come
/// from the STYLE.md ramps, lit from the top-left and shaded to the
/// bottom-right (I1). Tool tiers share the handle and differ in the head (I3);
/// cooked food sits in a bowl, on a plate or in a nest (I4). Current icons that
/// already fit the set are listed too and drawn by the game's own
/// <see cref="ItemIcons"/>, unchanged, so the catalogue is complete.
/// </summary>
public sealed class ItemsProposal : IArtProposal, IArtSetProvider
{
    public string Family => "items";
    public string Name => "items";

    /// <summary>The icon grid, as in <see cref="ItemIcons.Grid"/>.</summary>
    private const int Grid = 16;

    /// <summary>Outline ink shared with the game's item icons (STYLE.md L3).</summary>
    private static readonly Color Ink = new("2A1A10");

    /// <summary>
    /// One catalogue entry: a note for the review sheet, and either a new
    /// hand-drawn icon (its palette and rows) or, when it has no rows, the
    /// game's current icon kept unchanged.
    /// </summary>
    private sealed record Drawing(string Note, string Palette, string[] Rows)
    {
        /// <summary>True when the entry keeps the game's current icon from <see cref="ItemIcons"/>.</summary>
        public bool KeepsCurrent => Rows.Length == 0;
    }

    /// <summary>A catalogue entry that keeps the game's current icon unchanged.</summary>
    private static Drawing Current(string note) => new(note, "", []);

    // Palettes shared between icons, so tiers and families stay consistent.

    /// <summary>The handle every tool shares: the game's current tool-handle browns (light, shade).</summary>
    private const string Handle = "HC08448 D7A4E26";

    /// <summary>Worked iron, the cool steel of the game's iron bar icon: glint, light, base, shade, dark.</summary>
    private const string Steel = "wEEF2F4 lBFC8CF m939CA5 d6A727B k50575E";

    /// <summary>Fiber cord lashing a head to its handle (Thatch light and shade).</summary>
    private const string Cord = "cE6C77B CA98A45";

    /// <summary>A carved wooden tool head, the wooden tier (Timber highlight, light, base, shade; STYLE I3).</summary>
    private const string WoodHead = "hD2AC77 lA77C52 m8A6440 d6E4E31";

    /// <summary>A knapped stone tool head, the stone tier (Rock highlight, light, base, shade; STYLE I3).</summary>
    private const string StoneHead = "hA49C95 l8B837D m756D68 d625B56";

    /// <summary>
    /// Every item icon in sheet order, grouped as food and drink, seeds,
    /// materials, tools, weapons and protection, containers, clothing and care,
    /// and knowledge and value. Kinds that replace a current icon keep its Id;
    /// round-1 icons the owner approved are unchanged.
    /// </summary>
    private static readonly (string Kind, Drawing Art)[] Drawings =
    [
        // Food and drink
        ("water", new("Fresh water: a Lake-blue drop with a glint, its own silhouette beside the jug.",
            "wE8FFFF h8ABBD6 l6A9FC0 m598FB3 d4A7B9D",
            [
                "................",
                ".......hl.......",
                ".......hm.......",
                "......hllm......",
                "......hlmm......",
                ".....hllmmm.....",
                ".....hlmmmd.....",
                "....hllmmmmd....",
                "....hwlmmmmd....",
                "...hwllmmmmmd...",
                "...hwlmmmmmmd...",
                "...hwlmmmmmdd...",
                "...hlmmmmmmdd...",
                "....lmmmmmdd....",
                ".....dddddd.....",
                "................",
            ])),
        ("milk", new("Milk: a wooden pail with two iron hoops, full to the brim with white milk and a drip down the side (Timber and Snow ramps).",
            "PF4F8F6 pDCE5E0 qB8C6C4 hD2AC77 lA77C52 m8A6440 d6E4E31 k6A727B K50575E",
            [
                "................",
                "................",
                "................",
                "..hhhhhhhhhhhl..",
                ".hPPPPPPPPPPpqm.",
                ".hpPPPPPPPpppqm.",
                "..lqqqqqqqqqqm..",
                "..KkkkkkkkkkKK..",
                "..hPlllllllmmd..",
                "..hPllllllmmmd..",
                "...hllllllmmd...",
                "...KkkkkkkkKK...",
                "...hlllllmmmd...",
                "....dddddddd....",
                "................",
                "................",
            ])),
        ("wild_greens", new("Wild greens: a loose bunch of three pointed leaves with pale midribs, so it reads as picked leaves rather than a lettuce head (broadleaf and orchard canopy greens).",
            "h8DB660 v9BC66F b6C9A4B s557D3E g8DB660 G476B36",
            [
                "................",
                ".......h........",
                "......hvb.......",
                ".h....hvbs....s.",
                ".hh..hhvbs...bs.",
                ".hvb.hvvbs..bvs.",
                "..hvbhbvbs.bvbs.",
                "..hbvbhvbsbvbs..",
                "...hbvbvbbvbs...",
                "....hbvvvvbs....",
                ".....hbvvbs.....",
                "......gGGG......",
                ".......gG.......",
                ".......gG.......",
                "................",
                "................",
            ])),
        ("cultivated_greens", new("Cultivated greens: a full lettuce head with a pale heart, veins and frilled outer leaves, apart from the loose wild greens (Canopy greens, Cloth veins, STYLE N5).",
            "v9BC66F h8DB660 l6C9A4B b557D3E s476B36 cE8DCC0",
            [
                "................",
                "................",
                "................",
                "......hvvh......",
                "....hhvvvvhb....",
                "...hvvcvvcvbb...",
                "..hlhvvcvcvhbs..",
                ".hlhlvvvcvvhlbs.",
                ".hlhllhvvvhllbs.",
                ".lhlllhhhhllbbs.",
                ".hlbhllbllbllbs.",
                ".lb.lbllbblbs.s.",
                ".l...lbs.bs...s.",
                "................",
                "................",
                "................",
            ])),
        ("potato", new("Potato: two lumpy tan potatoes with eyes, a big one behind and a small one in front (Timber light and highlight).",
            "wE3D6B5 hD2AC77 lA77C52 e8A6440",
            [
                "................",
                "................",
                "................",
                "...whhhh........",
                "..whhhhhhl......",
                ".whhehhhhhl.....",
                ".hhhhhhhehl.....",
                ".hhhhhhhhll.....",
                ".hheehhhhll.....",
                ".lhhhhhhll......",
                "..llhhll..hhh...",
                "...llll..whhhl..",
                ".........hhehll.",
                ".........lhhlll.",
                "..........llll..",
                "................",
            ])),
        ("grain", new("Grain (round 2): round 1's full sheaf, redrawn to read as wheat: three pointed ears with a checker of plump kernels and fine awns, thin stalks to a twine band, and a flared bundle of stalks (Thatch ramp with Gold kernels).",
            "hF0DA9A lE6C77B bD2AE5E sA98A45 e6B5528 t8A6440 TA77C52 gD9AE3C GF0DA9A",
            [
                "................",
                ".l....l..l....l.",
                "..l....Gg....l..",
                "..G...GgGs...G..",
                ".GgG..gGgs..GgG.",
                ".gGgs.GgGs.GgGs.",
                ".GgGs.gGgs.gGgs.",
                "..gGs.GgGs.GgG..",
                "...gs..gs..gs...",
                "....b..bs..s....",
                ".....b.bs.s.....",
                ".....tTTTTt.....",
                "....bsbsbsbs....",
                "...bsbsbsbsbs...",
                "..bsbsbsbsbsbs..",
                "................",
            ])),
        ("flour", Current("Flour: the current icon, unchanged. A white sack with a puff of flour; it fits the set and stays apart from the new burlap sack.")),
        ("food", Current("Food: the current icon, unchanged. A red apple with a leaf; it already follows the rules.")),
        ("fruit", Current("Fruit: the current icon, unchanged. An orchard pear; it already follows the rules.")),
        ("berries", Current("Berries: the current icon, unchanged. Purple berry clusters; they already follow the rules.")),
        ("eggs", new("Eggs: two cream eggs in a straw nest (Cloth and Thatch ramps).",
            "PFFF5DF pE8DCC0 qCABC99 QA09170 hF0DA9A lE6C77B bD2AE5E sA98A45 e6B5528",
            [
                "................",
                "................",
                "................",
                ".....PPp........",
                "....PPppq.......",
                "....Pppqq.PPp...",
                "...PPppqqPPppq..",
                "...Pppqqqpppqq..",
                "...PppqqQppqqQ..",
                ".hlbppqQbpqqQbs.",
                ".hlbsbsbsbsbsbs.",
                ".lbsbsbsbsbsbss.",
                "..sbsbsbsbsbss..",
                "...sesesesese...",
                "................",
                "................",
            ])),
        ("bread", new("Bread: a taller domed loaf with three diagonal scores showing pale crumb, in the current crust colours (STYLE I4).",
            "cC07A34 CDC9C52 hF2C27E uF0DA9A d8A5222 k6A3C18",
            [
                "................",
                "................",
                "................",
                "................",
                "......CCCC......",
                "....CChhCCcc....",
                "...ChhhuCCCuc...",
                "..ChhCuCCCuCcc..",
                ".ChhCuCCCuCCccd.",
                ".cCCuCCCuCCcccd.",
                ".cCCCCCCCCCcccd.",
                ".cccccccccccccd.",
                "..cccccccccccdd.",
                "...kdddddddddk..",
                "................",
                "................",
            ])),
        ("porridge", new("Porridge: a wooden bowl of creamy porridge with a spoon (Timber bowl, Cloth porridge, STYLE I4).",
            "RD2AC77 bA77C52 B8A6440 d6E4E31 cFFF5DF CE8DCC0 qCABC99 sD2AC77 SA77C52",
            [
                "................",
                "............sS..",
                "...........sS...",
                "..........sS....",
                ".....ccccsSc....",
                "...ccCCCsSCqq...",
                "..RcCCCCCCCqqR..",
                ".RcCCCqCCCCqqqR.",
                ".RCCCCCCCCqqqqR.",
                ".bRRRRRRRRRRRRB.",
                ".bbbbBBBBBBBBBd.",
                "..bbBBBBBBBBBd..",
                "...BBBBBBBBBd...",
                "....dBBBBBBd....",
                ".....dddddd.....",
                "................",
            ])),
        ("stew", new("Stew: a clay bowl with two lug handles, brown broth with potato and greens (Clay ramp, STYLE I4).",
            "REFA882 bD5825A BB8623C d8E4428 o8A6440 O6E4E31 yA77C52 pD2AC77 PE3D6B5 g8DB660 G557D3E",
            [
                "................",
                "................",
                "................",
                "................",
                "....RRRRRRRR....",
                "..RRyooPpooyRR..",
                ".RooPpoogGooOOR.",
                ".RyGgooooPpoOOR.",
                ".bRoooGgooOOORd.",
                "..bRRRRRRRRRRd..",
                ".bbBBBBBBBBBBdd.",
                ".dbbBBBBBBBBddd.",
                "..bbBBBBBBBBdd..",
                "...bBBBBBBBBd...",
                ".....dddddd.....",
                "................",
            ])),
        ("meal", new("Meal: two cooked potatoes and a heap of greens on a pale plate with a lit rim (STYLE I4).",
            "PFFF5DF pE8DCC0 qCABC99 QA09170 wE3D6B5 hD2AC77 lA77C52 e8A6440 g8DB660 G6C9A4B k476B36",
            [
                "................",
                "................",
                "................",
                "................",
                "...gg...........",
                "..gGGg.whh......",
                ".gGkGgwhhhl.....",
                ".kgGkGhhhhe.wh..",
                "..kGkkhhhlewhhl.",
                ".PPPPPPlllehhll.",
                ".Ppppppppppppll.",
                ".qpppppppppppQQ.",
                "..qqqqqqqqqqQQ..",
                "....QQQQQQQQ....",
                "................",
                "................",
            ])),
        ("restaurant_meal", new("Restaurant meal: a slice of bread and a heap of farmed greens on a blue-rimmed plate, a step up from the plain meal on its cream plate (STYLE I4).",
            "PFFF5DF pE8DCC0 B6A9FC0 N4A7B9D cC07A34 CDC9C52 uF0DA9A g8DB660 G6C9A4B k476B36",
            [
                "................",
                "................",
                "................",
                "...CCCC.........",
                "..CuuuuC........",
                "..CuuuuC..ggg...",
                "..CuuuuC.gGGgg..",
                "..CuuuuCgGkGGgk.",
                "..CuuuucGkGkGkk.",
                ".BCccccPPPPPPPB.",
                ".BppppppppppppB.",
                ".NBppppppppppBN.",
                "..NBBBBBBBBBBN..",
                "...NNNNNNNNNN...",
                "................",
                "................",
            ])),

        // Seeds
        ("seed", Current("Seed: the current icon, unchanged. Brown seeds in pairs, the generic seed.")),
        ("grain_seed", new("Grain seed: a scatter of golden kernels in the colours of the grain ears.",
            "GF0DA9A gD9AE3C sB8902E d8A6A1E",
            [
                "................",
                "................",
                "................",
                "......Gg........",
                ".....Ggs...Gg...",
                ".....gss..Ggs...",
                "......s...gss...",
                "...Gg......s....",
                "..Ggs..Gg.......",
                "..gss.Ggs..Gg...",
                "...s..gss.Ggs...",
                ".......s..gss...",
                "...........s....",
                "................",
                "................",
                "................",
            ])),
        ("green_seed", new("Greens seed: small dark seeds with a sprouting seedling; the green marks the seed for farmed greens.",
            "h8DB660 l6C9A4B g476B36 sA77C52 d6E4E31",
            [
                "................",
                "................",
                "...hl....lg.....",
                "..hhll..llgg....",
                "..hlll.hllgg....",
                "...hlg.llg......",
                ".....gg.........",
                "......g.........",
                ".....sd.........",
                "..sd.dd...sd....",
                "..dd....sd.dd...",
                "........dd..sd..",
                "...sd.......dd..",
                "...dd...........",
                "................",
                "................",
            ])),
        ("orchard_seed", new("Orchard seed: half an orchard pear showing its dark pips, in the fruit icon colours, so it reads apart from the other seeds.",
            "s5E3A1E yC9C24E YDCD872 pF2EEB0 PE8DCC0 q8E8428 k3F2A1A K6E4E31 hA77C52 g6AA640 G3E6E28",
            [
                "................",
                ".......s.gg.....",
                ".......sgGG.....",
                "......yYYq......",
                ".....yppPPq.....",
                ".....YpPPPq.....",
                "....yppKKPPq....",
                "...yppPhkPPPq...",
                "...YpKhKkKPPq...",
                "..yppkkPkkPPPq..",
                "..YpPPKkPPPPPq..",
                "..ypPPPPPPPPqq..",
                "..qPPPPPPPPPqq..",
                "...qqPPPPPPqq...",
                ".....qqqqqq.....",
                "................",
            ])),
        ("tree_seed", Current("Tree seed: the current icon, unchanged. An acorn, apart from the crop seeds.")),

        // Materials
        ("wood", new("Wood: the same two logs, with rounder pale end grain showing a growth ring and pith, and bark grooves as short strokes instead of specks (Timber ramp, Thatch light end grain).",
            "fE6C77B rD2AC77 cA77C52 lA77C52 m8A6440 b6E4E31",
            [
                "................",
                "................",
                "................",
                "....fffllllllll.",
                "...frrrfmmlmmmm.",
                "...frcrfbbmmmbb.",
                "...frrrfmmmbmmm.",
                "....fffbbbbbbbb.",
                "................",
                "..ffflllllllll..",
                ".frrrfmmmlmmmm..",
                ".frcrfbbmmmbbm..",
                ".frrrfmmbmmmmm..",
                "..fffbbbbbbbbb..",
                "................",
                "................",
            ])),
        ("stone", new("Stone: a faceted chunk with a flat lit top, a crease and a loose pebble, in the cool Peak greys so it stays apart from the warmer iron ore.",
            "wEEF3F1 hC4C7C5 lAEB2B0 m8E8A85 d5F5955",
            [
                "................",
                "................",
                "......whhh......",
                "....whhhhhhm....",
                "...whhhhhhhhm...",
                "..whhhhhhhhmmm..",
                "..lllhhhhhdmmmd.",
                ".lllllllldmmmmd.",
                ".llllllldmmmmdd.",
                ".lllllldmmmmddd.",
                "..mllllmmmmdd...",
                "...mmmlmmddd.hl.",
                ".....mmmdd.hlmd.",
                "............lmd.",
                "................",
                "................",
            ])),
        ("clay", Current("Clay: the current icon, unchanged. A wet clay lump in the Clay ramp.")),
        ("iron_ore", Current("Iron ore: the current icon, unchanged. A warm grey lump with rust flecks; the round-1 stone moved to cool greys and a new shape, so the two no longer clash.")),
        ("iron", Current("Iron: the current icon, unchanged. Two steel bars; the iron tools take their steel from it.")),
        ("gold", new("Gold: a small pile of raw gold nuggets with bright facets (Gold ramp); the coin keeps the round shape.",
            "hFFE28A lF2CC5E bD9AE3C mB8902E d8A6A1E",
            [
                "................",
                "................",
                "................",
                "................",
                "......hl........",
                "....hhlbm.hl....",
                "...hlhlbmhlbm...",
                "...llbbmmlbbmd..",
                "..hlbbmmdbbmmd..",
                ".hlhbmmd.mmdd...",
                ".lllbbmhllbm....",
                ".lbbmmhlhbbmd...",
                "..mmmdlbbbmmd...",
                "......mmmmdd....",
                "................",
                "................",
            ])),
        ("diamond", new("Diamond: a cut gem with a flat table, crown and pavilion facets (Diamond ramp).",
            "wE8FFFF lB4EEF2 m7FD3DC s5FB4BE",
            [
                "................",
                "................",
                "................",
                "....wwlllllm....",
                "...wllwwllmms...",
                "..wlllwllllmss..",
                ".mmmmmmmmmmssss.",
                "..lllmlllmmsss..",
                "...llmlllmsss...",
                "....lmllmmss....",
                ".....mlmmss.....",
                "......lmss......",
                ".......ms.......",
                "................",
                "................",
                "................",
            ])),
        ("fiber", Current("Fiber: the current icon, unchanged. A ball of plant fiber, apart from the brown rope coil and the cream wool.")),
        ("cloth", Current("Cloth: the current icon, unchanged. A folded cream cloth.")),
        ("wool", new("Wool: a fluffy fleece of small cream curls, textured so it stays apart from the smooth cloth (Cloth ramp).",
            "hFFF5DF lE8DCC0 mCABC99 dA09170",
            [
                "................",
                "................",
                "................",
                "....hh.hh.hh....",
                "...hllhllhllm...",
                "..hlhmlhmlhmlm..",
                ".hllmhllmhllmmd.",
                ".lhmlhmlhmlhmld.",
                ".hllmhllmhllmmd.",
                ".lhmlhmlhmlhmld.",
                "..lmmlmmlmmlmd..",
                "..mdmmdmmdmmdd..",
                "...d..d..d..d...",
                "................",
                "................",
                "................",
            ])),
        ("hide", new("Hide: a raw pelt stretched flat, with four legs and a pale flesh side (Timber and Cloth ramps).",
            "hD2AC77 lA77C52 m8A6440 d6E4E31 cCABC99",
            [
                "................",
                "................",
                ".hl....hl....lm.",
                ".hll..hllm..lmd.",
                "..hllhlllmmlmd..",
                "...hllcccllmd...",
                "...hlcccccmmd...",
                "...llccccclmd...",
                "...lmcccccmmd...",
                "...lmmcccmmmd...",
                "..lmmmmmmmmmdd..",
                ".lmd.mmmmmd.mdd.",
                ".md...mmdd...dd.",
                ".......dd.......",
                "................",
                "................",
            ])),
        ("leather", new("Leather: a flat sheet of tanned leather with stitching along two edges and a curled corner (Rust ramp).",
            "hE0A070 lC98A5A bB7774C mA9643C d7A4426",
            [
                "................",
                "................",
                "................",
                ".......lll.lll..",
                ".....llbbblbbbm.",
                "....lbhbhbhbhbm.",
                "....lbbbbbbbbhm.",
                "...lhbbbbbbbbbm.",
                "...lbbbbbbbbbhm.",
                "..lhbbbbbbbbbm..",
                "..lbbbbbbbbbhm..",
                ".lhbbbbbbbbbmm..",
                ".lbhbhbhbhbmhl..",
                ".mmm.mmmmmmmld..",
                "................",
                "................",
            ])),

        // Tools
        ("wooden_axe", new("Wooden axe: a carved wooden blade (Timber light) lashed to the shared handle with fiber cord (STYLE I3).",
            Handle + " " + Cord + " " + WoodHead,
            [
                "................",
                ".hh......HD.....",
                ".hlll....HD.....",
                ".hllllllcCcC....",
                ".hlllmmmCcCc....",
                ".hlmmmmmcCcC....",
                ".hmmdddmCcCc....",
                ".mmd.....HD.....",
                ".dd......HD.....",
                ".........HD.....",
                ".........HD.....",
                ".........HD.....",
                ".........HD.....",
                ".........HD.....",
                ".........DD.....",
                "................",
            ])),
        ("stone_axe", new("Stone axe: a knapped stone head (Rock light) with rounded, chipped corners, lashed to the shared handle (STYLE I3).",
            Handle + " " + Cord + " " + StoneHead,
            [
                "................",
                "..hh.....HD.....",
                ".hhll....HD.....",
                ".hlhllmmcCcC....",
                ".hllmlmmCcCc....",
                ".lhlmmdmcCcC....",
                ".lmmdmddCcCc....",
                ".mmdd....HD.....",
                "..dd.....HD.....",
                ".........HD.....",
                ".........HD.....",
                ".........HD.....",
                ".........HD.....",
                ".........HD.....",
                ".........DD.....",
                "................",
            ])),
        ("iron_axe", new("Iron axe: a flared steel blade with a socket round the shared handle and a one-pixel glint (STYLE I3).",
            Handle + " " + Steel,
            [
                "................",
                "..ll.....HD.....",
                ".wllll..lmmd....",
                ".wllmmmmlwmdd...",
                ".wlmmmmmlmmdd...",
                ".wlmmdddlmmdd...",
                ".wmmdd..lmmd....",
                ".wmdd....HD.....",
                "..dd.....HD.....",
                ".........HD.....",
                ".........HD.....",
                ".........HD.....",
                ".........HD.....",
                ".........HD.....",
                ".........DD.....",
                "................",
            ])),
        ("wooden_pickaxe", new("Wooden pickaxe (round 2): redrawn under rule I3 with a carved wooden head lashed to the shared handle, in the iron pickaxe's layout.",
            Handle + " " + Cord + " " + WoodHead,
            [
                "................",
                ".......HD.......",
                "...hhlcCcCmmd...",
                "..hllmCcCcmmdd..",
                ".hlm..cCcC..mdd.",
                ".hl....HD....dd.",
                ".l.....HD.....d.",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......DD.......",
                "................",
            ])),
        ("stone_pickaxe", new("Stone pickaxe: the shared pickaxe layout with a knapped stone head lashed on (Rock ramp, STYLE I3).",
            Handle + " " + Cord + " " + StoneHead,
            [
                "................",
                ".......HD.......",
                "...hhlcCcCmmd...",
                "..hllmCcCcmmdd..",
                ".hlm..cCcC..mdd.",
                ".hl....HD....dd.",
                ".l.....HD.....d.",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......DD.......",
                "................",
            ])),
        ("iron_pickaxe", new("Iron pickaxe: the wooden pickaxe's layout with a steel head, socket and glint (STYLE I3).",
            Handle + " " + Steel,
            [
                "................",
                ".......HD.......",
                "...wlllwmmmmd...",
                "..wllmlwmmmmdd..",
                ".wlm..lmmd..mdd.",
                ".wl....HD....dd.",
                ".l.....HD.....d.",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......DD.......",
                "................",
            ])),
        ("wooden_hoe", new("Wooden hoe: a carved wooden blade with a pale bevelled edge on a neck, lashed to the shared handle (STYLE I3).",
            Handle + " " + Cord + " " + WoodHead + " eF0DA9A",
            [
                "................",
                "..........HD....",
                "....hhhhhcCcC...",
                "...hllllmCcCc...",
                "..ehlm...cCcC...",
                "..ehhl....HD....",
                ".ehhll....HD....",
                ".ehhlm....HD....",
                ".ehllm....HD....",
                ".edddd....HD....",
                "..........HD....",
                "..........HD....",
                "..........HD....",
                "..........HD....",
                "..........DD....",
                "................",
            ])),
        ("iron_hoe", new("Iron hoe: the same hoe in steel, with a socket and a bright edge (STYLE I3).",
            Handle + " " + Steel,
            [
                "................",
                "..........HD....",
                "...lllllllmmd...",
                "..wlllmmmlmmdd..",
                "..wllm...lmmd...",
                "..wlmm....HD....",
                ".wllmd....HD....",
                ".wlmmd....HD....",
                ".wmddd....HD....",
                ".dddd.....HD....",
                "..........HD....",
                "..........HD....",
                "..........HD....",
                "..........HD....",
                "..........DD....",
                "................",
            ])),
        ("sickle", new("Sickle: a curved steel blade, bright on its inner cutting edge, on the shared handle with an iron ferrule.",
            Handle + " " + Steel,
            [
                "................",
                ".....mmmmm......",
                "...mmwlllmmd....",
                "..mlw.....lmd...",
                ".mlw.......lmd..",
                ".mw........lmd..",
                ".mw........lmd..",
                "..w........lmd..",
                "...........lmd..",
                "..........kmmk..",
                "...........HD...",
                "...........HD...",
                "...........HD...",
                "...........HD...",
                "...........DD...",
                "................",
            ])),
        ("hammer", new("Hammer: wood and stone, a squared stone head lashed to the shared handle.",
            Handle + " " + Cord + " " + StoneHead,
            [
                "................",
                "................",
                "...hhhhhhhhhl...",
                "..hhllllllllmd..",
                "..hlllllllllmd..",
                "..lmmmmmmmmmmd..",
                "...dddcCcCddd...",
                "......CcCc......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......DD.......",
                "................",
            ])),
        ("knife", new("Knife: a broad steel blade on a short wooden handle with a rivet.",
            Handle + " " + Steel + " rE6C77B",
            [
                "................",
                "................",
                "..wm............",
                ".wllm...........",
                ".wlllm..........",
                "..wllmd.........",
                "...wllmd........",
                "....wllmd.......",
                ".....wlmmk......",
                "......dmkHH.....",
                ".........HrHD...",
                "..........HHDD..",
                "...........HDDD.",
                "............DDD.",
                ".............D..",
                "................",
            ])),
        ("tool", new("Tool (round 2): the generic tool becomes a crossed mallet and pick, so it no longer looks like the new hammer.",
            Handle + " " + Steel + " aD2AC77 bA77C52 e8A6440 f6E4E31",
            [
                "................",
                "..aab......wl...",
                ".abbef....wllm..",
                ".abeef....lmmd..",
                "..effHD..HD.d...",
                "......HDHD......",
                ".......HD.......",
                "......HDHD......",
                ".....HD..HD.....",
                "....HD....HD....",
                "...HD......HD...",
                "..HD........HD..",
                ".DD..........DD.",
                "................",
                "................",
                "................",
            ])),

        // Weapons and protection
        ("spear", new("Spear: a leaf-shaped steel head with a socket on the shared handle.",
            Handle + " " + Steel,
            [
                "................",
                ".......wl.......",
                "......wllm......",
                ".....wlllmd.....",
                ".....wllmmd.....",
                ".....wlmmmd.....",
                "......wlmd......",
                ".......md.......",
                "......kmmk......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......HD.......",
                ".......DD.......",
                "................",
            ])),
        ("sword", new("Sword: a steel blade with a cross guard, grip and pommel, lying diagonally.",
            Steel + " " + Handle,
            [
                "................",
                ".............w..",
                "............wlm.",
                "...........wlmd.",
                "..........wlmd..",
                ".........wlmd...",
                "........wlmd....",
                "...k...wlmd.....",
                "....k.wlmd......",
                ".....kmmd.......",
                "....HDkm........",
                "...HD..k........",
                "..HD....k.......",
                ".kk.............",
                ".kk.............",
                "................",
            ])),
        ("shield", new("Shield: a wooden heater shield with an iron rim and boss.",
            Steel + " hD2AC77 aA77C52 b8A6440 s6E4E31",
            [
                "................",
                "................",
                "..llllllllllmd..",
                "..lhhaahhaabsd..",
                "..lhaabhaabbsd..",
                "..lhaabwlabbsd..",
                "..lhaabmdabbsd..",
                "..lhaabhaabbsd..",
                "..lhaabhaabbsd..",
                "...lhabhaabsd...",
                "...lhabhaabsd...",
                "....lbhaabsd....",
                ".....lhabsd.....",
                "......lmdd......",
                "................",
                "................",
            ])),
        ("armor", new("Armor: a steel breastplate with shoulder plates, a leather belt and a plated skirt.",
            Steel + " tA77C52 T6E4E31",
            [
                "................",
                "................",
                "..wll......lmd..",
                ".wlllt....tmmdd.",
                ".wllmlt..tlmmdd.",
                ".lllmmlllllmmdd.",
                "..ddwllllllmdd..",
                "....wllllllmd...",
                "....wlllmllmd...",
                "....lllmlmmmd...",
                "....TTTTTTTTT...",
                "...wllmlmlmmdd..",
                "...lmdlmdlmddd..",
                "...ddddddddddd..",
                "................",
                "................",
            ])),

        // Containers and carrying
        ("rope", new("Rope: a coil of twisted rope seen from above, two turns with dark gaps between them and a frayed loose end (Timber browns).",
            "hD2AC77 mA77C52 d8A6440 fE6C77B",
            [
                "................",
                ".....mhhmhh.....",
                "...hmhhmhhmhh...",
                "..hmh......hdm..",
                "..mh..hhmh..mm..",
                ".mh..hhmhhd..dm.",
                ".hh.hhm..dmm.mm.",
                ".hm.hm....md.md.",
                ".mh.mhh..mdm.dm.",
                ".hh..hdmmdm..mm.",
                "..mh..mmdm..mm..",
                "..hhd......mmd..",
                "...dmmdmmdmmd...",
                ".....dmmdmmdmm..",
                "............mhf.",
                "................",
            ])),
        ("basket", new("Basket: a woven wicker basket with an arched handle (Thatch ramp).",
            "hF0DA9A lE6C77B bD2AE5E sA98A45 e6B5528",
            [
                "................",
                ".....hlllls.....",
                "....hl....bs....",
                "...hl......bs...",
                "...hl......bs...",
                "...hl......bs...",
                ".hhllllllllllls.",
                ".lsssssssssssse.",
                ".llbbllbbllbbse.",
                "..bbllbbllbbse..",
                "..llbbllbbllse..",
                "..bbllbbllbbse..",
                "...llbbllbbse...",
                "....eeeeeeee....",
                "................",
                "................",
            ])),
        ("sack", new("Sack: a burlap sack tied with rope, darker and coarser than the white flour sack (Cloth shade steps, Timber rope).",
            "hE8DCC0 lCABC99 mA09170 d75674D tD2AC77 TA77C52 R8A6440",
            [
                "................",
                ".....hll.lm.....",
                "......lmlm......",
                ".....tTTTTR.....",
                "......lllm.R....",
                ".....hllllm.R...",
                "....hlllmllm....",
                "...hllllllmmd...",
                "...hlmllllmmd...",
                "..hllllllmlmmd..",
                "..hllmllllmmmd..",
                "..lllllmllmmmd..",
                "..mllllllmmmdd..",
                "...mmmmmmmmdd...",
                "................",
                "................",
            ])),
        ("handcart", new("Handcart: a plank cart on a spoked, iron-rimmed wheel, with a pulling handle and grip (Timber ramp).",
            "hD2AC77 lA77C52 m8A6440 d6E4E31 K6A727B",
            [
                "................",
                "................",
                "................",
                ".h..............",
                ".hhhhhhhhhh.....",
                ".hllllllllm.....",
                ".hlmllmllmm.....",
                ".hlmllmllmmhhhh.",
                ".lmmmmmmmmmmmmd.",
                ".ddKKKKKddd...d.",
                "..K..l..K.......",
                ".K...l...K......",
                ".KlllllllK......",
                ".K...l...K......",
                "..K..l..K.......",
                "................",
            ])),
        ("clay_pot", new("Clay pot: a round storage pot with a lid, a knob and a dark band (Clay ramp); squat and without a handle beside the water jug.",
            "hEFA882 lD5825A bB8623C s8E4428 d6A3020",
            [
                "................",
                "................",
                ".......hl.......",
                ".....hhllbb.....",
                "....ssssssss....",
                ".....hllllb.....",
                "...hhllllllbb...",
                "..hllllllllbbs..",
                ".hlllllllllbbbs.",
                ".lddsddsddsddds.",
                ".llllllllllbbbs.",
                "..lllllllbbbbs..",
                "...bbbbbbbbss...",
                "....ssssssss....",
                "................",
                "................",
            ])),
        ("water_jug", new("Water jug: a clay jug with a handle and a glimpse of water in the mouth (Clay ramp).",
            "hEFA882 lD5825A bB8623C s8E4428 w7FB4CF",
            [
                "................",
                "....hhhhhh......",
                "....hwwwwb......",
                ".....lbbs.......",
                ".....lbbsbllb...",
                "....hlbbbs..lb..",
                "...hlbbbbbs..lb.",
                "..hlbbbbbbbs.ls.",
                "..lbbbbbbbbbbs..",
                "..lbbbbbbbbbs...",
                "..lbbbbbbbbbs...",
                "..bbbbbbbbbbs...",
                "...bbbbbbbbs....",
                "....sssssss.....",
                "................",
                "................",
            ])),
        ("crate", Current("Crate: the current icon, unchanged. It stays the plain fallback for any item without its own icon.")),

        // Clothing and care
        ("clothing", new("Clothing: the same blue tunic, now lit from the left and shaded on the right, with a V neck, dark cuffs, a belt with a buckle and a hem.",
            "b4A6E9E B6C92C4 h92B4DE d32507E k263E62 t7A4E2A TC09A5A",
            [
                "................",
                "................",
                "....bBhkkBbb....",
                "..bBhhBhkBBBbd..",
                ".bBhhBBBBBBBBbd.",
                ".bhBBBBBBBBBbbd.",
                ".BhBBBBBBBBBbdd.",
                ".ddbhBBBBBBbbdd.",
                "....hBBBBBbd....",
                "....tttTTttt....",
                "....hBBBBBbd....",
                "....hBBBBBbd....",
                "...hBBBBBBBbd...",
                "...dddddddddd...",
                "................",
                "................",
            ])),
        ("cold_clothing", new("Cold-weather clothing: a long brown coat with a fluffy cream fur collar, cuffs and hem.",
            "hD2AC77 lA77C52 m8A6440 d6E4E31 FFFF5DF fE8DCC0 gCABC99 tC09A5A",
            [
                "................",
                "....FfF..FfF....",
                "...FfffFFfffg...",
                "..hFfggffggfgd..",
                ".hlhFfgllgfgmmd.",
                ".hlhlFfllfgmmmd.",
                ".hlhllFffglmmmd.",
                ".FfhllltlmlmmFg.",
                ".fglllllllmmmfg.",
                "...hllllltmmd...",
                "...hllllllmmd...",
                "...hllllltmmd...",
                "...hllllllmmd...",
                "...FfFfFfFfgg...",
                "................",
                "................",
            ])),
        ("wet_clothing", new("Wet-weather clothing: a hooded cape of waxed green oilcloth, with rain drops beside it.",
            "hA8B4A2 l8E9B88 m6F7C6A s566150 d30372D w8ABBD6 W598FB3",
            [
                "................",
                "..w.............",
                ".wW...hhll...w..",
                ".W...hlllmm.wW..",
                ".....hlddsm.W...",
                ".....hldddm.....",
                "....hhlsssmm....",
                "....hllllmmm....",
                "...hlllsllmms...",
                "...hllsllllms...",
                "..hlllsllsllms..",
                "..hllsllllslms..",
                ".hlllsllllsllms.",
                ".sssssssssssssd.",
                "................",
                "................",
            ])),
        ("herbs", new("Medicinal herbs: a tied bunch of blue-green sprigs with lilac flower tips.",
            "f86B89A l5E9278 m3F7358 d2F5B45 pC8A8D4 P8F6A9E cE6C77B CA98A45 s6E4E31",
            [
                "................",
                ".........pP.....",
                "....pP...Pf..pP.",
                "....Pf..flm..Pf.",
                "...flm.fflm.flm.",
                "...ffmlflmmflmd.",
                "....flmflmmlmd..",
                "....lmdlmdlmd...",
                ".....lmmdmmd....",
                "......cCcCd.....",
                "......CcCc......",
                ".....s.ss.......",
                "....s..s.s......",
                "...s...s..s.....",
                "................",
                "................",
            ])),
        ("bandage", new("Bandage: a cream cloth roll with its spiral end showing and the loose strip unrolling to the right (Cloth ramp).",
            "hFFF5DF lE8DCC0 mCABC99 dA09170",
            [
                "................",
                "................",
                "................",
                ".....hhhh.......",
                "...hhllllhm.....",
                "..hlldddllmm....",
                "..hldlllldmm....",
                ".hldlhhdldlmm...",
                ".hldlhddldlmm...",
                ".hlldllldllmhhh.",
                "..hlldddllmmlll.",
                "..lllllllmmllmd.",
                "...mmmmmmmlllmd.",
                ".........mmmmd..",
                "................",
                "................",
            ])),
        ("medicine", new("Medicine: a corked glass bottle (Snow greys) of red tincture (Berry ramp) with a cream label and a green cross.",
            "cA77C52 C6E4E31 gDCE5E0 GB8C6C4 rC4474B RA33A3F pF08A8A LE8DCC0 x557D3E",
            [
                "................",
                "......cccc......",
                "......cCCC......",
                ".......gG.......",
                "......ggGG......",
                ".....gprrRG.....",
                "....gprrrrRG....",
                "...gprrrrrrRG...",
                "...grLLxLLrRG...",
                "...grLxxxLrRG...",
                "...grLLxLLrRG...",
                "...grrrrrrRRG...",
                "....GrrrrRRG....",
                ".....GGGGGG.....",
                "................",
                "................",
            ])),

        // Knowledge and value
        ("paper", new("Paper: a small stack of cool white sheets, the top one with a turned corner, cooler than the cream cloth (Snow ramp).",
            "hF4F8F6 lDCE5E0 mCCD7D1 sB8C6C4 d9AAAA8",
            [
                "................",
                "................",
                "....hhhhhhhs....",
                "....hllllllds...",
                "..mmhlllllldds..",
                "..mmhllllllllm..",
                "..mmhllllllllm..",
                "..mmhllllllllm..",
                "..mmhllllllllm..",
                "..mmhllllllllm..",
                "..mmhllllllllm..",
                "..mmhllllllllm..",
                "..mmlmmmmmmmmm..",
                "..sssssssssss...",
                "................",
                "................",
            ])),
        ("map", new("Map: a three-panel folded map on sand-coloured paper, with land, a river and a red route to an X.",
            "hE3D6B5 lC8B78C bBAA77B sA08F66 g6FA069 G527F4F w4786AB rC4474B",
            [
                "................",
                "................",
                ".hhhhh.....hhhh.",
                ".hhgghlllllhhhh.",
                ".hgGGhbbbbbhrhh.",
                ".hgggwwbbbblrhh.",
                ".hhhhlbwwbbhrhh.",
                ".hrhhlbbbwwhrhh.",
                ".hhrrlrrbbbwwwh.",
                ".hhhhlbbrrrhhrh.",
                ".hhhhlbbbbbhrhr.",
                ".hhhhlbbbbbhhhh.",
                ".sssssbbbbbssss.",
                "......sssss.....",
                "................",
                "................",
            ])),
        ("record", new("Written record: a parchment scroll with rolled ends, lines of writing and a red wax seal.",
            "hE3D6B5 lC8B78C bBAA77B sA08F66 d7E6E4A tA77C52 rC4474B RA33A3F pF08A8A",
            [
                "................",
                "................",
                "..hhhhhhhhhhhl..",
                ".hllllllllllbbs.",
                "..sssssssssssd..",
                "...hhhhhhhhhs...",
                "...htttthtttb...",
                "...hhhhhhhhhs...",
                "...httthttttb...",
                "...hhhhhhhhhs...",
                "...htthttpRhb...",
                "..hhhhhhprRls...",
                ".hlllllllRRbbs..",
                "..sssssssr.r....",
                "................",
                "................",
            ])),
        ("book", new("Book: a closed book with a red leather cover (Berry ramp), a small gold emblem and cream page edges.",
            "RF08A8A rC4474B sA33A3F e7A2A2E pFFF5DF PCABC99 GF2CC5E",
            [
                "................",
                "................",
                "...RRRRRRRRRR...",
                "..eRrrrrrrrrrs..",
                "..eRrrrrrrrrrsp.",
                "..eRrrrGGrrrrsp.",
                "..eRrrGrrGrrrsp.",
                "..eRrrrGGrrrrsp.",
                "..eRrrrrrrrrrsp.",
                "..eRrrrrrrrrrsp.",
                "..eRrrrrrrrrrsp.",
                "..essssssssssPp.",
                "...pppppppppppP.",
                "....PPPPPPPPPP..",
                "................",
                "................",
            ])),
        ("ornament", new("Ornament: a gold ring set with a diamond (Gold and Diamond ramps).",
            "hFFE28A lF2CC5E bD9AE3C mB8902E d8A6A1E wE8FFFF LB4EEF2 M7FD3DC S5FB4BE",
            [
                "................",
                "................",
                "......wwLM......",
                ".....wLLMMS.....",
                "......LMMS......",
                ".......MS.......",
                ".....hbllbm.....",
                "...hll....bbm...",
                "..hl........bm..",
                "..l..........m..",
                "..lb........bm..",
                "..mbb......bmd..",
                "...mmbb..bbmd...",
                ".....mmmmdd.....",
                "................",
                "................",
            ])),
        ("coin", new("Coin: a gold coin tilted to show its edge, with a raised rim and a small embossed star (Gold ramp).",
            "hFFE28A lF2CC5E bD9AE3C mB8902E d8A6A1E",
            [
                "................",
                "................",
                ".....hhhhhh.....",
                "...hhllllllhm...",
                "..hllbbbbbbllm..",
                "..hlbbbbhbbblm..",
                ".hlbbbbhlmbbblm.",
                ".hlbbbhlllmbblm.",
                ".hlbbbbmlmbbblm.",
                "..hlbbbbmbbblm..",
                "..mllbbbbbbllm..",
                "..dmmllllllmmd..",
                "...ddmmmmmmdd...",
                ".....dddddd.....",
                "................",
                "................",
            ])),
    ];

    private static readonly Dictionary<string, Drawing> ByKind =
        Drawings.ToDictionary(entry => entry.Kind, entry => entry.Art, StringComparer.Ordinal);

    /// <summary>Every item kind in the catalogue, drawn or kept, in sheet order.</summary>
    public static IReadOnlyList<string> Kinds => Drawings.Select(entry => entry.Kind).ToArray();

    /// <summary>
    /// The outlined 16 × 16 icon for <paramref name="kind"/>. Kinds this
    /// proposal keeps or does not list come from the game's current
    /// <see cref="ItemIcons.Render"/>, which shows its plain crate for an
    /// unknown kind.
    /// </summary>
    public static Image Icon(string kind)
    {
        if (!ByKind.TryGetValue(kind, out var art) || art.KeepsCurrent)
            return ItemIcons.Render(kind, Grid);
        CheckGrid(kind, art.Rows);
        try
        {
            return Bitmap.Outlined(Bitmap.Draw(art.Palette, art.Rows), Ink);
        }
        catch (ArgumentException problem)
        {
            throw new ArgumentException($"Icon '{kind}': {problem.Message}", problem);
        }
    }

    /// <summary>
    /// Throws unless the rows are 16 × 16 with an empty outer ring, so the
    /// outline always fits (the same rule as <see cref="ItemIcons.FitsGrid"/>).
    /// </summary>
    private static void CheckGrid(string kind, string[] rows)
    {
        if (rows.Length != Grid)
            throw new ArgumentException($"Icon '{kind}' has {rows.Length} rows, not {Grid}.");
        for (var y = 0; y < Grid; y++)
        {
            if (rows[y].Length != Grid)
                throw new ArgumentException($"Icon '{kind}' row {y} is {rows[y].Length} wide, not {Grid}.");
            var edgeRow = y == 0 || y == Grid - 1;
            if ((edgeRow && rows[y].Any(pixel => pixel != '.')) || rows[y][0] != '.' || rows[y][^1] != '.')
                throw new ArgumentException($"Icon '{kind}' row {y} touches the outer ring, which the outline needs.");
        }
    }

    /// <summary>One entry per item kind, new or kept, at its native 16 px; the review sheet scales it.</summary>
    public IEnumerable<Entry> Render()
    {
        foreach (var (kind, art) in Drawings)
            yield return new Entry(Family, kind, Icon(kind), art.Note);
    }

    /// <summary>Item icons do not appear in the reference scene, so nothing changes there.</summary>
    public void Apply(ArtSet set)
    {
    }
}
