using Godot;

namespace ClankerWorld.GodotClient.UI;

/// <summary>
/// Pixel-art icons for stored items. Each is drawn by hand on a 16 × 16 grid
/// in three or four shades, and gets a one-pixel outline all the way round
/// its silhouette, in a darker shade of whatever it borders, so the outline
/// is always complete. Icons scale only by whole numbers (16, 32, 48 px) so
/// they stay crisp. An item kind without its own icon yet (for example new
/// content) shows a plain crate, so it is still counted. The set is the
/// complete catalogue the owner approved in the art review, so many icons are
/// for agreed items the simulation does not make yet, such as milk, the
/// weapons, the handcart and the coin; they wait here until it does.
/// </summary>
public static class ItemIcons
{
    public const int Grid = 16;
    private const string Fallback = "crate";
    private static readonly Color Ink = new("2A1A10");
    private static readonly Dictionary<(string Kind, int Size), ImageTexture> Cache = [];
    private static readonly Dictionary<string, Image> Art = [];

    /// <summary>The handle every tool shares, in the tool-handle browns (light, shade).</summary>
    private const string Handle = "HC08448 D7A4E26";

    /// <summary>Worked iron for tool heads, the cool steel of the iron bar: glint, light, base, shade, dark.</summary>
    private const string Steel = "wEEF2F4 lBFC8CF m939CA5 d6A727B k50575E";

    /// <summary>Fiber cord lashing a wooden or stone head to its handle.</summary>
    private const string Cord = "cE6C77B CA98A45";

    /// <summary>A carved wooden tool head, the wooden tier: Timber highlight, light, base, shade.</summary>
    private const string WoodHead = "hD2AC77 lA77C52 m8A6440 d6E4E31";

    /// <summary>A knapped stone tool head, the stone tier: Rock highlight, light, base, shade.</summary>
    private const string StoneHead = "hA49C95 l8B837D m756D68 d625B56";

    /// <summary>Each row is one line of pixels; '.' is empty and every other letter is a palette colour.</summary>
    private sealed record Icon(string Palette, string[] Rows);

    private static readonly Dictionary<string, Icon> Icons = new(StringComparer.Ordinal)
    {
        // Drinking water, a drop so it never reads as the jug.
        ["water"] = new("wE8FFFF h8ABBD6 l6A9FC0 m598FB3 d4A7B9D",
        [
            "................",
            ".......hl.......",
            ".......hm.......",
            "......hllm......",
            "......hlmm......",
            ".....hllmmm.....",
            ".....hlmmmd.....",
            "....hllmmmmd....",
            "....hwlmmmmd....",
            "...hwllmmmmmd...",
            "...hwlmmmmmmd...",
            "...hwlmmmmmdd...",
            "...hlmmmmmmdd...",
            "....lmmmmmdd....",
            ".....dddddd.....",
            "................",
        ]),
        ["milk"] = new("PF4F8F6 pDCE5E0 qB8C6C4 hD2AC77 lA77C52 m8A6440 d6E4E31 k6A727B K50575E",
        [
            "................",
            "................",
            "................",
            "..hhhhhhhhhhhl..",
            ".hPPPPPPPPPPpqm.",
            ".hpPPPPPPPpppqm.",
            "..lqqqqqqqqqqm..",
            "..KkkkkkkkkkKK..",
            "..hPlllllllmmd..",
            "..hPllllllmmmd..",
            "...hllllllmmd...",
            "...KkkkkkkkKK...",
            "...hlllllmmmd...",
            "....dddddddd....",
            "................",
            "................",
        ]),
        ["wild_greens"] = new("h8DB660 v9BC66F b6C9A4B s557D3E g8DB660 G476B36",
        [
            "................",
            ".......h........",
            "......hvb.......",
            ".h....hvbs....s.",
            ".hh..hhvbs...bs.",
            ".hvb.hvvbs..bvs.",
            "..hvbhbvbs.bvbs.",
            "..hbvbhvbsbvbs..",
            "...hbvbvbbvbs...",
            "....hbvvvvbs....",
            ".....hbvvbs.....",
            "......gGGG......",
            ".......gG.......",
            ".......gG.......",
            "................",
            "................",
        ]),
        ["cultivated_greens"] = new("v9BC66F h8DB660 l6C9A4B b557D3E s476B36 cE8DCC0",
        [
            "................",
            "................",
            "................",
            "......hvvh......",
            "....hhvvvvhb....",
            "...hvvcvvcvbb...",
            "..hlhvvcvcvhbs..",
            ".hlhlvvvcvvhlbs.",
            ".hlhllhvvvhllbs.",
            ".lhlllhhhhllbbs.",
            ".hlbhllbllbllbs.",
            ".lb.lbllbblbs.s.",
            ".l...lbs.bs...s.",
            "................",
            "................",
            "................",
        ]),
        ["potato"] = new("wE3D6B5 hD2AC77 lA77C52 e8A6440",
        [
            "................",
            "................",
            "................",
            "...whhhh........",
            "..whhhhhhl......",
            ".whhehhhhhl.....",
            ".hhhhhhhehl.....",
            ".hhhhhhhhll.....",
            ".hheehhhhll.....",
            ".lhhhhhhll......",
            "..llhhll..hhh...",
            "...llll..whhhl..",
            ".........hhehll.",
            ".........lhhlll.",
            "..........llll..",
            "................",
        ]),
        ["grain"] = new("hF0DA9A lE6C77B bD2AE5E sA98A45 e6B5528 t8A6440 TA77C52 gD9AE3C GF0DA9A",
        [
            "................",
            ".l....l..l....l.",
            "..l....Gg....l..",
            "..G...GgGs...G..",
            ".GgG..gGgs..GgG.",
            ".gGgs.GgGs.GgGs.",
            ".GgGs.gGgs.gGgs.",
            "..gGs.GgGs.GgG..",
            "...gs..gs..gs...",
            "....b..bs..s....",
            ".....b.bs.s.....",
            ".....tTTTTt.....",
            "....bsbsbsbs....",
            "...bsbsbsbsbs...",
            "..bsbsbsbsbsbs..",
            "................",
        ]),
        ["flour"] = new("WF8F2E2 wE8DEC6 gCDBF9E GA89878 t8A5A30 sC8A060",
        [
            "................",
            "......ww.ww.....",
            ".......www......",
            "......ttttt.....",
            ".....wWWwwww....",
            "....wWWwwwwwg...",
            "...wWWwwwwwwgg..",
            "..wWwwwwwwwggg..",
            ".wwWwwwwwwwwggg.",
            ".wwwwwwwwwwwggg.",
            ".wwwwwwwwwwgggG.",
            ".gwwwwwwwwggggG.",
            "..ggggggggggGG..",
            "...GGGGGGGGGG...",
            "................",
            "................",
        ]),
        ["food"] = new("rC23A2A RE0584A hF8A08A d8A2418 s5E3A1E g6AA640 G3E6E28",
        [
            "................",
            "........s.gg....",
            "........sgGGg...",
            "...RRRR.srrrr...",
            "..RhhRRRrrrrrr..",
            ".RhhRRRrrrrrrrr.",
            ".RhRRRrrrrrrrrr.",
            ".RRRRrrrrrrrrrd.",
            ".RRRrrrrrrrrrrd.",
            ".RRrrrrrrrrrrdd.",
            ".rrrrrrrrrrrrdd.",
            "..rrrrrrrrrrdd..",
            "..rrrrrrrrrddd..",
            "...rrrr..rddd...",
            "................",
            "................",
        ]),
        // Orchard fruit, kept apart from foraged food.
        ["fruit"] = new("yC9C24E YDCD872 hF2EEB0 d8E8428 s5E3A1E g6AA640 G3E6E28",
        [
            "................",
            "........s.......",
            "........sgg.....",
            ".......yyGGg....",
            "......yYyyy.....",
            "......Yhyyy.....",
            ".....yYhyyyd....",
            "....yYhyyyyyd...",
            "...yYyyyyyyyyd..",
            "..yYyyyyyyyyydd.",
            "..Yhyyyyyyyyydd.",
            "..yyyyyyyyyyydd.",
            "..dyyyyyyyyyddd.",
            "...ddyyyyyyddd..",
            ".....ddddddd....",
            "................",
        ]),
        ["berries"] = new("m7E3A96 hC89AE6 lA060C0 d4E2262 g6AA640 G3E6E28 s5E3A1E",
        [
            "................",
            ".......gg.......",
            "......gGGg......",
            ".......s.s......",
            ".....lm...lm....",
            "....lhmm.lhmm...",
            "....mmmd.mmmd...",
            ".....dd...dd....",
            "...lm...lm......",
            "..lhmm.lhmm.lm..",
            "..mmmd.mmmdlhmm.",
            "...dd...dd.mmmd.",
            "............dd..",
            "................",
            "................",
            "................",
        ]),
        ["eggs"] = new("PFFF5DF pE8DCC0 qCABC99 QA09170 hF0DA9A lE6C77B bD2AE5E sA98A45 e6B5528",
        [
            "................",
            "................",
            "................",
            ".....PPp........",
            "....PPppq.......",
            "....Pppqq.PPp...",
            "...PPppqqPPppq..",
            "...Pppqqqpppqq..",
            "...PppqqQppqqQ..",
            ".hlbppqQbpqqQbs.",
            ".hlbsbsbsbsbsbs.",
            ".lbsbsbsbsbsbss.",
            "..sbsbsbsbsbss..",
            "...sesesesese...",
            "................",
            "................",
        ]),
        ["bread"] = new("cC07A34 CDC9C52 hF2C27E uF0DA9A d8A5222 k6A3C18",
        [
            "................",
            "................",
            "................",
            "................",
            "......CCCC......",
            "....CChhCCcc....",
            "...ChhhuCCCuc...",
            "..ChhCuCCCuCcc..",
            ".ChhCuCCCuCCccd.",
            ".cCCuCCCuCCcccd.",
            ".cCCCCCCCCCcccd.",
            ".cccccccccccccd.",
            "..cccccccccccdd.",
            "...kdddddddddk..",
            "................",
            "................",
        ]),
        ["porridge"] = new("RD2AC77 bA77C52 B8A6440 d6E4E31 cFFF5DF CE8DCC0 qCABC99 sD2AC77 SA77C52",
        [
            "................",
            "............sS..",
            "...........sS...",
            "..........sS....",
            ".....ccccsSc....",
            "...ccCCCsSCqq...",
            "..RcCCCCCCCqqR..",
            ".RcCCCqCCCCqqqR.",
            ".RCCCCCCCCqqqqR.",
            ".bRRRRRRRRRRRRB.",
            ".bbbbBBBBBBBBBd.",
            "..bbBBBBBBBBBd..",
            "...BBBBBBBBBd...",
            "....dBBBBBBd....",
            ".....dddddd.....",
            "................",
        ]),
        ["stew"] = new("REFA882 bD5825A BB8623C d8E4428 o8A6440 O6E4E31 yA77C52 pD2AC77 PE3D6B5 g8DB660 G557D3E",
        [
            "................",
            "................",
            "................",
            "................",
            "....RRRRRRRR....",
            "..RRyooPpooyRR..",
            ".RooPpoogGooOOR.",
            ".RyGgooooPpoOOR.",
            ".bRoooGgooOOORd.",
            "..bRRRRRRRRRRd..",
            ".bbBBBBBBBBBBdd.",
            ".dbbBBBBBBBBddd.",
            "..bbBBBBBBBBdd..",
            "...bBBBBBBBBd...",
            ".....dddddd.....",
            "................",
        ]),
        ["meal"] = new("PFFF5DF pE8DCC0 qCABC99 QA09170 wE3D6B5 hD2AC77 lA77C52 e8A6440 g8DB660 G6C9A4B k476B36",
        [
            "................",
            "................",
            "................",
            "................",
            "...gg...........",
            "..gGGg.whh......",
            ".gGkGgwhhhl.....",
            ".kgGkGhhhhe.wh..",
            "..kGkkhhhlewhhl.",
            ".PPPPPPlllehhll.",
            ".Ppppppppppppll.",
            ".qpppppppppppQQ.",
            "..qqqqqqqqqqQQ..",
            "....QQQQQQQQ....",
            "................",
            "................",
        ]),
        ["restaurant_meal"] = new("PFFF5DF pE8DCC0 B6A9FC0 N4A7B9D cC07A34 CDC9C52 uF0DA9A g8DB660 G6C9A4B k476B36",
        [
            "................",
            "................",
            "................",
            "...CCCC.........",
            "..CuuuuC........",
            "..CuuuuC..ggg...",
            "..CuuuuC.gGGgg..",
            "..CuuuuCgGkGGgk.",
            "..CuuuucGkGkGkk.",
            ".BCccccPPPPPPPB.",
            ".BppppppppppppB.",
            ".NBppppppppppBN.",
            "..NBBBBBBBBBBN..",
            "...NNNNNNNNNN...",
            "................",
            "................",
        ]),
        ["seed"] = new("lC8985E m9A6A3A d6A4222",
        [
            "................",
            "................",
            "...ll.....ll....",
            "..lmmm...lmmm...",
            "..mmmd...mmmd...",
            "..mmdd...mmdd...",
            "...dd.....dd....",
            "................",
            "......ll........",
            ".....lmmm...ll..",
            ".....mmmd..lmmm.",
            ".....mmdd..mmmd.",
            "......dd...mmdd.",
            "............dd..",
            "................",
            "................",
        ]),
        ["grain_seed"] = new("GF0DA9A gD9AE3C sB8902E d8A6A1E",
        [
            "................",
            "................",
            "................",
            "......Gg........",
            ".....Ggs...Gg...",
            ".....gss..Ggs...",
            "......s...gss...",
            "...Gg......s....",
            "..Ggs..Gg.......",
            "..gss.Ggs..Gg...",
            "...s..gss.Ggs...",
            ".......s..gss...",
            "...........s....",
            "................",
            "................",
            "................",
        ]),
        ["green_seed"] = new("h8DB660 l6C9A4B g476B36 sA77C52 d6E4E31",
        [
            "................",
            "................",
            "...hl....lg.....",
            "..hhll..llgg....",
            "..hlll.hllgg....",
            "...hlg.llg......",
            ".....gg.........",
            "......g.........",
            ".....sd.........",
            "..sd.dd...sd....",
            "..dd....sd.dd...",
            "........dd..sd..",
            "...sd.......dd..",
            "...dd...........",
            "................",
            "................",
        ]),
        ["orchard_seed"] = new("s5E3A1E yC9C24E YDCD872 pF2EEB0 PE8DCC0 q8E8428 k3F2A1A K6E4E31 hA77C52 g6AA640 G3E6E28",
        [
            "................",
            ".......s.gg.....",
            ".......sgGG.....",
            "......yYYq......",
            ".....yppPPq.....",
            ".....YpPPPq.....",
            "....yppKKPPq....",
            "...yppPhkPPPq...",
            "...YpKhKkKPPq...",
            "..yppkkPkkPPPq..",
            "..YpPPKkPPPPPq..",
            "..ypPPPPPPPPqq..",
            "..qPPPPPPPPPqq..",
            "...qqPPPPPPqq...",
            ".....qqqqqq.....",
            "................",
        ]),
        // A seed for planting a tree, kept apart from crop seed.
        ["tree_seed"] = new("C9C6E42 c7A5230 k553820 nC8904A NE4B272 d8E5E2C s4E3218",
        [
            "................",
            "........s.......",
            ".......ss.......",
            "....CCCCcccc....",
            "...CCcCcCcCcc...",
            "..CCcCcCcCcCck..",
            "..ccccccccccckk.",
            "...nNNnnnnnnd...",
            "...NNnnnnnnnd...",
            "...Nnnnnnnnnd...",
            "....nnnnnnndd...",
            "....nnnnnnndd...",
            ".....nnnnndd....",
            "......nnndd.....",
            ".......nd.......",
            "................",
        ]),
        ["wood"] = new("fE6C77B rD2AC77 cA77C52 lA77C52 m8A6440 b6E4E31",
        [
            "................",
            "................",
            "................",
            "....fffllllllll.",
            "...frrrfmmlmmmm.",
            "...frcrfbbmmmbb.",
            "...frrrfmmmbmmm.",
            "....fffbbbbbbbb.",
            "................",
            "..ffflllllllll..",
            ".frrrfmmmlmmmm..",
            ".frcrfbbmmmbbm..",
            ".frrrfmmbmmmmm..",
            "..fffbbbbbbbbb..",
            "................",
            "................",
        ]),
        ["stone"] = new("wEEF3F1 hC4C7C5 lAEB2B0 m8E8A85 d5F5955",
        [
            "................",
            "................",
            "......whhh......",
            "....whhhhhhm....",
            "...whhhhhhhhm...",
            "..whhhhhhhhmmm..",
            "..lllhhhhhdmmmd.",
            ".lllllllldmmmmd.",
            ".llllllldmmmmdd.",
            ".lllllldmmmmddd.",
            "..mllllmmmmdd...",
            "...mmmlmmddd.hl.",
            ".....mmmdd.hlmd.",
            "............lmd.",
            "................",
            "................",
        ]),
        ["clay"] = new("hEFA882 lD5825A mB8623C d8E4428 k6A3020",
        [
            "................",
            "................",
            "................",
            "....hhhhhhhh....",
            "...hllllllllh...",
            "..hllddlllllll..",
            "..lllllllddlll..",
            ".mllllllllllllm.",
            ".mmmmmmmmmmmmmm.",
            ".mmmmmmmmmmmmmd.",
            ".dmmmmmmmmmmmdd.",
            "..dddddddddddd..",
            "................",
            "................",
            "................",
            "................",
        ]),
        ["iron_ore"] = new("hA69E98 l8A827C m6C6560 d524C48 k3E3A37 oC8662E OF2A060",
        [
            "................",
            "................",
            "........hl......",
            "......hhOll.....",
            ".....hhoOlll....",
            "...hhhhhlloOm...",
            "..lhoOhllllmmm..",
            "..llhhlllommmmd.",
            ".llllOolllmmmmd.",
            ".llllllllmmoOdd.",
            ".mlloOllmmmmddd.",
            ".mmmlllmmOommdd.",
            "..mmmmmmmmmdddk.",
            "...mmmmmmdddkk..",
            ".....kkkkkkk....",
            "................",
        ]),
        ["iron"] = new("hEEF2F4 lBFC8CF m939CA5 d6A727B k50575E",
        [
            "................",
            "................",
            "......hhhh......",
            ".....hllllh.....",
            "....mmmmmmmm....",
            "....mhmmmmmd....",
            "....dddddddk....",
            "...hlllllllll...",
            "..hlllllllllll..",
            ".mmmmmmmmmmmmmd.",
            ".mhmmmmmmmmmmmd.",
            ".mmmmmmmmmmmmmd.",
            ".dddddddddddddk.",
            "................",
            "................",
            "................",
        ]),
        ["gold"] = new("hFFE28A lF2CC5E bD9AE3C mB8902E d8A6A1E",
        [
            "................",
            "................",
            "................",
            "................",
            "......hl........",
            "....hhlbm.hl....",
            "...hlhlbmhlbm...",
            "...llbbmmlbbmd..",
            "..hlbbmmdbbmmd..",
            ".hlhbmmd.mmdd...",
            ".lllbbmhllbm....",
            ".lbbmmhlhbbmd...",
            "..mmmdlbbbmmd...",
            "......mmmmdd....",
            "................",
            "................",
        ]),
        ["diamond"] = new("wE8FFFF lB4EEF2 m7FD3DC s5FB4BE",
        [
            "................",
            "................",
            "................",
            "....wwlllllm....",
            "...wllwwllmms...",
            "..wlllwllllmss..",
            ".mmmmmmmmmmssss.",
            "..lllmlllmmsss..",
            "...llmlllmsss...",
            "....lmllmmss....",
            ".....mlmmss.....",
            "......lmss......",
            ".......ms.......",
            "................",
            "................",
            "................",
        ]),
        ["fiber"] = new("hF0E0A0 lD8C47A mB8A458 d8E7C3E k6E5E2C",
        [
            "................",
            "................",
            "......llll......",
            "....llhhllmm....",
            "...lhhlldlmmm...",
            "..lhllddllmmmd..",
            "..llddllmmddmd..",
            ".llddllmmddmmdd.",
            ".lddllmmddmmddd.",
            ".llllmmddmmdddd.",
            ".mllmmddmmmdddd.",
            "..mmmddmmddddd..",
            "..mmddmmdddddd..",
            "...mmmddddddm...",
            ".....dddddd..mm.",
            "................",
        ]),
        ["cloth"] = new("hFFF5DF lE8DCC0 mCABC99 dA09170 k75674D",
        [
            "................",
            "................",
            "................",
            "....hhhhhhhhh...",
            "...hlllllllllm..",
            "..hlllllllllll..",
            ".hllllllllllllm.",
            ".hlllhllllllmmd.",
            ".hlllhlmmmmlmmd.",
            ".hlllhmmmmmlmmd.",
            ".hlllhlmmmmlmmd.",
            "..lllllmmllmmdd.",
            "...mmmmmmmmdddk.",
            "....ddddddddkk..",
            "................",
            "................",
        ]),
        ["wool"] = new("hFFF5DF lE8DCC0 mCABC99 dA09170",
        [
            "................",
            "................",
            "................",
            "....hh.hh.hh....",
            "...hllhllhllm...",
            "..hlhmlhmlhmlm..",
            ".hllmhllmhllmmd.",
            ".lhmlhmlhmlhmld.",
            ".hllmhllmhllmmd.",
            ".lhmlhmlhmlhmld.",
            "..lmmlmmlmmlmd..",
            "..mdmmdmmdmmdd..",
            "...d..d..d..d...",
            "................",
            "................",
            "................",
        ]),
        ["hide"] = new("hD2AC77 lA77C52 m8A6440 d6E4E31 cCABC99",
        [
            "................",
            "................",
            ".hl....hl....lm.",
            ".hll..hllm..lmd.",
            "..hllhlllmmlmd..",
            "...hllcccllmd...",
            "...hlcccccmmd...",
            "...llccccclmd...",
            "...lmcccccmmd...",
            "...lmmcccmmmd...",
            "..lmmmmmmmmmdd..",
            ".lmd.mmmmmd.mdd.",
            ".md...mmdd...dd.",
            ".......dd.......",
            "................",
            "................",
        ]),
        ["leather"] = new("hE0A070 lC98A5A bB7774C mA9643C d7A4426",
        [
            "................",
            "................",
            "................",
            ".......lll.lll..",
            ".....llbbblbbbm.",
            "....lbhbhbhbhbm.",
            "....lbbbbbbbbhm.",
            "...lhbbbbbbbbbm.",
            "...lbbbbbbbbbhm.",
            "..lhbbbbbbbbbm..",
            "..lbbbbbbbbbhm..",
            ".lhbbbbbbbbbmm..",
            ".lbhbhbhbhbmhl..",
            ".mmm.mmmmmmmld..",
            "................",
            "................",
        ]),
        ["wooden_axe"] = new(Handle + " " + Cord + " " + WoodHead,
        [
            "................",
            ".hh......HD.....",
            ".hlll....HD.....",
            ".hllllllcCcC....",
            ".hlllmmmCcCc....",
            ".hlmmmmmcCcC....",
            ".hmmdddmCcCc....",
            ".mmd.....HD.....",
            ".dd......HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........DD.....",
            "................",
        ]),
        ["stone_axe"] = new(Handle + " " + Cord + " " + StoneHead,
        [
            "................",
            "..hh.....HD.....",
            ".hhll....HD.....",
            ".hlhllmmcCcC....",
            ".hllmlmmCcCc....",
            ".lhlmmdmcCcC....",
            ".lmmdmddCcCc....",
            ".mmdd....HD.....",
            "..dd.....HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........DD.....",
            "................",
        ]),
        ["iron_axe"] = new(Handle + " " + Steel,
        [
            "................",
            "..ll.....HD.....",
            ".wllll..lmmd....",
            ".wllmmmmlwmdd...",
            ".wlmmmmmlmmdd...",
            ".wlmmdddlmmdd...",
            ".wmmdd..lmmd....",
            ".wmdd....HD.....",
            "..dd.....HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........DD.....",
            "................",
        ]),
        ["wooden_pickaxe"] = new(Handle + " " + Cord + " " + WoodHead,
        [
            "................",
            ".......HD.......",
            "...hhlcCcCmmd...",
            "..hllmCcCcmmdd..",
            ".hlm..cCcC..mdd.",
            ".hl....HD....dd.",
            ".l.....HD.....d.",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......DD.......",
            "................",
        ]),
        ["stone_pickaxe"] = new(Handle + " " + Cord + " " + StoneHead,
        [
            "................",
            ".......HD.......",
            "...hhlcCcCmmd...",
            "..hllmCcCcmmdd..",
            ".hlm..cCcC..mdd.",
            ".hl....HD....dd.",
            ".l.....HD.....d.",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......DD.......",
            "................",
        ]),
        ["iron_pickaxe"] = new(Handle + " " + Steel,
        [
            "................",
            ".......HD.......",
            "...wlllwmmmmd...",
            "..wllmlwmmmmdd..",
            ".wlm..lmmd..mdd.",
            ".wl....HD....dd.",
            ".l.....HD.....d.",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......DD.......",
            "................",
        ]),
        ["wooden_hoe"] = new(Handle + " " + Cord + " " + WoodHead + " eF0DA9A",
        [
            "................",
            "..........HD....",
            "....hhhhhcCcC...",
            "...hllllmCcCc...",
            "..ehlm...cCcC...",
            "..ehhl....HD....",
            ".ehhll....HD....",
            ".ehhlm....HD....",
            ".ehllm....HD....",
            ".edddd....HD....",
            "..........HD....",
            "..........HD....",
            "..........HD....",
            "..........HD....",
            "..........DD....",
            "................",
        ]),
        ["iron_hoe"] = new(Handle + " " + Steel,
        [
            "................",
            "..........HD....",
            "...lllllllmmd...",
            "..wlllmmmlmmdd..",
            "..wllm...lmmd...",
            "..wlmm....HD....",
            ".wllmd....HD....",
            ".wlmmd....HD....",
            ".wmddd....HD....",
            ".dddd.....HD....",
            "..........HD....",
            "..........HD....",
            "..........HD....",
            "..........HD....",
            "..........DD....",
            "................",
        ]),
        ["sickle"] = new(Handle + " " + Steel,
        [
            "................",
            ".....mmmmm......",
            "...mmwlllmmd....",
            "..mlw.....lmd...",
            ".mlw.......lmd..",
            ".mw........lmd..",
            ".mw........lmd..",
            "..w........lmd..",
            "...........lmd..",
            "..........kmmk..",
            "...........HD...",
            "...........HD...",
            "...........HD...",
            "...........HD...",
            "...........DD...",
            "................",
        ]),
        ["hammer"] = new(Handle + " " + Cord + " " + StoneHead,
        [
            "................",
            "................",
            "...hhhhhhhhhl...",
            "..hhllllllllmd..",
            "..hlllllllllmd..",
            "..lmmmmmmmmmmd..",
            "...dddcCcCddd...",
            "......CcCc......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......DD.......",
            "................",
        ]),
        ["knife"] = new(Handle + " " + Steel + " rE6C77B",
        [
            "................",
            "................",
            "..wm............",
            ".wllm...........",
            ".wlllm..........",
            "..wllmd.........",
            "...wllmd........",
            "....wllmd.......",
            ".....wlmmk......",
            "......dmkHH.....",
            ".........HrHD...",
            "..........HHDD..",
            "...........HDDD.",
            "............DDD.",
            ".............D..",
            "................",
        ]),
        ["tool"] = new(Handle + " " + Steel + " aD2AC77 bA77C52 e8A6440 f6E4E31",
        [
            "................",
            "..aab......wl...",
            ".abbef....wllm..",
            ".abeef....lmmd..",
            "..effHD..HD.d...",
            "......HDHD......",
            ".......HD.......",
            "......HDHD......",
            ".....HD..HD.....",
            "....HD....HD....",
            "...HD......HD...",
            "..HD........HD..",
            ".DD..........DD.",
            "................",
            "................",
            "................",
        ]),
        ["spear"] = new(Handle + " " + Steel,
        [
            "................",
            ".......wl.......",
            "......wllm......",
            ".....wlllmd.....",
            ".....wllmmd.....",
            ".....wlmmmd.....",
            "......wlmd......",
            ".......md.......",
            "......kmmk......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......DD.......",
            "................",
        ]),
        ["sword"] = new(Steel + " " + Handle,
        [
            "................",
            ".............w..",
            "............wlm.",
            "...........wlmd.",
            "..........wlmd..",
            ".........wlmd...",
            "........wlmd....",
            "...k...wlmd.....",
            "....k.wlmd......",
            ".....kmmd.......",
            "....HDkm........",
            "...HD..k........",
            "..HD....k.......",
            ".kk.............",
            ".kk.............",
            "................",
        ]),
        ["shield"] = new(Steel + " hD2AC77 aA77C52 b8A6440 s6E4E31",
        [
            "................",
            "................",
            "..llllllllllmd..",
            "..lhhaahhaabsd..",
            "..lhaabhaabbsd..",
            "..lhaabwlabbsd..",
            "..lhaabmdabbsd..",
            "..lhaabhaabbsd..",
            "..lhaabhaabbsd..",
            "...lhabhaabsd...",
            "...lhabhaabsd...",
            "....lbhaabsd....",
            ".....lhabsd.....",
            "......lmdd......",
            "................",
            "................",
        ]),
        ["armor"] = new(Steel + " tA77C52 T6E4E31",
        [
            "................",
            "................",
            "..wll......lmd..",
            ".wlllt....tmmdd.",
            ".wllmlt..tlmmdd.",
            ".lllmmlllllmmdd.",
            "..ddwllllllmdd..",
            "....wllllllmd...",
            "....wlllmllmd...",
            "....lllmlmmmd...",
            "....TTTTTTTTT...",
            "...wllmlmlmmdd..",
            "...lmdlmdlmddd..",
            "...ddddddddddd..",
            "................",
            "................",
        ]),
        ["rope"] = new("hD2AC77 mA77C52 d8A6440 fE6C77B",
        [
            "................",
            ".....mhhmhh.....",
            "...hmhhmhhmhh...",
            "..hmh......hdm..",
            "..mh..hhmh..mm..",
            ".mh..hhmhhd..dm.",
            ".hh.hhm..dmm.mm.",
            ".hm.hm....md.md.",
            ".mh.mhh..mdm.dm.",
            ".hh..hdmmdm..mm.",
            "..mh..mmdm..mm..",
            "..hhd......mmd..",
            "...dmmdmmdmmd...",
            ".....dmmdmmdmm..",
            "............mhf.",
            "................",
        ]),
        ["basket"] = new("hF0DA9A lE6C77B bD2AE5E sA98A45 e6B5528",
        [
            "................",
            ".....hlllls.....",
            "....hl....bs....",
            "...hl......bs...",
            "...hl......bs...",
            "...hl......bs...",
            ".hhllllllllllls.",
            ".lsssssssssssse.",
            ".llbbllbbllbbse.",
            "..bbllbbllbbse..",
            "..llbbllbbllse..",
            "..bbllbbllbbse..",
            "...llbbllbbse...",
            "....eeeeeeee....",
            "................",
            "................",
        ]),
        ["sack"] = new("hE8DCC0 lCABC99 mA09170 d75674D tD2AC77 TA77C52 R8A6440",
        [
            "................",
            ".....hll.lm.....",
            "......lmlm......",
            ".....tTTTTR.....",
            "......lllm.R....",
            ".....hllllm.R...",
            "....hlllmllm....",
            "...hllllllmmd...",
            "...hlmllllmmd...",
            "..hllllllmlmmd..",
            "..hllmllllmmmd..",
            "..lllllmllmmmd..",
            "..mllllllmmmdd..",
            "...mmmmmmmmdd...",
            "................",
            "................",
        ]),
        ["handcart"] = new("hD2AC77 lA77C52 m8A6440 d6E4E31 K6A727B",
        [
            "................",
            "................",
            "................",
            ".h..............",
            ".hhhhhhhhhh.....",
            ".hllllllllm.....",
            ".hlmllmllmm.....",
            ".hlmllmllmmhhhh.",
            ".lmmmmmmmmmmmmd.",
            ".ddKKKKKddd...d.",
            "..K..l..K.......",
            ".K...l...K......",
            ".KlllllllK......",
            ".K...l...K......",
            "..K..l..K.......",
            "................",
        ]),
        ["clay_pot"] = new("hEFA882 lD5825A bB8623C s8E4428 d6A3020",
        [
            "................",
            "................",
            ".......hl.......",
            ".....hhllbb.....",
            "....ssssssss....",
            ".....hllllb.....",
            "...hhllllllbb...",
            "..hllllllllbbs..",
            ".hlllllllllbbbs.",
            ".lddsddsddsddds.",
            ".llllllllllbbbs.",
            "..lllllllbbbbs..",
            "...bbbbbbbbss...",
            "....ssssssss....",
            "................",
            "................",
        ]),
        ["water_jug"] = new("hEFA882 lD5825A bB8623C s8E4428 w7FB4CF",
        [
            "................",
            "....hhhhhh......",
            "....hwwwwb......",
            ".....lbbs.......",
            ".....lbbsbllb...",
            "....hlbbbs..lb..",
            "...hlbbbbbs..lb.",
            "..hlbbbbbbbs.ls.",
            "..lbbbbbbbbbbs..",
            "..lbbbbbbbbbs...",
            "..lbbbbbbbbbs...",
            "..bbbbbbbbbbs...",
            "...bbbbbbbbs....",
            "....sssssss.....",
            "................",
            "................",
        ]),
        ["clothing"] = new("b4A6E9E B6C92C4 h92B4DE d32507E k263E62 t7A4E2A TC09A5A",
        [
            "................",
            "................",
            "....bBhkkBbb....",
            "..bBhhBhkBBBbd..",
            ".bBhhBBBBBBBBbd.",
            ".bhBBBBBBBBBbbd.",
            ".BhBBBBBBBBBbdd.",
            ".ddbhBBBBBBbbdd.",
            "....hBBBBBbd....",
            "....tttTTttt....",
            "....hBBBBBbd....",
            "....hBBBBBbd....",
            "...hBBBBBBBbd...",
            "...dddddddddd...",
            "................",
            "................",
        ]),
        ["cold_clothing"] = new("hD2AC77 lA77C52 m8A6440 d6E4E31 FFFF5DF fE8DCC0 gCABC99 tC09A5A",
        [
            "................",
            "....FfF..FfF....",
            "...FfffFFfffg...",
            "..hFfggffggfgd..",
            ".hlhFfgllgfgmmd.",
            ".hlhlFfllfgmmmd.",
            ".hlhllFffglmmmd.",
            ".FfhllltlmlmmFg.",
            ".fglllllllmmmfg.",
            "...hllllltmmd...",
            "...hllllllmmd...",
            "...hllllltmmd...",
            "...hllllllmmd...",
            "...FfFfFfFfgg...",
            "................",
            "................",
        ]),
        ["wet_clothing"] = new("hA8B4A2 l8E9B88 m6F7C6A s566150 d30372D w8ABBD6 W598FB3",
        [
            "................",
            "..w.............",
            ".wW...hhll...w..",
            ".W...hlllmm.wW..",
            ".....hlddsm.W...",
            ".....hldddm.....",
            "....hhlsssmm....",
            "....hllllmmm....",
            "...hlllsllmms...",
            "...hllsllllms...",
            "..hlllsllsllms..",
            "..hllsllllslms..",
            ".hlllsllllsllms.",
            ".sssssssssssssd.",
            "................",
            "................",
        ]),
        ["herbs"] = new("f86B89A l5E9278 m3F7358 d2F5B45 pC8A8D4 P8F6A9E cE6C77B CA98A45 s6E4E31",
        [
            "................",
            ".........pP.....",
            "....pP...Pf..pP.",
            "....Pf..flm..Pf.",
            "...flm.fflm.flm.",
            "...ffmlflmmflmd.",
            "....flmflmmlmd..",
            "....lmdlmdlmd...",
            ".....lmmdmmd....",
            "......cCcCd.....",
            "......CcCc......",
            ".....s.ss.......",
            "....s..s.s......",
            "...s...s..s.....",
            "................",
            "................",
        ]),
        ["bandage"] = new("hFFF5DF lE8DCC0 mCABC99 dA09170",
        [
            "................",
            "................",
            "................",
            ".....hhhh.......",
            "...hhllllhm.....",
            "..hlldddllmm....",
            "..hldlllldmm....",
            ".hldlhhdldlmm...",
            ".hldlhddldlmm...",
            ".hlldllldllmhhh.",
            "..hlldddllmmlll.",
            "..lllllllmmllmd.",
            "...mmmmmmmlllmd.",
            ".........mmmmd..",
            "................",
            "................",
        ]),
        ["medicine"] = new("cA77C52 C6E4E31 gDCE5E0 GB8C6C4 rC4474B RA33A3F pF08A8A LE8DCC0 x557D3E",
        [
            "................",
            "......cccc......",
            "......cCCC......",
            ".......gG.......",
            "......ggGG......",
            ".....gprrRG.....",
            "....gprrrrRG....",
            "...gprrrrrrRG...",
            "...grLLxLLrRG...",
            "...grLxxxLrRG...",
            "...grLLxLLrRG...",
            "...grrrrrrRRG...",
            "....GrrrrRRG....",
            ".....GGGGGG.....",
            "................",
            "................",
        ]),
        ["paper"] = new("hF4F8F6 lDCE5E0 mCCD7D1 sB8C6C4 d9AAAA8",
        [
            "................",
            "................",
            "....hhhhhhhs....",
            "....hllllllds...",
            "..mmhlllllldds..",
            "..mmhllllllllm..",
            "..mmhllllllllm..",
            "..mmhllllllllm..",
            "..mmhllllllllm..",
            "..mmhllllllllm..",
            "..mmhllllllllm..",
            "..mmhllllllllm..",
            "..mmlmmmmmmmmm..",
            "..sssssssssss...",
            "................",
            "................",
        ]),
        // A field map: knowledge of several sites, drawn as a folded map.
        ["field_map"] = new("hE3D6B5 lC8B78C bBAA77B sA08F66 g6FA069 G527F4F w4786AB rC4474B",
        [
            "................",
            "................",
            ".hhhhh.....hhhh.",
            ".hhgghlllllhhhh.",
            ".hgGGhbbbbbhrhh.",
            ".hgggwwbbbblrhh.",
            ".hhhhlbwwbbhrhh.",
            ".hrhhlbbbwwhrhh.",
            ".hhrrlrrbbbwwwh.",
            ".hhhhlbbrrrhhrh.",
            ".hhhhlbbbbbhrhr.",
            ".hhhhlbbbbbhhhh.",
            ".sssssbbbbbssss.",
            "......sssss.....",
            "................",
            "................",
        ]),
        // A field record: knowledge of one site, drawn as a sealed scroll.
        ["field_record"] = new("hE3D6B5 lC8B78C bBAA77B sA08F66 d7E6E4A tA77C52 rC4474B RA33A3F pF08A8A",
        [
            "................",
            "................",
            "..hhhhhhhhhhhl..",
            ".hllllllllllbbs.",
            "..sssssssssssd..",
            "...hhhhhhhhhs...",
            "...htttthtttb...",
            "...hhhhhhhhhs...",
            "...httthttttb...",
            "...hhhhhhhhhs...",
            "...htthttpRhb...",
            "..hhhhhhprRls...",
            ".hlllllllRRbbs..",
            "..sssssssr.r....",
            "................",
            "................",
        ]),
        ["book"] = new("RF08A8A rC4474B sA33A3F e7A2A2E pFFF5DF PCABC99 GF2CC5E",
        [
            "................",
            "................",
            "...RRRRRRRRRR...",
            "..eRrrrrrrrrrs..",
            "..eRrrrrrrrrrsp.",
            "..eRrrrGGrrrrsp.",
            "..eRrrGrrGrrrsp.",
            "..eRrrrGGrrrrsp.",
            "..eRrrrrrrrrrsp.",
            "..eRrrrrrrrrrsp.",
            "..eRrrrrrrrrrsp.",
            "..essssssssssPp.",
            "...pppppppppppP.",
            "....PPPPPPPPPP..",
            "................",
            "................",
        ]),
        ["ornament"] = new("hFFE28A lF2CC5E bD9AE3C mB8902E d8A6A1E wE8FFFF LB4EEF2 M7FD3DC S5FB4BE",
        [
            "................",
            "................",
            "......wwLM......",
            ".....wLLMMS.....",
            "......LMMS......",
            ".......MS.......",
            ".....hbllbm.....",
            "...hll....bbm...",
            "..hl........bm..",
            "..l..........m..",
            "..lb........bm..",
            "..mbb......bmd..",
            "...mmbb..bbmd...",
            ".....mmmmdd.....",
            "................",
            "................",
        ]),
        ["coin"] = new("hFFE28A lF2CC5E bD9AE3C mB8902E d8A6A1E",
        [
            "................",
            "................",
            ".....hhhhhh.....",
            "...hhllllllhm...",
            "..hllbbbbbbllm..",
            "..hlbbbbhbbblm..",
            ".hlbbbbhlmbbblm.",
            ".hlbbbhlllmbblm.",
            ".hlbbbbmlmbbblm.",
            "..hlbbbbmbbblm..",
            "..mllbbbbbbllm..",
            "..dmmllllllmmd..",
            "...ddmmmmmmdd...",
            ".....dddddd.....",
            "................",
            "................",
        ]),
        ["crate"] = new("wB07A42 WD09A5A d7A4E26",
        [
            "................",
            "................",
            ".WWWWWWWWWWWWWW.",
            ".WddwwwwwwwwwdW.",
            ".WwddwwwwwwwwwW.",
            ".WwwddwwwwwwwwW.",
            ".WwwwddwwwwwwwW.",
            ".WWWWWWWWWWWWWW.",
            ".WwwwwwwddwwwwW.",
            ".WwwwwwwwddwwwW.",
            ".WwwwwwwwwddwwW.",
            ".WwwwwwwwwwddwW.",
            ".WdwwwwwwwwwddW.",
            ".dddddddddddddd.",
            "................",
            "................",
        ]),
    };

    /// <summary>
    /// Simulation item kinds shown with an approved icon kept under the art
    /// review's name: the storage pot is the approved clay pot, and fresh
    /// water carried in a jug is the approved water.
    /// </summary>
    private static readonly Dictionary<string, string> DrawnAs = new(StringComparer.Ordinal)
    {
        ["storage_pot"] = "clay_pot",
        ["fresh_water"] = "water",
    };

    private static string Drawing(string kind) => DrawnAs.GetValueOrDefault(kind, kind);

    /// <summary>The item kinds that have their own icon.</summary>
    public static IReadOnlyCollection<string> Kinds => Icons.Keys.Where(kind => kind != Fallback).ToArray();

    /// <summary>Whether this kind has its own icon rather than the crate.</summary>
    public static bool Has(string kind) => kind != Fallback && Icons.ContainsKey(Drawing(kind));

    public static ImageTexture Texture(string kind, int size)
    {
        var key = (kind, size);
        if (Cache.TryGetValue(key, out var cached)) return cached;
        var texture = ImageTexture.CreateFromImage(Render(kind, size));
        Cache[key] = texture;
        return texture;
    }

    /// <summary>
    /// The icon at the largest whole-number scale that fits <paramref name="size"/>,
    /// centred on a transparent square of that size.
    /// </summary>
    public static Image Render(string kind, int size)
    {
        var art = OutlinedArt(Icons.ContainsKey(Drawing(kind)) ? Drawing(kind) : Fallback);
        var scale = Math.Max(1, size / Grid);
        var offset = (size - Grid * scale) / 2;
        var image = Image.CreateEmpty(size, size, false, Image.Format.Rgba8);
        image.Fill(Colors.Transparent);
        for (var y = 0; y < Grid; y++)
            for (var x = 0; x < Grid; x++)
            {
                var color = art.GetPixel(x, y);
                if (color.A > 0) image.FillRect(new Rect2I(offset + x * scale, offset + y * scale, scale, scale), color);
            }
        return image;
    }

    /// <summary>The 16 × 16 art with its outline, drawn once per kind.</summary>
    public static Image OutlinedArt(string kind)
    {
        if (Art.TryGetValue(kind, out var cached)) return cached;
        var icon = Icons[kind];
        var palette = icon.Palette.Split(' ').ToDictionary(entry => entry[0], entry => new Color(entry[1..]));
        var fill = new Color?[Grid, Grid];
        for (var y = 0; y < Grid; y++)
            for (var x = 0; x < Grid; x++)
                if (icon.Rows[y][x] is not '.' and var key) fill[x, y] = palette[key];
        var image = Image.CreateEmpty(Grid, Grid, false, Image.Format.Rgba8);
        image.Fill(Colors.Transparent);
        for (var y = 0; y < Grid; y++)
            for (var x = 0; x < Grid; x++)
            {
                if (fill[x, y] is { } color)
                {
                    image.SetPixel(x, y, color);
                    continue;
                }
                // An empty pixel beside the silhouette becomes outline, in a
                // dark shade of the darkest colour it touches.
                Color? darkest = null;
                foreach (var (dx, dy) in new[] { (1, 0), (-1, 0), (0, 1), (0, -1) })
                    if (x + dx is >= 0 and < Grid && y + dy is >= 0 and < Grid && fill[x + dx, y + dy] is { } near &&
                        (darkest is null || near.Luminance < darkest.Value.Luminance))
                        darkest = near;
                if (darkest is { } edge) image.SetPixel(x, y, Snapped((edge * 0.42f).Lerp(Ink, 0.45f) with { A = 1 }));
            }
        Art[kind] = image;
        return image;
    }

    /// <summary>
    /// A mixed colour on the nearest of the 8-bit steps an image stores. Godot
    /// truncates a channel when it stores it, so the outline is snapped first
    /// to keep the game's pixels exactly as drawn.
    /// </summary>
    private static Color Snapped(Color color) => new(Step(color.R), Step(color.G), Step(color.B), Step(color.A));

    private static float Step(float channel) => Math.Clamp(MathF.Round(channel * 255f), 0f, 255f) / 255f;

    /// <summary>Whether every row is 16 wide and no pixel touches the edge, so the outline fits.</summary>
    public static bool FitsGrid(string kind) => Icons.TryGetValue(kind, out var icon) && icon.Rows.Length == Grid &&
        icon.Rows.All(row => row.Length == Grid) &&
        icon.Rows[0].All(pixel => pixel == '.') && icon.Rows[^1].All(pixel => pixel == '.') &&
        icon.Rows.All(row => row[0] == '.' && row[^1] == '.');
}
