using Godot;

namespace ClankerWorld.GodotClient.UI;

/// <summary>
/// Pixel-art icons for stored items. Each is drawn by hand on a 16 × 16 grid
/// in three or four shades, and gets a one-pixel outline all the way round
/// its silhouette, in a darker shade of whatever it borders, so the outline
/// is always complete. Icons scale only by whole numbers (16, 32, 48 px) so
/// they stay crisp. An item kind without its own icon yet (for example new
/// content) shows a plain crate, so it is still counted. Some icons are for
/// agreed items the simulation does not make yet, such as the stone and iron
/// tools, rope, medicine and the coin; they wait here until it does.
/// </summary>
public static class ItemIcons
{
    public const int Grid = 16;
    private const string Fallback = "crate";
    private static readonly Color Ink = new("2A1A10");
    private static readonly Dictionary<(string Kind, int Size), ImageTexture> Cache = [];
    private static readonly Dictionary<string, Image> Art = [];

    /// <summary>The handle every newer tool shares, in today's tool-handle browns (light, shade).</summary>
    private const string Handle = "HC08448 D7A4E26";

    /// <summary>Worked iron for tool heads, the cool steel of the iron bar: glint, light, base, shade, dark.</summary>
    private const string Steel = "wEEF2F4 lBFC8CF m939CA5 d6A727B k50575E";

    /// <summary>Fiber cord lashing a wooden or stone head to its handle.</summary>
    private const string Cord = "cE6C77B CA98A45";

    /// <summary>Each row is one line of pixels; '.' is empty and every other letter is a palette colour.</summary>
    private sealed record Icon(string Palette, string[] Rows);

    private static readonly Dictionary<string, Icon> Icons = new(StringComparer.Ordinal)
    {
        ["wood"] = new("fE6C77B rD2AC77 cA77C52 lA77C52 m8A6440 b6E4E31",
        [
            "................",
            "................",
            "................",
            "....fffllllllll.",
            "...frrrfmmlmmmm.",
            "...frcrfbbmmmbb.",
            "...frrrfmmmbmmm.",
            "....fffbbbbbbbb.",
            "................",
            "..ffflllllllll..",
            ".frrrfmmmlmmmm..",
            ".frcrfbbmmmbbm..",
            ".frrrfmmbmmmmm..",
            "..fffbbbbbbbbb..",
            "................",
            "................",
        ]),
        ["stone"] = new("wEEF3F1 hC4C7C5 lAEB2B0 m8E8A85 d5F5955",
        [
            "................",
            "................",
            "......whhh......",
            "....whhhhhhm....",
            "...whhhhhhhhm...",
            "..whhhhhhhhmmm..",
            "..lllhhhhhdmmmd.",
            ".lllllllldmmmmd.",
            ".llllllldmmmmdd.",
            ".lllllldmmmmddd.",
            "..mllllmmmmdd...",
            "...mmmlmmddd.hl.",
            ".....mmmdd.hlmd.",
            "............lmd.",
            "................",
            "................",
        ]),
        ["clay"] = new("hEFA882 lD5825A mB8623C d8E4428 k6A3020",
        [
            "................",
            "................",
            "................",
            "....hhhhhhhh....",
            "...hllllllllh...",
            "..hllddlllllll..",
            "..lllllllddlll..",
            ".mllllllllllllm.",
            ".mmmmmmmmmmmmmm.",
            ".mmmmmmmmmmmmmd.",
            ".dmmmmmmmmmmmdd.",
            "..dddddddddddd..",
            "................",
            "................",
            "................",
            "................",
        ]),
        ["iron_ore"] = new("hA69E98 l8A827C m6C6560 d524C48 k3E3A37 oC8662E OF2A060",
        [
            "................",
            "................",
            "........hl......",
            "......hhOll.....",
            ".....hhoOlll....",
            "...hhhhhlloOm...",
            "..lhoOhllllmmm..",
            "..llhhlllommmmd.",
            ".llllOolllmmmmd.",
            ".llllllllmmoOdd.",
            ".mlloOllmmmmddd.",
            ".mmmlllmmOommdd.",
            "..mmmmmmmmmdddk.",
            "...mmmmmmdddkk..",
            ".....kkkkkkk....",
            "................",
        ]),
        ["iron"] = new("hEEF2F4 lBFC8CF m939CA5 d6A727B k50575E",
        [
            "................",
            "................",
            "......hhhh......",
            ".....hllllh.....",
            "....mmmmmmmm....",
            "....mhmmmmmd....",
            "....dddddddk....",
            "...hlllllllll...",
            "..hlllllllllll..",
            ".mmmmmmmmmmmmmd.",
            ".mhmmmmmmmmmmmd.",
            ".mmmmmmmmmmmmmd.",
            ".dddddddddddddk.",
            "................",
            "................",
            "................",
        ]),
        ["diamond"] = new("wE8FFFF lB4EEF2 m7FD3DC s5FB4BE",
        [
            "................",
            "................",
            "................",
            "....wwlllllm....",
            "...wllwwllmms...",
            "..wlllwllllmss..",
            ".mmmmmmmmmmssss.",
            "..lllmlllmmsss..",
            "...llmlllmsss...",
            "....lmllmmss....",
            ".....mlmmss.....",
            "......lmss......",
            ".......ms.......",
            "................",
            "................",
            "................",
        ]),
        ["fiber"] = new("hF0E0A0 lD8C47A mB8A458 d8E7C3E k6E5E2C",
        [
            "................",
            "................",
            "......llll......",
            "....llhhllmm....",
            "...lhhlldlmmm...",
            "..lhllddllmmmd..",
            "..llddllmmddmd..",
            ".llddllmmddmmdd.",
            ".lddllmmddmmddd.",
            ".llllmmddmmdddd.",
            ".mllmmddmmmdddd.",
            "..mmmddmmddddd..",
            "..mmddmmdddddd..",
            "...mmmddddddm...",
            ".....dddddd..mm.",
            "................",
        ]),
        ["rope"] = new("hD2AC77 mA77C52 d8A6440 fE6C77B",
        [
            "................",
            ".....mhhmhh.....",
            "...hmhhmhhmhh...",
            "..hmh......hdm..",
            "..mh..hhmh..mm..",
            ".mh..hhmhhd..dm.",
            ".hh.hhm..dmm.mm.",
            ".hm.hm....md.md.",
            ".mh.mhh..mdm.dm.",
            ".hh..hdmmdm..mm.",
            "..mh..mmdm..mm..",
            "..hhd......mmd..",
            "...dmmdmmdmmd...",
            ".....dmmdmmdmm..",
            "............mhf.",
            "................",
        ]),
        ["grain"] = new("eE2B64A EF6D882 sB8963E S8A6E2C t7A4E2A",
        [
            "................",
            ".......E........",
            "......eEe.......",
            "...E..EeE..E....",
            "..eEe.eEe.eEe...",
            "..EeE.EeE.EeE...",
            "..eEe..s..eEe...",
            "..EeE..s..EeE...",
            "...s...s...s....",
            "....s..s..s.....",
            ".....s.s.s......",
            "......sss.......",
            ".....ttttt......",
            "......sSs.......",
            ".....s.S.s......",
            "................",
        ]),
        ["flour"] = new("WF8F2E2 wE8DEC6 gCDBF9E GA89878 t8A5A30 sC8A060",
        [
            "................",
            "......ww.ww.....",
            ".......www......",
            "......ttttt.....",
            ".....wWWwwww....",
            "....wWWwwwwwg...",
            "...wWWwwwwwwgg..",
            "..wWwwwwwwwggg..",
            ".wwWwwwwwwwwggg.",
            ".wwwwwwwwwwwggg.",
            ".wwwwwwwwwwgggG.",
            ".gwwwwwwwwggggG.",
            "..ggggggggggGG..",
            "...GGGGGGGGGG...",
            "................",
            "................",
        ]),
        ["seed"] = new("lC8985E m9A6A3A d6A4222",
        [
            "................",
            "................",
            "...ll.....ll....",
            "..lmmm...lmmm...",
            "..mmmd...mmmd...",
            "..mmdd...mmdd...",
            "...dd.....dd....",
            "................",
            "......ll........",
            ".....lmmm...ll..",
            ".....mmmd..lmmm.",
            ".....mmdd..mmmd.",
            "......dd...mmdd.",
            "............dd..",
            "................",
            "................",
        ]),
        // A seed for planting a tree, kept apart from crop seed.
        ["tree_seed"] = new("C9C6E42 c7A5230 k553820 nC8904A NE4B272 d8E5E2C s4E3218",
        [
            "................",
            "........s.......",
            ".......ss.......",
            "....CCCCcccc....",
            "...CCcCcCcCcc...",
            "..CCcCcCcCcCck..",
            "..ccccccccccckk.",
            "...nNNnnnnnnd...",
            "...NNnnnnnnnd...",
            "...Nnnnnnnnnd...",
            "....nnnnnnndd...",
            "....nnnnnnndd...",
            ".....nnnnndd....",
            "......nnndd.....",
            ".......nd.......",
            "................",
        ]),
        ["food"] = new("rC23A2A RE0584A hF8A08A d8A2418 s5E3A1E g6AA640 G3E6E28",
        [
            "................",
            "........s.gg....",
            "........sgGGg...",
            "...RRRR.srrrr...",
            "..RhhRRRrrrrrr..",
            ".RhhRRRrrrrrrrr.",
            ".RhRRRrrrrrrrrr.",
            ".RRRRrrrrrrrrrd.",
            ".RRRrrrrrrrrrrd.",
            ".RRrrrrrrrrrrdd.",
            ".rrrrrrrrrrrrdd.",
            "..rrrrrrrrrrdd..",
            "..rrrrrrrrrddd..",
            "...rrrr..rddd...",
            "................",
            "................",
        ]),
        // Orchard fruit, kept apart from foraged food.
        ["fruit"] = new("yC9C24E YDCD872 hF2EEB0 d8E8428 s5E3A1E g6AA640 G3E6E28",
        [
            "................",
            "........s.......",
            "........sgg.....",
            ".......yyGGg....",
            "......yYyyy.....",
            "......Yhyyy.....",
            ".....yYhyyyd....",
            "....yYhyyyyyd...",
            "...yYyyyyyyyyd..",
            "..yYyyyyyyyyydd.",
            "..Yhyyyyyyyyydd.",
            "..yyyyyyyyyyydd.",
            "..dyyyyyyyyyddd.",
            "...ddyyyyyyddd..",
            ".....ddddddd....",
            "................",
        ]),
        ["berries"] = new("m7E3A96 hC89AE6 lA060C0 d4E2262 g6AA640 G3E6E28 s5E3A1E",
        [
            "................",
            ".......gg.......",
            "......gGGg......",
            ".......s.s......",
            ".....lm...lm....",
            "....lhmm.lhmm...",
            "....mmmd.mmmd...",
            ".....dd...dd....",
            "...lm...lm......",
            "..lhmm.lhmm.lm..",
            "..mmmd.mmmdlhmm.",
            "...dd...dd.mmmd.",
            "............dd..",
            "................",
            "................",
            "................",
        ]),
        ["wild_greens"] = new("h8DB660 v9BC66F b6C9A4B s557D3E g8DB660 G476B36",
        [
            "................",
            ".......h........",
            "......hvb.......",
            ".h....hvbs....s.",
            ".hh..hhvbs...bs.",
            ".hvb.hvvbs..bvs.",
            "..hvbhbvbs.bvbs.",
            "..hbvbhvbsbvbs..",
            "...hbvbvbbvbs...",
            "....hbvvvvbs....",
            ".....hbvvbs.....",
            "......gGGG......",
            ".......gG.......",
            ".......gG.......",
            "................",
            "................",
        ]),
        ["potato"] = new("wE3D6B5 hD2AC77 lA77C52 e8A6440",
        [
            "................",
            "................",
            "................",
            "...whhhh........",
            "..whhhhhhl......",
            ".whhehhhhhl.....",
            ".hhhhhhhehl.....",
            ".hhhhhhhhll.....",
            ".hheehhhhll.....",
            ".lhhhhhhll......",
            "..llhhll..hhh...",
            "...llll..whhhl..",
            ".........hhehll.",
            ".........lhhlll.",
            "..........llll..",
            "................",
        ]),
        // Drinking water, a drop so it never reads as the jug.
        ["water"] = new("wE8FFFF h8ABBD6 l6A9FC0 m598FB3 d4A7B9D",
        [
            "................",
            ".......hl.......",
            ".......hm.......",
            "......hllm......",
            "......hlmm......",
            ".....hllmmm.....",
            ".....hlmmmd.....",
            "....hllmmmmd....",
            "....hwlmmmmd....",
            "...hwllmmmmmd...",
            "...hwlmmmmmmd...",
            "...hwlmmmmmdd...",
            "...hlmmmmmmdd...",
            "....lmmmmmdd....",
            ".....dddddd.....",
            "................",
        ]),
        ["bread"] = new("cC07A34 CDC9C52 hF2C27E uF0DA9A d8A5222 k6A3C18",
        [
            "................",
            "................",
            "................",
            "................",
            "......CCCC......",
            "....CChhCCcc....",
            "...ChhhuCCCuc...",
            "..ChhCuCCCuCcc..",
            ".ChhCuCCCuCCccd.",
            ".cCCuCCCuCCcccd.",
            ".cCCCCCCCCCcccd.",
            ".cccccccccccccd.",
            "..cccccccccccdd.",
            "...kdddddddddk..",
            "................",
            "................",
        ]),
        ["porridge"] = new("RD2AC77 bA77C52 B8A6440 d6E4E31 cFFF5DF CE8DCC0 qCABC99 sD2AC77 SA77C52",
        [
            "................",
            "............sS..",
            "...........sS...",
            "..........sS....",
            ".....ccccsSc....",
            "...ccCCCsSCqq...",
            "..RcCCCCCCCqqR..",
            ".RcCCCqCCCCqqqR.",
            ".RCCCCCCCCqqqqR.",
            ".bRRRRRRRRRRRRB.",
            ".bbbbBBBBBBBBBd.",
            "..bbBBBBBBBBBd..",
            "...BBBBBBBBBd...",
            "....dBBBBBBd....",
            ".....dddddd.....",
            "................",
        ]),
        ["stew"] = new("REFA882 bD5825A BB8623C d8E4428 o8A6440 O6E4E31 yA77C52 pD2AC77 PE3D6B5 g8DB660 G557D3E",
        [
            "................",
            "................",
            "................",
            "................",
            "....RRRRRRRR....",
            "..RRyooPpooyRR..",
            ".RooPpoogGooOOR.",
            ".RyGgooooPpoOOR.",
            ".bRoooGgooOOORd.",
            "..bRRRRRRRRRRd..",
            ".bbBBBBBBBBBBdd.",
            ".dbbBBBBBBBBddd.",
            "..bbBBBBBBBBdd..",
            "...bBBBBBBBBd...",
            ".....dddddd.....",
            "................",
        ]),
        ["meal"] = new("PFFF5DF pE8DCC0 qCABC99 QA09170 wE3D6B5 hD2AC77 lA77C52 e8A6440 g8DB660 G6C9A4B k476B36",
        [
            "................",
            "................",
            "................",
            "................",
            "...gg...........",
            "..gGGg.whh......",
            ".gGkGgwhhhl.....",
            ".kgGkGhhhhe.wh..",
            "..kGkkhhhlewhhl.",
            ".PPPPPPlllehhll.",
            ".Ppppppppppppll.",
            ".qpppppppppppQQ.",
            "..qqqqqqqqqqQQ..",
            "....QQQQQQQQ....",
            "................",
            "................",
        ]),
        ["cloth"] = new("hFFF5DF lE8DCC0 mCABC99 dA09170 k75674D",
        [
            "................",
            "................",
            "................",
            "....hhhhhhhhh...",
            "...hlllllllllm..",
            "..hlllllllllll..",
            ".hllllllllllllm.",
            ".hlllhllllllmmd.",
            ".hlllhlmmmmlmmd.",
            ".hlllhmmmmmlmmd.",
            ".hlllhlmmmmlmmd.",
            "..lllllmmllmmdd.",
            "...mmmmmmmmdddk.",
            "....ddddddddkk..",
            "................",
            "................",
        ]),
        ["clothing"] = new("b4A6E9E B6C92C4 h92B4DE d32507E k263E62 t7A4E2A TC09A5A",
        [
            "................",
            "................",
            "....bBhkkBbb....",
            "..bBhhBhkBBBbd..",
            ".bBhhBBBBBBBBbd.",
            ".bhBBBBBBBBBbbd.",
            ".BhBBBBBBBBBbdd.",
            ".ddbhBBBBBBbbdd.",
            "....hBBBBBbd....",
            "....tttTTttt....",
            "....hBBBBBbd....",
            "....hBBBBBbd....",
            "...hBBBBBBBbd...",
            "...dddddddddd...",
            "................",
            "................",
        ]),
        ["bandage"] = new("hFFF5DF lE8DCC0 mCABC99 dA09170",
        [
            "................",
            "................",
            "................",
            ".....hhhh.......",
            "...hhllllhm.....",
            "..hlldddllmm....",
            "..hldlllldmm....",
            ".hldlhhdldlmm...",
            ".hldlhddldlmm...",
            ".hlldllldllmhhh.",
            "..hlldddllmmlll.",
            "..lllllllmmllmd.",
            "...mmmmmmmlllmd.",
            ".........mmmmd..",
            "................",
            "................",
        ]),
        ["medicine"] = new("cA77C52 C6E4E31 gDCE5E0 GB8C6C4 rC4474B RA33A3F pF08A8A LE8DCC0 x557D3E",
        [
            "................",
            "......cccc......",
            "......cCCC......",
            ".......gG.......",
            "......ggGG......",
            ".....gprrRG.....",
            "....gprrrrRG....",
            "...gprrrrrrRG...",
            "...grLLxLLrRG...",
            "...grLxxxLrRG...",
            "...grLLxLLrRG...",
            "...grrrrrrRRG...",
            "....GrrrrRRG....",
            ".....GGGGGG.....",
            "................",
            "................",
        ]),
        ["basket"] = new("hF0DA9A lE6C77B bD2AE5E sA98A45 e6B5528",
        [
            "................",
            ".....hlllls.....",
            "....hl....bs....",
            "...hl......bs...",
            "...hl......bs...",
            "...hl......bs...",
            ".hhllllllllllls.",
            ".lsssssssssssse.",
            ".llbbllbbllbbse.",
            "..bbllbbllbbse..",
            "..llbbllbbllse..",
            "..bbllbbllbbse..",
            "...llbbllbbse...",
            "....eeeeeeee....",
            "................",
            "................",
        ]),
        ["water_jug"] = new("hEFA882 lD5825A bB8623C s8E4428 w7FB4CF",
        [
            "................",
            "....hhhhhh......",
            "....hwwwwb......",
            ".....lbbs.......",
            ".....lbbsbllb...",
            "....hlbbbs..lb..",
            "...hlbbbbbs..lb.",
            "..hlbbbbbbbs.ls.",
            "..lbbbbbbbbbbs..",
            "..lbbbbbbbbbs...",
            "..lbbbbbbbbbs...",
            "..bbbbbbbbbbs...",
            "...bbbbbbbbs....",
            "....sssssss.....",
            "................",
            "................",
        ]),
        ["wooden_axe"] = new(Handle + " " + Cord + " hD2AC77 lA77C52 m8A6440 d6E4E31",
        [
            "................",
            ".hh......HD.....",
            ".hlll....HD.....",
            ".hllllllcCcC....",
            ".hlllmmmCcCc....",
            ".hlmmmmmcCcC....",
            ".hmmdddmCcCc....",
            ".mmd.....HD.....",
            ".dd......HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........DD.....",
            "................",
        ]),
        ["stone_axe"] = new(Handle + " " + Cord + " hA49C95 l8B837D m756D68 d625B56",
        [
            "................",
            "..hh.....HD.....",
            ".hhll....HD.....",
            ".hlhllmmcCcC....",
            ".hllmlmmCcCc....",
            ".lhlmmdmcCcC....",
            ".lmmdmddCcCc....",
            ".mmdd....HD.....",
            "..dd.....HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........DD.....",
            "................",
        ]),
        ["iron_axe"] = new(Handle + " " + Steel,
        [
            "................",
            "..ll.....HD.....",
            ".wllll..lmmd....",
            ".wllmmmmlwmdd...",
            ".wlmmmmmlmmdd...",
            ".wlmmdddlmmdd...",
            ".wmmdd..lmmd....",
            ".wmdd....HD.....",
            "..dd.....HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........HD.....",
            ".........DD.....",
            "................",
        ]),
        ["wooden_pickaxe"] = new("HC08448 D7A4E26 g8C8984 GB8B5AE k5E5C57",
        [
            "................",
            "................",
            "....GGGHDGGG....",
            "..GGgggHDgggkk..",
            ".Ggk...HD...kgk.",
            ".gk....HD....kk.",
            ".k.....HD.....k.",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......DD.......",
            "................",
            "................",
        ]),
        ["iron_pickaxe"] = new(Handle + " " + Steel,
        [
            "................",
            ".......HD.......",
            "...wlllwmmmmd...",
            "..wllmlwmmmmdd..",
            ".wlm..lmmd..mdd.",
            ".wl....HD....dd.",
            ".l.....HD.....d.",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......HD.......",
            ".......DD.......",
            "................",
        ]),
        ["sickle"] = new(Handle + " " + Steel,
        [
            "................",
            ".....mmmmm......",
            "...mmwlllmmd....",
            "..mlw.....lmd...",
            ".mlw.......lmd..",
            ".mw........lmd..",
            ".mw........lmd..",
            "..w........lmd..",
            "...........lmd..",
            "..........kmmk..",
            "...........HD...",
            "...........HD...",
            "...........HD...",
            "...........HD...",
            "...........DD...",
            "................",
        ]),
        ["tool"] = new("HC08448 D7A4E26 g8C8984 GB8B5AE k5E5C57",
        [
            "................",
            "................",
            "..kGGGGGGGGk....",
            "..kGgggggggk....",
            "..kkkkHDkkkk....",
            "......HD........",
            "......HD........",
            "......HD........",
            "......HD........",
            "......HD........",
            "......HD........",
            "......HD........",
            "......HD........",
            "......DD........",
            "................",
            "................",
        ]),
        // A field map: knowledge of several sites, drawn as a folded map.
        ["field_map"] = new("hE3D6B5 lC8B78C bBAA77B sA08F66 g6FA069 G527F4F w4786AB rC4474B",
        [
            "................",
            "................",
            ".hhhhh.....hhhh.",
            ".hhgghlllllhhhh.",
            ".hgGGhbbbbbhrhh.",
            ".hgggwwbbbblrhh.",
            ".hhhhlbwwbbhrhh.",
            ".hrhhlbbbwwhrhh.",
            ".hhrrlrrbbbwwwh.",
            ".hhhhlbbrrrhhrh.",
            ".hhhhlbbbbbhrhr.",
            ".hhhhlbbbbbhhhh.",
            ".sssssbbbbbssss.",
            "......sssss.....",
            "................",
            "................",
        ]),
        // A field record: knowledge of one site, drawn as a closed book.
        ["field_record"] = new("RF08A8A rC4474B sA33A3F e7A2A2E pFFF5DF PCABC99 GF2CC5E",
        [
            "................",
            "................",
            "...RRRRRRRRRR...",
            "..eRrrrrrrrrrs..",
            "..eRrrrrrrrrrsp.",
            "..eRrrrGGrrrrsp.",
            "..eRrrGrrGrrrsp.",
            "..eRrrrGGrrrrsp.",
            "..eRrrrrrrrrrsp.",
            "..eRrrrrrrrrrsp.",
            "..eRrrrrrrrrrsp.",
            "..essssssssssPp.",
            "...pppppppppppP.",
            "....PPPPPPPPPP..",
            "................",
            "................",
        ]),
        ["coin"] = new("hFFE28A lF2CC5E bD9AE3C mB8902E d8A6A1E",
        [
            "................",
            "................",
            ".....hhhhhh.....",
            "...hhllllllhm...",
            "..hllbbbbbbllm..",
            "..hlbbbbhbbblm..",
            ".hlbbbbhlmbbblm.",
            ".hlbbbhlllmbblm.",
            ".hlbbbbmlmbbblm.",
            "..hlbbbbmbbblm..",
            "..mllbbbbbbllm..",
            "..dmmllllllmmd..",
            "...ddmmmmmmdd...",
            ".....dddddd.....",
            "................",
            "................",
        ]),
        ["crate"] = new("wB07A42 WD09A5A d7A4E26",
        [
            "................",
            "................",
            ".WWWWWWWWWWWWWW.",
            ".WddwwwwwwwwwdW.",
            ".WwddwwwwwwwwwW.",
            ".WwwddwwwwwwwwW.",
            ".WwwwddwwwwwwwW.",
            ".WWWWWWWWWWWWWW.",
            ".WwwwwwwddwwwwW.",
            ".WwwwwwwwddwwwW.",
            ".WwwwwwwwwddwwW.",
            ".WwwwwwwwwwddwW.",
            ".WdwwwwwwwwwddW.",
            ".dddddddddddddd.",
            "................",
            "................",
        ]),
    };

    /// <summary>The item kinds that have their own icon.</summary>
    public static IReadOnlyCollection<string> Kinds => Icons.Keys.Where(kind => kind != Fallback).ToArray();

    /// <summary>Whether this kind has its own icon rather than the crate.</summary>
    public static bool Has(string kind) => kind != Fallback && Icons.ContainsKey(kind);

    public static ImageTexture Texture(string kind, int size)
    {
        var key = (kind, size);
        if (Cache.TryGetValue(key, out var cached)) return cached;
        var texture = ImageTexture.CreateFromImage(Render(kind, size));
        Cache[key] = texture;
        return texture;
    }

    /// <summary>
    /// The icon at the largest whole-number scale that fits <paramref name="size"/>,
    /// centred on a transparent square of that size.
    /// </summary>
    public static Image Render(string kind, int size)
    {
        var art = OutlinedArt(Icons.ContainsKey(kind) ? kind : Fallback);
        var scale = Math.Max(1, size / Grid);
        var offset = (size - Grid * scale) / 2;
        var image = Image.CreateEmpty(size, size, false, Image.Format.Rgba8);
        image.Fill(Colors.Transparent);
        for (var y = 0; y < Grid; y++)
            for (var x = 0; x < Grid; x++)
            {
                var color = art.GetPixel(x, y);
                if (color.A > 0) image.FillRect(new Rect2I(offset + x * scale, offset + y * scale, scale, scale), color);
            }
        return image;
    }

    /// <summary>The 16 × 16 art with its outline, drawn once per kind.</summary>
    public static Image OutlinedArt(string kind)
    {
        if (Art.TryGetValue(kind, out var cached)) return cached;
        var icon = Icons[kind];
        var palette = icon.Palette.Split(' ').ToDictionary(entry => entry[0], entry => new Color(entry[1..]));
        var fill = new Color?[Grid, Grid];
        for (var y = 0; y < Grid; y++)
            for (var x = 0; x < Grid; x++)
                if (icon.Rows[y][x] is not '.' and var key) fill[x, y] = palette[key];
        var image = Image.CreateEmpty(Grid, Grid, false, Image.Format.Rgba8);
        image.Fill(Colors.Transparent);
        for (var y = 0; y < Grid; y++)
            for (var x = 0; x < Grid; x++)
            {
                if (fill[x, y] is { } color)
                {
                    image.SetPixel(x, y, color);
                    continue;
                }
                // An empty pixel beside the silhouette becomes outline, in a
                // dark shade of the darkest colour it touches.
                Color? darkest = null;
                foreach (var (dx, dy) in new[] { (1, 0), (-1, 0), (0, 1), (0, -1) })
                    if (x + dx is >= 0 and < Grid && y + dy is >= 0 and < Grid && fill[x + dx, y + dy] is { } near &&
                        (darkest is null || near.Luminance < darkest.Value.Luminance))
                        darkest = near;
                if (darkest is { } edge) image.SetPixel(x, y, (edge * 0.42f).Lerp(Ink, 0.45f) with { A = 1 });
            }
        Art[kind] = image;
        return image;
    }

    /// <summary>Whether every row is 16 wide and no pixel touches the edge, so the outline fits.</summary>
    public static bool FitsGrid(string kind) => Icons.TryGetValue(kind, out var icon) && icon.Rows.Length == Grid &&
        icon.Rows.All(row => row.Length == Grid) &&
        icon.Rows[0].All(pixel => pixel == '.') && icon.Rows[^1].All(pixel => pixel == '.') &&
        icon.Rows.All(row => row[0] == '.' && row[^1] == '.');
}
